#ifndef _LIPRO_MEMMAP_H
#define _LIPRO_MEMMAP_H

#define ROM_BASE 0
#define ROM_SIZE 0x20000
#define RAM_BASE 0x100000
#define RAM_SIZE 0x800000

#define BL_CODE_START ROM_BASE
#define BL_CODE_SIZE  ROM_SIZE
#define BL_DATA_START RAM_BASE
#define BL_DATA_SIZE  0x20000

#define MP_CODE_START (BL_DATA_START + BL_DATA_SIZE)
#define MP_CODE_SIZE  0x80000
#define MP_DATA_START (MP_CODE_START + MP_CODE_SIZE)
#define MP_DATA_SIZE  0x80000

#define MC_CODE_START (MP_DATA_START + MP_DATA_SIZE)
#define MC_CODE_SIZE  0x80000
#define MC_DATA_START (MC_CODE_START + MC_CODE_SIZE)
#define MC_DATA_SIZE  0x80000

// second stage boot loader
#define SSTG_CODE_START (MC_DATA_START + MC_DATA_SIZE)
#define SSTG_CODE_SIZE  0x4000
#define SSTG_DATA_START (SSTG_CODE_START + SSTG_CODE_SIZE)
#define SSTG_DATA_SIZE  0x4000

#define SHARED_DATA_START (SSTG_DATA_START + SSTG_DATA_SIZE)
#define SHARED_DATA_SIZE  0x20000
                  
#endif // _LIPRO_MEMMAP_H
