## Metaware Toolchain Options For Core ##
COMMON_CORE_OPT_MW = @$(EMBARC_GENERATED_DIR)/$(GENE_CCAC_ARG)

CCORE_OPT_MW   += $(COMMON_CORE_OPT_MW)
CXXCORE_OPT_MW += $(COMMON_CORE_OPT_MW)
ACORE_OPT_MW   += $(COMMON_CORE_OPT_MW)
LCORE_OPT_MW   += $(COMMON_CORE_OPT_MW)

## GNU Toolchain Options For Core ##
COMMON_CORE_OPT_GNU = @$(EMBARC_GENERATED_DIR)/$(GENE_GCC_ARG)

CCORE_OPT_GNU   += $(COMMON_CORE_OPT_GNU)
CXXCORE_OPT_GNU += $(COMMON_CORE_OPT_GNU)
ACORE_OPT_GNU   += $(COMMON_CORE_OPT_GNU)
LCORE_OPT_GNU   += $(COMMON_CORE_OPT_GNU)