#ifndef _APPL_MEM_CONFIG_H_
#define _APPL_MEM_CONFIG_H_

#if defined(BOARD_EMSK)
/* arcem9d only */
#ifndef __MW__
/* GNU toolchain needs more memory */
#define REGION_ROM      REGION_EXT_ROM
#define REGION_RAM      REGION_EXT_RAM
#endif


#define REGION_MLI_ROM		REGION_ROM
#define REGION_MLI_DATA		REGION_DCCM
#define REGION_MLI_BSS		REGION_DCCM
#define REGION_MLI_ZDATA	REGION_DCCM
#define REGION_MLI_MODEL_P2	REGION_DCCM
#define REGION_MLI_MODEL	REGION_DCCM
#define REGION_MLI_XDATA	REGION_XCCM
#define REGION_MLI_YDATA	REGION_YCCM

#elif defined(BOARD_IOTDK)
#ifndef __MW__
/* GNU toolchain needs more memory */
#define EXT_ROM_START	BOOT_SPI_FLASH_BASE
#define EXT_ROM_SIZE	BOOT_SPI_FLASH_SIZE
#define REGION_ROM	REGION_EXT_ROM
#define REGION_RAM	REGION_EXT_RAM
#endif

#define REGION_MLI_ROM		REGION_ROM
#define REGION_MLI_DATA		REGION_DCCM
#define REGION_MLI_BSS		REGION_DCCM
#define REGION_MLI_ZDATA	REGION_DCCM
#define REGION_MLI_MODEL_P2	REGION_DCCM
#define REGION_MLI_MODEL	REGION_XCCM
#define REGION_MLI_XDATA	REGION_XCCM
#define REGION_MLI_YDATA	REGION_YCCM

#elif defined(BOARD_EMSDP)

#ifndef __MW__
/* GNU toolchain needs more memory */
#define REGION_ROM      REGION_EXT_RAM
#define REGION_RAM      REGION_EXT_RAM
#endif

#define REGION_MLI_ROM		REGION_ROM
#define REGION_MLI_DATA		REGION_DCCM
#define REGION_MLI_BSS		REGION_DCCM
#define REGION_MLI_ZDATA	REGION_DCCM
#define REGION_MLI_MODEL_P2	REGION_DCCM
#define REGION_MLI_MODEL	REGION_XCCM
#define REGION_MLI_XDATA	REGION_XCCM
#define REGION_MLI_YDATA	REGION_YCCM

#elif defined(BOARD_NSIM)
#define REGION_MLI_ROM		REGION_ICCM
#define REGION_MLI_DATA		REGION_DCCM
#define REGION_MLI_BSS		REGION_DCCM
#define REGION_MLI_ZDATA	REGION_DCCM
#define REGION_MLI_MODEL_P2	REGION_DCCM
#define REGION_MLI_MODEL	REGION_XCCM
#define REGION_MLI_XDATA	REGION_XCCM
#define REGION_MLI_YDATA	REGION_YCCM
#endif

#endif /* _APPL_MEM_CONFIG_H_ */