image: python:2.7

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
  OSP_ROOT: "."
  TOOLCHAIN: "gnu"
  TOOLCHAIN_VER: "latest"
  EXPECTED: ".ci/expected.ini"

cache:
  paths:
    - .cache/result
    - .cache/toolchain


before_script:
  - bash .ci/before_install.sh

stages:
  - build
  - deploy

baremetal-emsk-gnu-latest:
  stage: build
  variables:
    BOARD: "emsk"
    EXAMPLES: "example/baremetal"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

baremetal-emsk-gnu-201803:
  stage: build
  variables:
    TOOLCHAIN_VER: "2018.03"
    BOARD: "emsk"
    EXAMPLES: "example/baremetal"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_11-gnu-latest:
  stage: build
  variables:
    BOARD: "emsk"
    BD_VER: "11"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_11-gnu-201803:
  stage: build
  variables:
    BOARD: "emsk"
    BD_VER: "11"
    TOOLCHAIN_VER: "2018.03"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_22-gnu-latest:
  stage: build
  variables:
    BOARD: "emsk"
    BD_VER: "22"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_22-gnu-201803:
  stage: build
  variables:
    BD_VER: "22"
    BOARD: "emsk"
    TOOLCHAIN_VER: "2018.03"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_23-gnu-latest:
  stage: build
  variables:
    BOARD: "emsk"
    BD_VER: "23"
    PARALLEL: 8
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_23-gnu-201803:
  stage: build
  variables:
    BOARD: "emsk"
    BD_VER: "23"
    PARALLEL: 8
    TOOLCHAIN_VER: "2018.03"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

arc_feature-gnu-latest:
  stage: build
  variables:
    EXAMPLES: "example/baremetal/arc_feature"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

arc_feature-gnu-201803:
  stage: build
  variables:
    TOOLCHAIN_VER: "2018.03"
    EXAMPLES: "example/baremetal/arc_feature"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

baremetal-emsk-mw-latest:
  stage: build
  variables:
    BOARD: "emsk"
    TOOLCHAIN: "mw"
    EXAMPLES: "example/baremetal"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

baremetal-emsk-mw-201806:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    TOOLCHAIN_VER: "2018.06"
    BOARD: "emsk"
    EXAMPLES: "example/baremetal"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_11-mw-latest:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    BOARD: "emsk"
    BD_VER: "11"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_11-mw-201806:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    BOARD: "emsk"
    BD_VER: "11"
    TOOLCHAIN_VER: "2018.06"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_22-mw-latest:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    BOARD: "emsk"
    BD_VER: "22"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_22-mw-201806:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    BD_VER: "22"
    BOARD: "emsk"
    TOOLCHAIN_VER: "2018.06"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_23-mw-latest:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    BOARD: "emsk"
    BD_VER: "23"
    PARALLEL: 8
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

freertos-emsk_23-mw-201806:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    BOARD: "emsk"
    BD_VER: "23"
    PARALLEL: 8
    TOOLCHAIN_VER: "2018.06"
    EXAMPLES: "example/freertos"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

arc_feature-mw-latest:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    EXAMPLES: "example/baremetal/arc_feature"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

arc_feature-mw-201806:
  stage: build
  variables:
    TOOLCHAIN: "mw"
    TOOLCHAIN_VER: "2018.06"
    EXAMPLES: "example/baremetal/arc_feature"
  script:
  - bash .ci/script.sh
  except:
  - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result

deploy_prod:
  stage: deploy
  script:
    - python .ci/build.py
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_COMMIT_REF_SLUG.example.com
  except:
    - gh-pages
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
      - .cache/result