
/* **** DO NOT EDIT - this file is generated by ARChitect2 ****
 *
 * Description: Header file declaring the compiler extensions for eia components 
 */

#ifndef _dsp_config_H_
#define _dsp_config_H_


#define DSP_TRIG_PRESENT

#endif


