CONTIKI_TARGET_DIRS = . dev net net/mrf24j40 net/mrf24g dev/sensors

CONTIKI_TARGET_SOURCEFILES = contiki-main.c mtarch.c mtarch-asm.s clock.c rtimer-arch.c leds-arch.c init-net.c mrf24j40.c \
							 button-sensor.c temperature-sensor.c mrf24g_drv.c watchdog.c
CONTIKI_SOURCEFILES += $(CONTIKI_TARGET_SOURCEFILES)


### Define the CPU directory
CONTIKI_CPU=$(CONTIKI)/cpu/arc

## Default modules
MODULES += core/net/mac core/net core/net/llsec core/net/llsec/noncoresec
