
/* **** DO NOT EDIT - this file is generated by ARChitect2 ****
 *
 * Description: Header file declaring the compiler extensions for eia components 
 */

#ifndef _dsp_config_H_
#define _dsp_config_H_


#define DSP_MAC_PRESENT
#define DSP_MAC_IO_FW (15)
#define DSP_MAC_ACC_SIZE (min)
#define DSP_MAC_Z_WRAP (floor)
#define DSP_ABS_PRESENT
#define DSP_ADD_PRESENT
#define DSP_MULT_PRESENT
#define DSP_MULV_PRESENT
#define DSP_NEGATE_PRESENT
#define DSP_SHIFT_PRESENT
#define DSP_SINCOS_PRESENT
#define DSP_SQRT_PRESENT
#define DSP_SUB_PRESENT

#endif
