embARC: ad7991.c File Reference
ad7991.c File Reference
PMOD AD2 ADC Driver.
#include "arc.h"
#include "arc_builtin.h"
#include "embARC_toolchain.h"
#include "embARC_error.h"
#include "embARC_debug.h"
#include "dev_iic.h"
#include "ad7991.h"
#include "board.h"
Macros
#define AD7991_CONFIG_BIT_TRAIL_DELAY (1 << 0)
AD7991_REG_CONFIG definition.
#define AD7991_CONFIG_SAMPLE_DELAY (1 << 1)
#define AD7991_CONFIG_FLTR (1 << 2)
#define AD7991_CONFIG_REF_SEL (1 << 3)
#define EMSK_ADC_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
AD7991_CONFIG_CH0 ~ CH3 defines see ad7991.h.
Functions
static int32_t _ad7991_reg_write (AD7991_DEF_PTR obj, uint8_t val)
write ad7991 register
static int32_t _ad7991_reg_read (AD7991_DEF_PTR obj, uint8_t *val, uint8_t channel_num)
read ad7991 register
int32_t ad7991_adc_init (AD7991_DEF_PTR obj)
ad7991 init function
int32_t ad7991_adc_deinit (AD7991_DEF_PTR obj)
ad7991 deinit
int32_t ad7991_ref_select (AD7991_DEF_PTR obj, int32_t source)
ad7991 reference voltage source selection
int32_t ad7991_adc_channel (AD7991_DEF_PTR obj, int8_t channel)
ad7991 adc channel setting
int32_t ad7991_adc_read (AD7991_DEF_PTR obj, float *val)
read 4 channel ADC converted value in 1.0 mV unit
Detailed Description
PMOD AD2 ADC Driver.
Realize driver for PMOD AD2 ADC using I2C driver.
pmod AD2 ADC(ad7991) driver
Definition in file ad7991.c.
Function Documentation
static int32_t _ad7991_reg_read (AD7991_DEF_PTR obj, uint8_t * val, uint8_t channel_num) static
read ad7991 register
Parameters
[in] obj ad7991 object
[in] val pointer to buffer to read
[in] channel_num active channel number
Return values
>=0 read success, return bytes read
<E_OK read failed
Definition at line 97 of file ad7991.c.
References CONV2VOID, E_PAR, EMSK_ADC_CHECK_EXP_NORTN, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_STOP, and dev_iic::iic_read.
Referenced by ad7991_adc_read().
static int32_t _ad7991_reg_write (AD7991_DEF_PTR obj, uint8_t val) static
write ad7991 register
Parameters
[in] obj ad7991 object
[in] val config value to write
Return values
>=0 write success, return bytes written
!E_OK write failed
Definition at line 72 of file ad7991.c.
References CONV2VOID, E_PAR, EMSK_ADC_CHECK_EXP_NORTN, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by ad7991_adc_channel(), and ad7991_ref_select().
int32_t ad7991_adc_channel (AD7991_DEF_PTR obj, int8_t channel)
ad7991 adc channel setting
Parameters
[in] obj ad7991 object
[in] channel channel selection
Return values
E_OK always return E_OK
Definition at line 189 of file ad7991.c.
References _ad7991_reg_write(), and E_OK.
Referenced by ad7991_adc_init(), and ad7991_ref_select().
int32_t ad7991_adc_deinit (AD7991_DEF_PTR obj)
ad7991 deinit
Parameters
[in] obj ad7991 object
Return values
E_OK init success
!E_OK init failed
Definition at line 149 of file ad7991.c.
References E_OK, dev_iic::iic_close, and iic_get_dev().
int32_t ad7991_adc_init (AD7991_DEF_PTR obj)
ad7991 init function
Parameters
[in] obj ad7991 object
Return values
E_OK init success
!E_OK init failed
Definition at line 121 of file ad7991.c.
References ad7991_adc_channel(), ad7991_ref_select(), CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, EMSK_ADC_CHECK_EXP_NORTN, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, and IIC_SPEED_HIGH.
int32_t ad7991_adc_read (AD7991_DEF_PTR obj, float * val)
read 4 channel ADC converted value in 1.0 mV unit
Parameters
[in] obj ad7991 object
[out] val need at least float [4] array to run, return latest avaiable convert data, array index corresponding to channel
Return values
E_OK read success
!E_OK read failed
Definition at line 218 of file ad7991.c.
References _ad7991_reg_read(), E_OBJ, E_OK, and EMSK_ADC_CHECK_EXP_NORTN.
int32_t ad7991_ref_select (AD7991_DEF_PTR obj, int32_t source)
ad7991 reference voltage source selection
Parameters
[in] obj ad7991 object
[in] source sensor working source, choose from enum sensor_op_mode
Return values
E_OK always return E_OK
Definition at line 163 of file ad7991.c.
References _ad7991_reg_write(), ad7991_adc_channel(), and E_OK.
Referenced by ad7991_adc_init().