embARC: ad7991.h File Reference
ad7991.h File Reference
header file of emsk pmod AD2 ADC driver
#include "dev_iic.h"
Data Structures
struct AD7991_DEF
AD7991 object type.
Macros
#define AD2_JUMPER_REF 0
PMOD AD2 board (AD7991) has to choose its voltage reference form power supply, or external on board 2.048V Voltage Reference (ADR380) or VIN4 (Ch3) please note that when choose external reference, only 3 channels are converting.
#define AD2_JUMPER_VIN4 1
#define AD2_REF_JUMPER AD2_JUMPER_REF
#define AD2_REF_VDD 3300 /*< power supply voltage is 3300mV*/
#define AD2_REF_EXTERNAL 2048 /*< The ADR380 voltage reference on AD2 board has 2048mV output*/
#define AD7991_CONFIG_CH0_EN (1 << 4)
#define AD7991_CONFIG_CH1_EN (1 << 5)
#define AD7991_CONFIG_CH2_EN (1 << 6)
#define AD7991_CONFIG_CH3_EN (1 << 7)
#define AD7991_IIC_ADDRESS 0x28
I2C address : Pmod AD2 (AD7991) uses AD7991-0, has only one address which is 0x28.
#define ADC_I2C_SLAVE_ADDRESS AD7991_IIC_ADDRESS
#define AD7991_DEFINE(NAME, DEVICE_ID, SLAVE_ADDRESS)
Typedefs
typedef enum ad7991_ref_source AD7991_REF_SOURCE
options for reference source parameter of ad7991_ref_select()
typedef struct AD7991_DEF * AD7991_DEF_PTR
Enumerations
enum ad7991_ref_source { AD7991_REF_VDD, AD7991_REF_EXTERNAL }
options for reference source parameter of ad7991_ref_select()
Functions
int32_t ad7991_adc_init (AD7991_DEF_PTR obj)
ad7991 init function
int32_t ad7991_adc_deinit (AD7991_DEF_PTR obj)
ad7991 deinit
int32_t ad7991_ref_select (AD7991_DEF_PTR obj, int32_t source)
ad7991 reference voltage source selection
int32_t ad7991_adc_channel (AD7991_DEF_PTR obj, int8_t channel)
ad7991 adc channel setting
int32_t ad7991_adc_read (AD7991_DEF_PTR obj, float *val)
read 4 channel ADC converted value in 1.0 mV unit
Detailed Description
header file of emsk pmod AD2 ADC driver
Definition in file ad7991.h.
Macro Definition Documentation
#define AD7991_DEFINE (NAME, DEVICE_ID, SLAVE_ADDRESS)
Value:
AD7991_DEF __ ## NAME = { \
                        .dev_id = DEVICE_ID, \
                        .slvaddr = SLAVE_ADDRESS, \
        }; \
        AD7991_DEF_PTR NAME = &__ ## NAME
Definition at line 88 of file ad7991.h.
Function Documentation
int32_t ad7991_adc_channel (AD7991_DEF_PTR obj, int8_t channel)
ad7991 adc channel setting
Parameters
[in] obj ad7991 object
[in] channel channel selection
Return values
E_OK always return E_OK
Definition at line 189 of file ad7991.c.
References _ad7991_reg_write(), and E_OK.
Referenced by ad7991_adc_init(), and ad7991_ref_select().
int32_t ad7991_adc_deinit (AD7991_DEF_PTR obj)
ad7991 deinit
Parameters
[in] obj ad7991 object
Return values
E_OK init success
!E_OK init failed
Definition at line 149 of file ad7991.c.
References E_OK, dev_iic::iic_close, and iic_get_dev().
int32_t ad7991_adc_init (AD7991_DEF_PTR obj)
ad7991 init function
Parameters
[in] obj ad7991 object
Return values
E_OK init success
!E_OK init failed
Definition at line 121 of file ad7991.c.
References ad7991_adc_channel(), ad7991_ref_select(), CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, EMSK_ADC_CHECK_EXP_NORTN, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, and IIC_SPEED_HIGH.
int32_t ad7991_adc_read (AD7991_DEF_PTR obj, float * val)
read 4 channel ADC converted value in 1.0 mV unit
Parameters
[in] obj ad7991 object
[out] val need at least float [4] array to run, return latest avaiable convert data, array index corresponding to channel
Return values
E_OK read success
!E_OK read failed
Definition at line 218 of file ad7991.c.
References _ad7991_reg_read(), E_OBJ, E_OK, and EMSK_ADC_CHECK_EXP_NORTN.
int32_t ad7991_ref_select (AD7991_DEF_PTR obj, int32_t source)
ad7991 reference voltage source selection
Parameters
[in] obj ad7991 object
[in] source sensor working source, choose from enum sensor_op_mode
Return values
E_OK always return E_OK
Definition at line 163 of file ad7991.c.
References _ad7991_reg_write(), ad7991_adc_channel(), and E_OK.
Referenced by ad7991_adc_init().