embARC: adt7420.c File Reference
adt7420.c File Reference
adt7420 pmod temperature sensor driver
#include "arc.h"
#include "arc_builtin.h"
#include "embARC_toolchain.h"
#include "embARC_error.h"
#include "embARC_debug.h"
#include "dev_iic.h"
#include "adt7420.h"
#include "board.h"
Macros
#define STATUS_T_LOW (1 << 4)
#define STATUS_T_HIGH (1 << 5)
#define STATUS_T_CRIT (1 << 6)
#define STATUS_RDY (1 << 7)
#define ADT7420_CONFIG_FAULT_QUEUE(x) (x & 0x3)
#define ADT7420_CONFIG_CT_POL (1 << 2)
#define ADT7420_CONFIG_INT_POL (1 << 3)
#define ADT7420_CONFIG_INT_CT_MODE (1 << 4)
#define ADT7420_CONFIG_OP_MODE(x) ((x & 0x3) << 5)
#define ADT7420_CONFIG_RESOLUTION (1 << 7)
#define ADT7420_DEFAULT_ID 0xCB
#define ADT7420_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
Enumerations
enum registers {
ADT7420_REG_TEMP_MSB = 0x00, ADT7420_REG_TEMP_LSB = 0x01, ADT7420_REG_STATUS = 0x02, ADT7420_REG_CONFIG = 0x03,
ADT7420_REG_T_HIGH_MSB = 0x04, ADT7420_REG_T_HIGH_LSB = 0x05, ADT7420_REG_T_LOW_MSB = 0x06, ADT7420_REG_T_LOW_LSB = 0x07,
ADT7420_REG_T_CRIT_MSB = 0x08, ADT7420_REG_T_CRIT_LSB = 0x09, ADT7420_REG_HIST = 0x0A, ADT7420_REG_ID = 0x0B,
ADT7420_REG_RESET = 0x2F, TCN75_REG_TEMP = 0x00, TCN75_REG_CONFIG = 0x01, TCN75_REG_TEMP_HYST = 0x02,
TCN75_REG_TEMP_SET = 0x03
}
enum fault_queue {
FAULT_QUEUE_1 = 0, FAULT_QUEUE_2 = 1, FAULT_QUEUE_3 = 2, FAULT_QUEUE_4 = 3,
FAULT_QUEUE_1 = 1, FAULT_QUEUE_2 = 2, FAULT_QUEUE_3 = 4, FAULT_QUEUE_4 = 6
}
Functions
static int32_t _adt7420_reg_write (ADT7420_DEF_PTR obj, uint8_t regaddr, uint8_t *val, uint8_t len)
write adt7420 register
static int32_t _adt7420_reg_read (ADT7420_DEF_PTR obj, uint8_t regaddr, uint8_t *val, uint8_t len)
read adt7420 register
int32_t adt7420_sensor_init (ADT7420_DEF_PTR obj)
adt7420 init
int32_t adt7420_sensor_deinit (ADT7420_DEF_PTR obj)
temperature sensor deinit
int32_t adt7420_sensor_mode (ADT7420_DEF_PTR obj, int32_t mode)
temperature sensor deinit
int32_t adt7420_sensor_resolution (ADT7420_DEF_PTR obj, int32_t resolution)
temperature sensor resolution setting
int32_t adt7420_sensor_read (ADT7420_DEF_PTR obj, float *val)
read temperature sensor value in 0.1c unit
Detailed Description
adt7420 pmod temperature sensor driver
Definition in file adt7420.c.
Enumeration Type Documentation
enum registers
ADT7420 registers
Enumerator
ADT7420_REG_TEMP_MSB
ADT7420 Temperature value MSB
ADT7420_REG_TEMP_LSB
ADT7420 Temperature value LSB
ADT7420_REG_STATUS
ADT7420 Status
ADT7420_REG_CONFIG
ADT7420 Configuration
ADT7420_REG_T_HIGH_MSB
ADT7420 Temperature HIGH set point MSB
ADT7420_REG_T_HIGH_LSB
ADT7420 Temperature HIGH set point LSB
ADT7420_REG_T_LOW_MSB
ADT7420 Temperature LOW set point MSB
ADT7420_REG_T_LOW_LSB
ADT7420 Temperature LOW set point LSB
ADT7420_REG_T_CRIT_MSB
ADT7420 Temperature CRIT set point MSB
ADT7420_REG_T_CRIT_LSB
ADT7420 Temperature CRIT set point LSB
ADT7420_REG_HIST
ADT7420 Temperature HYST set point
ADT7420_REG_ID
ADT7420 ID
ADT7420_REG_RESET
ADT7420 Software reset
TCN75_REG_TEMP
TCN75 Temperature value
TCN75_REG_CONFIG
TCN75 Configuration
TCN75_REG_TEMP_HYST
TCN75 Hysteresis Temperature value
TCN75_REG_TEMP_SET
TCN75 User Set value for Interrupt or Comparator
Definition at line 45 of file adt7420.c.
Function Documentation
static int32_t _adt7420_reg_read (ADT7420_DEF_PTR obj, uint8_t regaddr, uint8_t * val, uint8_t len) static
read adt7420 register
Parameters
[in] obj emperature sensor object
[in] regaddr temperature sensor register address
[in] val pointer to buffer to read
[in] len length of data to read
Return values
>=0 read success, return bytes read
!E_OK read failed
Definition at line 130 of file adt7420.c.
References CONV2VOID, E_PAR, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by adt7420_sensor_mode(), adt7420_sensor_read(), and adt7420_sensor_resolution().
static int32_t _adt7420_reg_write (ADT7420_DEF_PTR obj, uint8_t regaddr, uint8_t * val, uint8_t len) static
write adt7420 register
Parameters
[in] obj temperature sensor object
[in] regaddr temperature sensor register address
[in] val pointer to buffer to write
[in] len length of data in buffer
Return values
>=0 write success, return bytes written
!E_OK write failed
Definition at line 97 of file adt7420.c.
References CONV2VOID, E_PAR, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_RESTART, IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by adt7420_sensor_mode(), and adt7420_sensor_resolution().
int32_t adt7420_sensor_deinit (ADT7420_DEF_PTR obj)
temperature sensor deinit
Parameters
[in] obj temperature sensor object
Return values
E_OK init success
!E_OK init failed
Definition at line 186 of file adt7420.c.
References E_OK, dev_iic::iic_close, and iic_get_dev().
int32_t adt7420_sensor_init (ADT7420_DEF_PTR obj)
adt7420 init
Parameters
[in] obj temperature sensor object
Return values
E_OK init success
!E_OK init failed
Definition at line 158 of file adt7420.c.
References adt7420_sensor_mode(), adt7420_sensor_resolution(), CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, and IIC_SPEED_HIGH.
int32_t adt7420_sensor_mode (ADT7420_DEF_PTR obj, int32_t mode)
temperature sensor deinit
Parameters
[in] obj temperature sensor object
[in] mode sensor working mode, choose from enum sensor_op_mode
Return values
E_OK always return E_OK
Definition at line 206 of file adt7420.c.
References _adt7420_reg_read(), _adt7420_reg_write(), ADT7420_REG_CONFIG, and E_OK.
Referenced by adt7420_sensor_init().
int32_t adt7420_sensor_read (ADT7420_DEF_PTR obj, float * val)
read temperature sensor value in 0.1c unit
Parameters
[in] obj temperature sensor object
[out] val return temperature in degrees Celsius (°C)
Return values
E_OK read success
!E_OK read failed
Definition at line 246 of file adt7420.c.
References _adt7420_reg_read(), ADT7420_REG_TEMP_MSB, E_OBJ, and E_OK.
int32_t adt7420_sensor_resolution (ADT7420_DEF_PTR obj, int32_t resolution)
temperature sensor resolution setting
Parameters
[in] obj temperature sensor object
[in] resolution resolution of temperature sensor
Return values
E_OK always return E_OK
Definition at line 224 of file adt7420.c.
References _adt7420_reg_read(), _adt7420_reg_write(), ADT7420_REG_CONFIG, and E_OK.
Referenced by adt7420_sensor_init().