embARC: adt7420.h File Reference
adt7420.h File Reference
header file of adt7420 pmod temperature sensor driver
#include "dev_iic.h"
Data Structures
struct ADT7420_DEF
Macros
#define ADT7420_A0_PIN 1
I2C address of PmodTmp2 (ADT7420) can be selected via jumpers: 0x48, 0x49, 0x4A, 0x4B Default (all jumpers removed) is 0x4B.
#define ADT7420_A1_PIN 1
#define ADT7420_IIC_ADDRESS (0x48 + (ADT7420_A1_PIN << 1) + ADT7420_A0_PIN)
#define TEMP_I2C_SLAVE_ADDRESS ADT7420_IIC_ADDRESS
#define ADT7420_DEFINE(NAME, I2C_ID, SLAVE_ADDRESS)
Typedefs
typedef struct ADT7420_DEF * ADT7420_DEF_PTR
Enumerations
enum ADT7420_OP_MODE { ADT7420_OP_MODE_CONT_CONV = 0, ADT7420_OP_MODE_ONE_SHOT = 1, ADT7420_OP_MODE_1_SPS = 2, ADT7420_OP_MODE_SHUTDOWN = 3 }
enum ADT7420_RESOLUTION { ADT7420_RESOLUTION_13BIT, ADT7420_RESOLUTION_16BIT }
Functions
int32_t adt7420_sensor_init (ADT7420_DEF_PTR obj)
adt7420 init
int32_t adt7420_sensor_deinit (ADT7420_DEF_PTR obj)
temperature sensor deinit
int32_t adt7420_sensor_mode (ADT7420_DEF_PTR obj, int32_t mode)
temperature sensor deinit
int32_t adt7420_sensor_resolution (ADT7420_DEF_PTR obj, int32_t resolution)
temperature sensor resolution setting
int32_t adt7420_sensor_read (ADT7420_DEF_PTR obj, float *val)
read temperature sensor value in 0.1c unit
Detailed Description
header file of adt7420 pmod temperature sensor driver
Definition in file adt7420.h.
Macro Definition Documentation
ADT7420_A0_PIN
#define ADT7420_A0_PIN 1
I2C address of PmodTmp2 (ADT7420) can be selected via jumpers: 0x48, 0x49, 0x4A, 0x4B Default (all jumpers removed) is 0x4B.
I2C Serial Bus Address Selection Pin
Definition at line 44 of file adt7420.h.
ADT7420_A1_PIN
#define ADT7420_A1_PIN 1
I2C Serial Bus Address Selection Pin
Definition at line 45 of file adt7420.h.
ADT7420_DEFINE
#define ADT7420_DEFINE (NAME, I2C_ID, SLAVE_ADDRESS)
Value:
ADT7420_DEF __ ## NAME = { \
                        .i2c_id = I2C_ID, \
                        .slvaddr = SLAVE_ADDRESS, \
        }; \
        ADT7420_DEF_PTR NAME = &__ ## NAME
Definition at line 77 of file adt7420.h.
Function Documentation
adt7420_sensor_deinit()
int32_t adt7420_sensor_deinit (ADT7420_DEF_PTR obj)
temperature sensor deinit
Parameters
[in] obj temperature sensor object
Return values
E_OK init success
!E_OK init failed
Definition at line 186 of file adt7420.c.
References E_OK, dev_iic::iic_close, and iic_get_dev().
adt7420_sensor_init()
int32_t adt7420_sensor_init (ADT7420_DEF_PTR obj)
adt7420 init
Parameters
[in] obj temperature sensor object
Return values
E_OK init success
!E_OK init failed
Definition at line 158 of file adt7420.c.
References E_OK, and iic_get_dev().
adt7420_sensor_mode()
int32_t adt7420_sensor_mode (ADT7420_DEF_PTR obj, int32_t mode)
temperature sensor deinit
Parameters
[in] obj temperature sensor object
[in] mode sensor working mode, choose from enum sensor_op_mode
Return values
E_OK always return E_OK
Definition at line 206 of file adt7420.c.
References _adt7420_reg_read(), and ADT7420_REG_CONFIG.
adt7420_sensor_read()
int32_t adt7420_sensor_read (ADT7420_DEF_PTR obj, float * val)
read temperature sensor value in 0.1c unit
Parameters
[in] obj temperature sensor object
[out] val return temperature in degrees Celsius (°C)
Return values
E_OK read success
!E_OK read failed
Definition at line 246 of file adt7420.c.
References E_OK.
adt7420_sensor_resolution()
int32_t adt7420_sensor_resolution (ADT7420_DEF_PTR obj, int32_t resolution)
temperature sensor resolution setting
Parameters
[in] obj temperature sensor object
[in] resolution resolution of temperature sensor
Return values
E_OK always return E_OK
Definition at line 224 of file adt7420.c.
References _adt7420_reg_read(), and ADT7420_REG_CONFIG.