embARC: arc_cache.c File Reference
arc_cache.c File Reference
ARC HAL » Internal Components » Cache
implementation of cache related functions
#include "arc_cache.h"
Data Structures
struct cache_config
Macros
#define DIV_ROUND_UP(x, y) (((x) + (y) - 1) / (y))
Functions
int32_t icache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi instruction cache lines
int32_t icache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in instruction cache
int32_t icache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write icache internal ram
int32_t icache_direct_read (uint32_t cache_addr, uint32_t *tag, uint32_t *data)
directly read icache internal ram
int32_t icache_indirect_read (uint32_t mem_addr, uint32_t *tag, uint32_t *data)
indirectly read icache internal ram
int32_t dcache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi data cache lines
int32_t dcache_flush_mlines (uint32_t start_addr, uint32_t size)
flush multi lines in data cache
int32_t dcache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in data cache
int32_t dcache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write dcache internal ram
int32_t dcache_direct_read (uint32_t cache_addr, uint32_t *tag, uint32_t *data)
directly read dcache internal ram
int32_t dcache_indirect_read (uint32_t mem_addr, uint32_t *tag, uint32_t *data)
indirectly read dcache internal ram
void arc_cache_init (void)
initialize cache
Variables
static struct cache_config
icache_config dcache_config
Detailed Description
implementation of cache related functions
Definition in file arc_cache.c.
Function Documentation
void arc_cache_init (void)
initialize cache
invalidate icache and dcache
Only support ARCv2 cache
Definition at line 390 of file arc_cache.c.
References AUX_BCR_D_CACHE, AUX_BCR_I_CACHE, DC_CTRL_DISABLE_FLUSH_LOCKED, DC_CTRL_INDIRECT_ACCESS, DC_CTRL_INVALID_FLUSH, dcache_enable(), dcache_invalidate(), IC_CTRL_IC_ENABLE, icache_enable(), and icache_invalidate().
int32_t dcache_direct_read (uint32_t cache_addr, uint32_t * tag, uint32_t * data)
directly read dcache internal ram
Parameters
[in] cache_addr,dcache internal address(way+index+offset)
[out] tag cache tag to read
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 346 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_DATA, AUX_DC_RAM_ADDR, AUX_DC_TAG, DC_CTRL_INDIRECT_ACCESS, and dcache_available().
int32_t dcache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write dcache internal ram
Parameters
[in] cache_addr,dcache internal address(way+index+offset)
[in] tag cache tag to write
[in] data cache data to write
Returns
0, succeeded, -1, failed
Definition at line 324 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_DATA, AUX_DC_RAM_ADDR, AUX_DC_TAG, DC_CTRL_INDIRECT_ACCESS, and dcache_available().
int32_t dcache_flush_mlines (uint32_t start_addr, uint32_t size)
flush multi lines in data cache
Parameters
[in] start_addr start address
[in] size the bytes to be flushed
Returns
0, succeeded, -1, failed
Definition at line 245 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_FLDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_FLUSH_STATUS, and dcache_available().
Referenced by __attribute__().
int32_t dcache_indirect_read (uint32_t mem_addr, uint32_t * tag, uint32_t * data)
indirectly read dcache internal ram
Parameters
[in] mem_addr,memory address(tag+index+offset)
[out] tag cache tag to read
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 368 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_DATA, AUX_DC_RAM_ADDR, AUX_DC_TAG, DC_CTRL_INDIRECT_ACCESS, DC_CTRL_OP_SUCCEEDED, and dcache_available().
int32_t dcache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi data cache lines
Parameters
[in] start_addr start address in data cache
[in] size the bytes to be invalidated
Returns
0, succeeded, -1, failed
Definition at line 206 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_IVDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_FLUSH_STATUS, and dcache_available().
Referenced by __attribute__().
int32_t dcache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in data cache
Parameters
[in] start_addr start address in data cache
[in] size the bytes to be locked
Returns
0, succeeded, -1, failed
Definition at line 283 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_LDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_OP_SUCCEEDED, and dcache_available().
Referenced by __attribute__().
int32_t icache_direct_read (uint32_t cache_addr, uint32_t * tag, uint32_t * data)
directly read icache internal ram
Parameters
[in] cache_addr,icache internal address(way+index+offset)
[out] tag cache tag to read (tag+index+lock bit+valid bit)
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 160 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_DATA, AUX_IC_RAM_ADDR, AUX_IC_TAG, IC_CTRL_INDIRECT_ACCESS, and icache_available().
int32_t icache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write icache internal ram
Parameters
[in] cache_addr,icache internal address(way+index+offset)
[in] tag cache tag to write (tag+lock bit+valid bit)
[in] data cache data to write
Returns
0, succeeded, -1, failed
Definition at line 138 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_DATA, AUX_IC_RAM_ADDR, AUX_IC_TAG, IC_CTRL_INDIRECT_ACCESS, and icache_available().
int32_t icache_indirect_read (uint32_t mem_addr, uint32_t * tag, uint32_t * data)
indirectly read icache internal ram
Parameters
[in] mem_addr,memory address
[out] tag cache tag to read
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 182 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_DATA, AUX_IC_RAM_ADDR, AUX_IC_TAG, IC_CTRL_INDIRECT_ACCESS, IC_CTRL_OP_SUCCEEDED, and icache_available().
int32_t icache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi instruction cache lines
Parameters
[in] start_addr start address in instruction cache
[in] size the bytes to be invalidated
Returns
0, succeeded, -1, failed
Definition at line 62 of file arc_cache.c.
References AUX_IC_IVIL, cpu_lock_save(), cpu_unlock_restore(), and icache_available().
int32_t icache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in instruction cache
Parameters
[in] start_addr start address in instruction cache
[in] size the bytes to be locked
Returns
0, succeeded, -1, failed (cache already locked or other reasons)
Definition at line 98 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_LIL, cpu_lock_save(), cpu_unlock_restore(), IC_CTRL_OP_SUCCEEDED, and icache_available().