embARC: arc_cache.h File Reference
arc_cache.h File Reference
ARC HAL » Internal Components » Cache
header file of cache module
#include "embARC_toolchain.h"
#include "arc.h"
#include "arc_builtin.h"
#include "arc_exception.h"
Macros
instruction cache control register related definition
#define IC_CTRL_IC_ENABLE 0x0
#define IC_CTRL_IC_DISABLE 0x1
#define IC_CTRL_DIRECT_ACCESS 0x0
#define IC_CTRL_INDIRECT_ACCESS 0x20
#define IC_CTRL_OP_SUCCEEDED 0x8
data cache control register related definition
#define IC_CTRL_I
#define DC_CTRL_DC_ENABLE 0x0
#define DC_CTRL_DC_DISABLE 0x1
#define DC_CTRL_INVALID_ONLY 0x0
#define DC_CTRL_INVALID_FLUSH 0x40
#define DC_CTRL_ENABLE_FLUSH_LOCKED 0x80
#define DC_CTRL_DISABLE_FLUSH_LOCKED 0x0
#define DC_CTRL_FLUSH_STATUS 0x100
#define DC_CTRL_DIRECT_ACCESS 0x0
#define DC_CTRL_INDIRECT_ACCESS 0x20
#define DC_CTRL_OP_SUCCEEDED 0x4
Functions
instruction cache related inline function
Inline uint8_t icache_available (void)
check whether instruction cache is available, 0 for not available, >0 for available
Inline void icache_enable (uint32_t icache_en_mask)
enable instruction cache
Inline void icache_disable (void)
disable instruction cache
Inline void icache_invalidate (void)
invalidate the entire instruction cache
Inline void icache_invalidate_line (uint32_t address)
invalidate specific cache line
Inline int32_t icache_lock_line (uint32_t address)
lock specific cache line
Inline void icache_access_mode (uint32_t mode)
set icache access mode
data cache related inline functions
Inline uint8_t dcache_available (void)
check whether data cache is available, 0 for not available, >0 for available
Inline void dcache_invalidate (void)
invalidate the entire data cache
Inline void dcache_invalidate_line (uint32_t address)
invalidate the specific cache line
Inline void dcache_enable (uint32_t dcache_en_mask)
enable data cache
Inline void dcache_disable (void)
disable data cache
Inline void dcache_flush (void)
flush data cache
Inline void dcache_flush_line (uint32_t address)
flush the specific data cache line
Inline int dcache_lock_line (uint32_t address)
lock the specific data cache line
Inline void dcache_access_mode (uint32_t mode)
set dcache access mode
declarations of cache related functions
int32_t icache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi instruction cache lines
int32_t icache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in instruction cache
int32_t icache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write icache internal ram
int32_t icache_direct_read (uint32_t cache_addr, uint32_t *tag, uint32_t *data)
directly read icache internal ram
int32_t icache_indirect_read (uint32_t mem_addr, uint32_t *tag, uint32_t *data)
indirectly read icache internal ram
int32_t dcache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi data cache lines
int32_t dcache_flush_mlines (uint32_t start_addr, uint32_t size)
flush multi lines in data cache
int32_t dcache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in data cache
int32_t dcache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write dcache internal ram
int32_t dcache_direct_read (uint32_t cache_addr, uint32_t *tag, uint32_t *data)
directly read dcache internal ram
int32_t dcache_indirect_read (uint32_t mem_addr, uint32_t *tag, uint32_t *data)
indirectly read dcache internal ram
void arc_cache_init (void)
initialize cache
Detailed Description
header file of cache module
Definition in file arc_cache.h.
Macro Definition Documentation
#define DC_CTRL_DC_DISABLE 0x1
disable data cache
Definition at line 64 of file arc_cache.h.
Referenced by dcache_disable().
#define DC_CTRL_DC_ENABLE 0x0
enable data cache
Definition at line 63 of file arc_cache.h.
#define DC_CTRL_DIRECT_ACCESS 0x0
direct access mode
Definition at line 70 of file arc_cache.h.
#define DC_CTRL_DISABLE_FLUSH_LOCKED 0x0
the locked data cache cannot be flushed
Definition at line 68 of file arc_cache.h.
Referenced by arc_cache_init().
#define DC_CTRL_ENABLE_FLUSH_LOCKED 0x80
the locked data cache can be flushed
Definition at line 67 of file arc_cache.h.
#define DC_CTRL_FLUSH_STATUS 0x100
flush status
Definition at line 69 of file arc_cache.h.
Referenced by dcache_flush(), dcache_flush_line(), dcache_flush_mlines(), dcache_invalidate(), and dcache_invalidate_mlines().
#define DC_CTRL_INDIRECT_ACCESS 0x20
indirect access mode
Definition at line 71 of file arc_cache.h.
Referenced by arc_cache_init(), dcache_access_mode(), dcache_direct_read(), dcache_direct_write(), and dcache_indirect_read().
#define DC_CTRL_INVALID_FLUSH 0x40
invalid and flush data cache
Definition at line 66 of file arc_cache.h.
Referenced by arc_cache_init().
#define DC_CTRL_INVALID_ONLY 0x0
invalid data cache only
Definition at line 65 of file arc_cache.h.
#define DC_CTRL_OP_SUCCEEDED 0x4
data cache operation succeeded
Definition at line 72 of file arc_cache.h.
Referenced by dcache_indirect_read(), dcache_lock_line(), and dcache_lock_mlines().
#define IC_CTRL_DIRECT_ACCESS 0x0
direct access mode
Definition at line 52 of file arc_cache.h.
#define IC_CTRL_IC_DISABLE 0x1
disable instruction cache
Definition at line 51 of file arc_cache.h.
Referenced by icache_disable().
#define IC_CTRL_IC_ENABLE 0x0
enable instruction cache
Definition at line 50 of file arc_cache.h.
Referenced by arc_cache_init().
#define IC_CTRL_INDIRECT_ACCESS 0x20
indirect access mode
Definition at line 53 of file arc_cache.h.
Referenced by icache_access_mode(), icache_direct_read(), icache_direct_write(), and icache_indirect_read().
#define IC_CTRL_OP_SUCCEEDED 0x8
instruction cache operation succeeded
Definition at line 54 of file arc_cache.h.
Referenced by icache_indirect_read(), icache_lock_line(), and icache_lock_mlines().
Function Documentation
void arc_cache_init (void)
initialize cache
invalidate icache and dcache
Only support ARCv2 cache
Definition at line 387 of file arc_cache.c.
References AUX_BCR_D_CACHE, AUX_BCR_I_CACHE, DC_CTRL_DISABLE_FLUSH_LOCKED, DC_CTRL_INDIRECT_ACCESS, DC_CTRL_INVALID_FLUSH, dcache_enable(), dcache_invalidate(), IC_CTRL_IC_ENABLE, icache_enable(), and icache_invalidate().
Inline void dcache_access_mode (uint32_t mode)
set dcache access mode
Parameters
[in] mode,access mode, 1: indirect access 0:direct access
Definition at line 280 of file arc_cache.h.
References AUX_DC_CTRL, DC_CTRL_INDIRECT_ACCESS, and dcache_available().
int32_t dcache_direct_read (uint32_t cache_addr, uint32_t * tag, uint32_t * data)
directly read dcache internal ram
Parameters
[in] cache_addr,dcache internal address(way+index+offset)
[out] tag cache tag to read
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 343 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_DATA, AUX_DC_RAM_ADDR, AUX_DC_TAG, DC_CTRL_INDIRECT_ACCESS, and dcache_available().
int32_t dcache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write dcache internal ram
Parameters
[in] cache_addr,dcache internal address(way+index+offset)
[in] tag cache tag to write
[in] data cache data to write
Returns
0, succeeded, -1, failed
Definition at line 321 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_DATA, AUX_DC_RAM_ADDR, AUX_DC_TAG, DC_CTRL_INDIRECT_ACCESS, and dcache_available().
Inline void dcache_enable (uint32_t dcache_en_mask)
enable data cache
Parameters
[in] dcache_en_mask operation mask
Definition at line 214 of file arc_cache.h.
References AUX_DC_CTRL, and dcache_available().
Referenced by arc_cache_init().
Inline void dcache_flush_line (uint32_t address)
flush the specific data cache line
Parameters
[in] address memory address
Definition at line 248 of file arc_cache.h.
References AUX_DC_CTRL, AUX_DC_FLDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_FLUSH_STATUS, and dcache_available().
Referenced by __attribute__(), and exc_entry_install().
int32_t dcache_flush_mlines (uint32_t start_addr, uint32_t size)
flush multi lines in data cache
Parameters
[in] start_addr start address
[in] size the bytes to be flushed
Returns
0, succeeded, -1, failed
Definition at line 242 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_FLDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_FLUSH_STATUS, and dcache_available().
Referenced by __attribute__().
int32_t dcache_indirect_read (uint32_t mem_addr, uint32_t * tag, uint32_t * data)
indirectly read dcache internal ram
Parameters
[in] mem_addr,memory address(tag+index+offset)
[out] tag cache tag to read
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 365 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_DATA, AUX_DC_RAM_ADDR, AUX_DC_TAG, DC_CTRL_INDIRECT_ACCESS, DC_CTRL_OP_SUCCEEDED, and dcache_available().
Inline void dcache_invalidate_line (uint32_t address)
invalidate the specific cache line
Parameters
[in] address memory address
Definition at line 201 of file arc_cache.h.
References AUX_DC_IVDL, and dcache_available().
Referenced by __attribute__().
int32_t dcache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi data cache lines
Parameters
[in] start_addr start address in data cache
[in] size the bytes to be invalidated
Returns
0, succeeded, -1, failed
Definition at line 203 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_IVDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_FLUSH_STATUS, and dcache_available().
Referenced by __attribute__().
Inline int dcache_lock_line (uint32_t address)
lock the specific data cache line
Parameters
[in] address memory address
Returns
0, succeeded, -1, failed
Definition at line 265 of file arc_cache.h.
References AUX_DC_CTRL, AUX_DC_LDL, DC_CTRL_OP_SUCCEEDED, and dcache_available().
Referenced by __attribute__().
int32_t dcache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in data cache
Parameters
[in] start_addr start address in data cache
[in] size the bytes to be locked
Returns
0, succeeded, -1, failed
Definition at line 280 of file arc_cache.c.
References AUX_DC_CTRL, AUX_DC_LDL, cpu_lock_save(), cpu_unlock_restore(), DC_CTRL_OP_SUCCEEDED, and dcache_available().
Referenced by __attribute__().
Inline void icache_access_mode (uint32_t mode)
set icache access mode
Parameters
[in] mode,access mode, 1: indirect access 0:direct access
Definition at line 155 of file arc_cache.h.
References AUX_IC_CTRL, IC_CTRL_INDIRECT_ACCESS, and icache_available().
int32_t icache_direct_read (uint32_t cache_addr, uint32_t * tag, uint32_t * data)
directly read icache internal ram
Parameters
[in] cache_addr,icache internal address(way+index+offset)
[out] tag cache tag to read (tag+index+lock bit+valid bit)
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 157 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_DATA, AUX_IC_RAM_ADDR, AUX_IC_TAG, IC_CTRL_INDIRECT_ACCESS, and icache_available().
int32_t icache_direct_write (uint32_t cache_addr, uint32_t tag, uint32_t data)
directly write icache internal ram
Parameters
[in] cache_addr,icache internal address(way+index+offset)
[in] tag cache tag to write (tag+lock bit+valid bit)
[in] data cache data to write
Returns
0, succeeded, -1, failed
Definition at line 135 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_DATA, AUX_IC_RAM_ADDR, AUX_IC_TAG, IC_CTRL_INDIRECT_ACCESS, and icache_available().
Inline void icache_enable (uint32_t icache_en_mask)
enable instruction cache
Parameters
[in] icache_en_mask operation mask
Definition at line 93 of file arc_cache.h.
References AUX_IC_CTRL, and icache_available().
Referenced by arc_cache_init().
int32_t icache_indirect_read (uint32_t mem_addr, uint32_t * tag, uint32_t * data)
indirectly read icache internal ram
Parameters
[in] mem_addr,memory address
[out] tag cache tag to read
[out] data cache data to read
Returns
0, succeeded, -1, failed
Definition at line 179 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_DATA, AUX_IC_RAM_ADDR, AUX_IC_TAG, IC_CTRL_INDIRECT_ACCESS, IC_CTRL_OP_SUCCEEDED, and icache_available().
Inline void icache_invalidate_line (uint32_t address)
invalidate specific cache line
Parameters
[in] address memory address
Definition at line 125 of file arc_cache.h.
References AUX_IC_IVIL, and icache_available().
Referenced by exc_entry_install().
int32_t icache_invalidate_mlines (uint32_t start_addr, uint32_t size)
invalidate multi instruction cache lines
Parameters
[in] start_addr start address in instruction cache
[in] size the bytes to be invalidated
Returns
0, succeeded, -1, failed
Definition at line 59 of file arc_cache.c.
References AUX_IC_IVIL, cpu_lock_save(), cpu_unlock_restore(), and icache_available().
Inline int32_t icache_lock_line (uint32_t address)
lock specific cache line
Parameters
[in] address memory address
Returns
0, succeeded, -1, failed
Definition at line 140 of file arc_cache.h.
References AUX_IC_CTRL, AUX_IC_LIL, IC_CTRL_OP_SUCCEEDED, and icache_available().
int32_t icache_lock_mlines (uint32_t start_addr, uint32_t size)
lock multi lines in instruction cache
Parameters
[in] start_addr start address in instruction cache
[in] size the bytes to be locked
Returns
0, succeeded, -1, failed (cache already locked or other reasons)
Definition at line 95 of file arc_cache.c.
References AUX_IC_CTRL, AUX_IC_LIL, cpu_lock_save(), cpu_unlock_restore(), IC_CTRL_OP_SUCCEEDED, and icache_available().