embARC: arc_exception.c File Reference
arc_exception.c File Reference
ARC HAL » Exception and Interrupt » CPU ExceptionARC HAL » Exception and Interrupt » | Interrupt
C Implementation of exception and interrupt management.
#include "arc_exception.h"
#include "arc_cache.h"
#include "embARC_debug.h"
Data Structures
struct aux_irq_ctrl_field
union aux_irq_ctrl_t
Typedefs
typedef struct aux_irq_ctrl_field aux_irq_ctrl_field_t
Functions
static void exc_handler_default (void *p_excinf)
default cpu exception handler
static void int_handler_default (void *p_excinf)
default interrupt handler
__attribute__ ((aligned(1024), section(".vector")))
void exc_int_init (void)
intialize the exception and interrupt handling
int32_t exc_entry_install (const uint32_t excno, EXC_ENTRY entry)
install a CPU exception entry
EXC_ENTRY exc_entry_get (const uint32_t excno)
get the installed CPU exception entry
int32_t exc_handler_install (const uint32_t excno, EXC_HANDLER handler)
install an exception handler
EXC_HANDLER exc_handler_get (const uint32_t excno)
get the installed exception handler
int32_t int_disable (const uint32_t intno)
disable the specific interrupt
int32_t int_enable (const uint32_t intno)
enable the specific int
int32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
int32_t int_ipm_get (void)
get the interrupt priority mask
int32_t int_ipm_set (int32_t intpri)
set the interrupt priority mask
int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
int32_t int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
int32_t int_secure_set (const uint32_t intno, uint32_t secure)
set interrupt secure or not secure This function is valid in secureshield v2
int32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
int32_t int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
int32_t int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
void cpu_lock (void)
lock cpu, disable interrupts
void cpu_unlock (void)
unlock cpu, enable interrupts to happen
uint32_t cpu_lock_save (void)
lock cpu and return status
void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
int32_t int_handler_install (const uint32_t intno, INT_HANDLER handler)
install an interrupt handler
INT_HANDLER int_handler_get (const uint32_t intno)
get the installed an interrupt handler
Variables
EXC_HANDLER exc_int_handler_table [NUM_EXC_ALL]
the cpu exception and interrupt exception handler table called in exc_entry_default and exc_entry_int
uint32_t exc_nest_count
the counter for exc/int processing, =0 no int/exc >1 in int/exc processing
Detailed Description
C Implementation of exception and interrupt management.
Definition in file arc_exception.c.
Function Documentation
uint32_t cpu_lock_save (void)
lock cpu and return status
Returns
cpu status
Definition at line 475 of file arc_exception.c.
Referenced by dcache_flush(), dcache_flush_line(), dcache_flush_mlines(), dcache_invalidate(), dcache_invalidate_mlines(), dcache_lock_mlines(), exc_entry_install(), icache_invalidate_mlines(), icache_lock_mlines(), int_pri_set(), rw009_cmd(), and spi_send_cmd().
void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Parameters
[in] status cpu status saved by cpu_lock_save
Definition at line 485 of file arc_exception.c.
Referenced by dcache_flush(), dcache_flush_line(), dcache_flush_mlines(), dcache_invalidate(), dcache_invalidate_mlines(), dcache_lock_mlines(), exc_entry_install(), icache_invalidate_mlines(), icache_lock_mlines(), int_pri_set(), rw009_cmd(), and spi_send_cmd().
int32_t int_disable (const uint32_t intno)
disable the specific interrupt
Parameters
[in] intno interrupt number
Definition at line 282 of file arc_exception.c.
Referenced by axs_timer_init(), dw_gpio_close(), dw_gpio_control(), dw_gpio_open(), dw_iic_dis_cbr(), dw_iic_disable_interrupt(), dw_spi_dis_cbr(), dw_spi_disable_interrupt(), dw_uart_dis_cbr(), dw_uart_disable_interrupt(), emsk_timer_init(), main(), and nsim_timer_init().
int32_t int_enable (const uint32_t intno)
enable the specific int
Parameters
[in] intno interrupt number
Definition at line 297 of file arc_exception.c.
Referenced by axs_timer_init(), dw_gpio_control(), dw_iic_ena_cbr(), dw_iic_enable_interrupt(), dw_spi_ena_cbr(), dw_spi_enable_interrupt(), dw_uart_ena_cbr(), dw_uart_enable_interrupt(), emsk_timer_init(), main(), and nsim_timer_init().
int32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
Parameters
[in] intno interrupt number
Returns
0 disabled, 1 enabled, < 0 error
Definition at line 313 of file arc_exception.c.
int32_t int_ipm_get (void)
get the interrupt priority mask
Returns
interrupt priority mask, negative num
Definition at line 328 of file arc_exception.c.
int32_t int_ipm_set (int32_t intpri)
set the interrupt priority mask
Parameters
[in] intpri interrupt priority
Definition at line 339 of file arc_exception.c.
int32_t int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Parameters
[in] intno interrupt number
[in] level,0-level trigger, 1-pulse triggered
Returns
0 ok, -1 error
Definition at line 444 of file arc_exception.c.
int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
Parameters
[in] intno interrupt number
Returns
<0 interrupt priority, 0 error
Definition at line 357 of file arc_exception.c.
int32_t int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
Parameters
[in] intno interrupt number
[in] intpri interrupt priority
Returns
<0 error, 0 ok
Definition at line 374 of file arc_exception.c.
Referenced by main().
int32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
Parameters
[in] intno interrupt number
Returns
1 pending, 0 no pending, -1 error
Definition at line 413 of file arc_exception.c.
int32_t int_secure_set (const uint32_t intno, uint32_t secure)
set interrupt secure or not secure This function is valid in secureshield v2
Parameters
[in] intno interrupt number
[in] secure,0 for normal, >0 for secure
Returns
<0 error, 0 ok
Definition at line 395 of file arc_exception.c.
References arc_int_secure_set(), NUM_EXC_ALL, and NUM_EXC_CPU.
int32_t int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Parameters
[in] intno interrupt number
Returns
0 ok, -1 error
Definition at line 428 of file arc_exception.c.