embARC: dw_uart.c File Reference
dw_uart.c File Reference
Device HAL » Device HAL Implementation » Designware Device Driver » Designware UART Driver
DesignWare UART driver implementation based on device hal layer definition (dev_uart.h)
#include <string.h>
#include "embARC_toolchain.h"
#include "embARC_error.h"
#include "arc_exception.h"
#include "dw_uart_hal.h"
#include "dw_uart.h"
Macros
DesignWare UART Driver Macros
DesignWare UART driver macros used in uart driver
#define DW_UART_CHECK_EXP(EXPR, ERROR_CODE) CHECK_EXP(EXPR, ercd, ERROR_CODE, error_exit)
check expressions used in DesignWare UART driver implementation
#define VALID_CHK_UART_INFO_OBJECT(uartinfo_obj_ptr)
valid check of uart info object
#define DW_UART_BAUD2DIV(perifreq, baud) ((perifreq) / ((baud)*16))
convert DesignWare baudrate to divisor
DesignWare UART Interrupt Callback Routine Select Marcos
DesignWare UART interrupt callback routines select macros definitions
#define DW_UART_RDY_SND (1U)
#define DW_UART_RDY_RCV (2U)
Functions
Inline int32_t dw_uart_putready (DW_UART_REG *uart_reg_ptr)
test whether uart is ready to send, 1 ready, 0 not ready
Inline int32_t dw_uart_getready (DW_UART_REG *uart_reg_ptr)
test whether uart is ready to receive, 1 ready, 0 not ready
Inline void dw_uart_putchar (DW_UART_REG *uart_reg_ptr, char chr)
write char to uart send fifo
Inline int32_t dw_uart_getchar (DW_UART_REG *uart_reg_ptr)
read data from uart receive fifo, return data received
Inline int32_t dw_uart_snd_chr (DW_UART_REG *uart_reg_ptr, char chr)
send char by uart when available, mostly used in interrupt method, non-blocked function
Inline int32_t dw_uart_rcv_chr (DW_UART_REG *uart_reg_ptr)
receive one char from uart, mostly used in interrupt routine, non-blocked function
Inline void dw_uart_psnd_chr (DW_UART_REG *uart_reg_ptr, char chr)
send char by uart in poll method, blocked function
Inline int32_t dw_uart_prcv_chr (DW_UART_REG *uart_reg_ptr)
receive one char from uart in poll method, blocked function
Inline uint32_t dw_uart_get_txfifo_len (DW_UART_REG *uart_reg_ptr)
Get TX FIFO Length.
Inline uint32_t dw_uart_get_rxfifo_len (DW_UART_REG *uart_reg_ptr)
Get RX FIFO Length.
static int32_t dw_uart_set_dps (DW_UART_REG *uart_reg_ptr, UART_DPS_FORMAT *dps)
set designware uart DPS value
static void dw_uart_set_baud (DW_UART_REG *uart_reg_ptr, uint32_t baud_divisor)
set designware uart baudrate
Inline void dw_uart_software_reset (DW_UART_REG *uart_reg_ptr)
Do uart software reset.
static void dw_uart_set_hwfc (DW_UART_REG *uart_reg_ptr, UART_HW_FLOW_CONTROL hwfc)
set designware uart baudrate
Inline void dw_uart_set_break (DW_UART_REG *uart_reg_ptr)
Inline void dw_uart_clr_break (DW_UART_REG *uart_reg_ptr)
static void dw_uart_init (DW_UART_REG *uart_reg_ptr, uint32_t baud_divisor, UART_DPS_FORMAT *dps, UART_HW_FLOW_CONTROL hwfc)
init designware uart with selected baud
static void dw_uart_flush_output (DEV_UART_INFO *uart_info_ptr)
set designware uart baudrate
static void dw_uart_dis_cbr (DEV_UART_INFO *uart_info_ptr, uint32_t cbrtn)
disable designware uart send or receive interrupt
static void dw_uart_ena_cbr (DEV_UART_INFO *uart_info_ptr, uint32_t cbrtn)
enable DesignWare UART send or receive interrupt
static void dw_uart_enable_interrupt (DEV_UART_INFO *uart_info_ptr)
enable designware uart interrupt
static void dw_uart_disable_interrupt (DEV_UART_INFO *uart_info_ptr)
disable designware uart interrupt
static void dw_uart_enable_device (DEV_UART_INFO *uart_info_ptr)
enable designware uart
static void dw_uart_disable_device (DEV_UART_INFO *uart_info_ptr)
disable designware uart
static void dw_uart_abort_tx (DEV_UART *uart_obj)
abort current interrupt transmit transfer
static void dw_uart_abort_rx (DEV_UART *uart_obj)
abort current interrupt receive transfer
static int32_t dw_uart_get_txavail (DW_UART_CTRL *uart_ctrl_ptr)
Get available transmit fifo count.
static int32_t dw_uart_get_rxavail (DW_UART_CTRL *uart_ctrl_ptr)
Get available receive fifo count.
int32_t dw_uart_open (DEV_UART *uart_obj, uint32_t baud)
open a designware uart device
int32_t dw_uart_close (DEV_UART *uart_obj)
close a DesignWare UART device
int32_t dw_uart_control (DEV_UART *uart_obj, uint32_t ctrl_cmd, void *param)
control uart by ctrl command
int32_t dw_uart_write (DEV_UART *uart_obj, const void *data, uint32_t len)
send data through DesignWare UART
int32_t dw_uart_read (DEV_UART *uart_obj, void *data, uint32_t len)
read data through DesignWare UART
void dw_uart_isr (DEV_UART *uart_obj, void *ptr)
DesignWare UART interrupt processing routine.
Variables
const uint8_t dw_uart_databits []
const uint8_t dw_uart_parity []
const uint8_t dw_uart_stopbits []
Detailed Description
DesignWare UART driver implementation based on device hal layer definition (dev_uart.h)
Definition in file dw_uart.c.
Macro Definition Documentation
#define DW_UART_RDY_RCV (2U)
ready to receive callback
Definition at line 81 of file dw_uart.c.
Referenced by dw_uart_abort_rx(), dw_uart_control(), dw_uart_dis_cbr(), dw_uart_disable_interrupt(), dw_uart_ena_cbr(), and dw_uart_isr().
#define DW_UART_RDY_SND (1U)
ready to send callback
Definition at line 80 of file dw_uart.c.
Referenced by dw_uart_abort_tx(), dw_uart_control(), dw_uart_dis_cbr(), dw_uart_disable_interrupt(), dw_uart_ena_cbr(), and dw_uart_isr().
#define VALID_CHK_UART_INFO_OBJECT (uartinfo_obj_ptr)
Value:
{                               \
            DW_UART_CHECK_EXP((uartinfo_obj_ptr)!=NULL, E_OBJ);                  \
            DW_UART_CHECK_EXP(((uartinfo_obj_ptr)->uart_ctrl)!=NULL, E_OBJ);     \
                }
valid check of uart info object
Definition at line 66 of file dw_uart.c.
Referenced by dw_uart_close(), dw_uart_control(), dw_uart_isr(), dw_uart_open(), dw_uart_read(), and dw_uart_write().
Function Documentation
int32_t dw_uart_close (DEV_UART * uart_obj)
close a DesignWare UART device
Parameters
[in] uart_obj uart object structure pointer
Return values
E_OK Open successfully without any issues
E_OPNED Device is still opened, the device opn_cnt decreased by 1
E_OBJ Device object is not valid
Definition at line 594 of file dw_uart.c.
References dw_uart_abort_rx(), dw_uart_abort_tx(), DW_UART_CHECK_EXP, dw_uart_disable_device(), dw_uart_disable_interrupt(), dw_uart_flush_output(), E_OK, E_OPNED, dev_uart_info::extra, dev_uart_info::opn_cnt, dev_uart_info::rx_buf, dev_uart_info::status, dev_uart_info::tx_buf, dev_uart_info::uart_cbs, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_close(), dw_uart_1_close(), and dw_uart_2_close().
int32_t dw_uart_control (DEV_UART * uart_obj, uint32_t ctrl_cmd, void * param)
control uart by ctrl command
Parameters
[in] uart_obj uart object structure pointer
[in] ctrl_cmd control command code to do specific uart work
[in,out] param parameters used to control uart or return something
Return values
E_OK Control device successfully
E_CLSED Device is not opened
E_DIS Device is disabled
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Control device failed, due to hardware issues
E_CTX Control device failed, due to different reasons like in transfer state
E_NOSPT Control command is not supported or not valid
Definition at line 638 of file dw_uart.c.
References dev_uart_info::baudrate, dev_buffer::buf, CHECK_ALIGN_4BYTES, DEV_ENABLED, dev_uart_info::dps_format, dw_uart_ctrl::dw_apb_bus_freq, dw_uart_abort_rx(), dw_uart_abort_tx(), DW_UART_BAUD2DIV, DW_UART_CHECK_EXP, dw_uart_dis_cbr(), dw_uart_disable_device(), dw_uart_ena_cbr(), dw_uart_enable_device(), dw_uart_flush_output(), dw_uart_get_rxavail(), dw_uart_get_txavail(), DW_UART_RDY_RCV, DW_UART_RDY_SND, dw_uart_ctrl::dw_uart_regbase, dw_uart_set_baud(), dw_uart_set_dps(), dw_uart_set_hwfc(), E_CLSED, E_NOSPT, E_OK, E_PAR, E_SYS, dev_uart_cbs::err_cb, dev_uart_info::hwfc, dev_buffer::len, dev_buffer::ofs, dev_uart_info::opn_cnt, dev_uart_info::rx_buf, dev_uart_cbs::rx_cb, dev_uart_info::status, dev_uart_info::tx_buf, dev_uart_cbs::tx_cb, dev_uart_info::uart_cbs, UART_CMD_ABORT_RX, UART_CMD_ABORT_TX, UART_CMD_BREAK_CLR, UART_CMD_BREAK_SET, UART_CMD_DIS_DEV, UART_CMD_ENA_DEV, UART_CMD_FLUSH_OUTPUT, UART_CMD_GET_RXAVAIL, UART_CMD_GET_STATUS, UART_CMD_GET_TXAVAIL, UART_CMD_SET_BAUD, UART_CMD_SET_DPS_FORMAT, UART_CMD_SET_ERRCB, UART_CMD_SET_HWFC, UART_CMD_SET_RXCB, UART_CMD_SET_RXINT, UART_CMD_SET_RXINT_BUF, UART_CMD_SET_TXCB, UART_CMD_SET_TXINT, UART_CMD_SET_TXINT_BUF, dev_uart_info::uart_ctrl, UART_FC_BOTH, UART_FC_NONE, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_control(), dw_uart_1_control(), and dw_uart_2_control().
void dw_uart_isr (DEV_UART * uart_obj, void * ptr)
DesignWare UART interrupt processing routine.
Parameters
[in] uart_obj uart object structure pointer
[in] ptr extra information
Definition at line 870 of file dw_uart.c.
References dev_buffer::buf, dw_uart_dis_cbr(), dw_uart_getchar(), dw_uart_getready(), dw_uart_putchar(), dw_uart_putready(), DW_UART_RDY_RCV, DW_UART_RDY_SND, dw_uart_ctrl::dw_uart_regbase, E_OK, dev_uart_cbs::err_cb, dev_buffer::len, dev_buffer::ofs, dev_uart_info::rx_buf, dev_uart_cbs::rx_cb, dev_uart_info::tx_buf, dev_uart_cbs::tx_cb, dev_uart_info::uart_cbs, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_isr(), dw_uart_1_isr(), and dw_uart_2_isr().
int32_t dw_uart_open (DEV_UART * uart_obj, uint32_t baud)
open a designware uart device
Parameters
[in] uart_obj uart object structure pointer
[in] baud baudrate to initialized
Return values
E_OK Open successfully without any issues
E_OPNED If device was opened before with different baudrate, then return E_OPNED
E_OBJ Device object is not valid
E_PAR Parameter is not valid
E_NOSPT Open settings are not supported
Definition at line 534 of file dw_uart.c.
References dev_uart_info::baudrate, DEV_ENABLED, dev_uart_info::dps_format, dps_format_default, dw_uart_ctrl::dw_apb_bus_freq, DW_UART_BAUD2DIV, DW_UART_CHECK_EXP, dw_uart_disable_interrupt(), dw_uart_get_rxfifo_len(), dw_uart_get_txfifo_len(), dw_uart_init(), dw_uart_ctrl::dw_uart_int_handler, dw_uart_ctrl::dw_uart_regbase, E_OK, E_OPNED, E_PAR, dev_uart_info::extra, dev_uart_info::hwfc, hwfc_default, int_handler_install(), dw_uart_ctrl::intno, dev_uart_info::opn_cnt, dev_uart_info::rx_buf, dw_uart_ctrl::rx_fifo_len, dev_uart_info::status, dev_uart_info::tx_buf, dw_uart_ctrl::tx_fifo_len, dev_uart_info::uart_cbs, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_open(), dw_uart_1_open(), and dw_uart_2_open().
int32_t dw_uart_read (DEV_UART * uart_obj, void * data, uint32_t len)
read data through DesignWare UART
Parameters
[in] uart_obj uart object structure pointer
[out] data data that need to read (data must be char type)
[in] len data count need to read
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Can't receive data from hardware due to hardware issues, such as device is disabled
Definition at line 837 of file dw_uart.c.
References DEV_ENABLED, DW_UART_CHECK_EXP, dw_uart_prcv_chr(), dw_uart_ctrl::dw_uart_regbase, E_CLSED, E_OK, E_PAR, E_SYS, dev_uart_info::opn_cnt, dev_uart_info::status, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_read(), dw_uart_1_read(), and dw_uart_2_read().
int32_t dw_uart_write (DEV_UART * uart_obj, const void * data, uint32_t len)
send data through DesignWare UART
Parameters
[in] uart_obj uart object structure pointer
[in] data data that need to send (data must be char type)
[in] len data length need to send
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Can't write data to hardware due to hardware issues
Definition at line 799 of file dw_uart.c.
References DEV_ENABLED, DW_UART_CHECK_EXP, dw_uart_psnd_chr(), dw_uart_ctrl::dw_uart_regbase, E_CLSED, E_OK, E_PAR, E_SYS, dev_uart_info::opn_cnt, dev_uart_info::status, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_write(), dw_uart_1_write(), and dw_uart_2_write().