embARC: dw_uart.h File Reference
dw_uart.h File Reference
Device HAL » Device HAL Implementation » Designware Device Driver » Designware UART Driver
DesignWare UART driver header file.
#include "dev_uart.h"
#include "arc_exception.h"
Data Structures
struct dw_uart_reg
DesignWare UART register structure.
struct dw_uart_ctrl
DesignWare UART control structure definition.
Macros
#define DEVICE_USE_DESIGNWARE_UART
if this header file is included, will indicate that this designware uart device is used
#define DW_UART_GINT_DISABLED (0)
#define DW_UART_GINT_ENABLE (1<<0)
#define DW_UART_TXINT_ENABLE (1<<1)
#define DW_UART_RXINT_ENABLE (1<<2)
#define DW_UART_INVALID_INTNO (DEV_INTNO_INVALID)
Typedefs
typedef struct dw_uart_ctrl DW_UART_CTRL
DesignWare UART control structure definition.
typedef struct dw_uart_ctrl * DW_UART_CTRL_PTR
DesignWare UART Register Structure
contains definitions of DesignWare UART register structure.
typedef volatile struct dw_uart_reg DW_UART_REG
DesignWare UART register structure.
typedef volatile struct
dw_uart_reg * DW_UART_REG_PTR
Functions
DesignWare UART Function Declaration
contains declarations of designware uart functions.
This are only used in uart object implementation source file
int32_t dw_uart_open (DEV_UART *uart_obj, uint32_t baud)
open a designware uart device
int32_t dw_uart_close (DEV_UART *uart_obj)
close a DesignWare UART device
int32_t dw_uart_control (DEV_UART *uart_obj, uint32_t ctrl_cmd, void *param)
control uart by ctrl command
int32_t dw_uart_write (DEV_UART *uart_obj, const void *data, uint32_t len)
send data through DesignWare UART
int32_t dw_uart_read (DEV_UART *uart_obj, void *data, uint32_t len)
read data through DesignWare UART
void dw_uart_isr (DEV_UART *uart_obj, void *ptr)
DesignWare UART interrupt processing routine.
Detailed Description
DesignWare UART driver header file.
detailed definitions of designware uart driver
Definition in file dw_uart.h.
Macro Definition Documentation
#define DW_UART_GINT_DISABLED (0)
designware interrupt disabled for control uart irq/fiq
Definition at line 96 of file dw_uart.h.
#define DW_UART_GINT_ENABLE (1<<0)
designware interrupt enabled for control uart irq/fiq
Definition at line 97 of file dw_uart.h.
Referenced by dw_uart_dis_cbr(), dw_uart_disable_interrupt(), dw_uart_ena_cbr(), and dw_uart_enable_interrupt().
#define DW_UART_RXINT_ENABLE (1<<2)
designware interrupt enabled for control transmit process
Definition at line 99 of file dw_uart.h.
Referenced by dw_uart_abort_rx(), dw_uart_dis_cbr(), dw_uart_disable_interrupt(), and dw_uart_ena_cbr().
#define DW_UART_TXINT_ENABLE (1<<1)
designware interrupt enabled for control transmit process
Definition at line 98 of file dw_uart.h.
Referenced by dw_uart_abort_tx(), dw_uart_dis_cbr(), dw_uart_disable_interrupt(), and dw_uart_ena_cbr().
Typedef Documentation
typedef struct dw_uart_ctrl DW_UART_CTRL
DesignWare UART control structure definition.
implement of dev_uart_info::uart_ctrl
typedef volatile struct dw_uart_reg DW_UART_REG
DesignWare UART register structure.
Detailed struct description of DesignWare UART block register information, implementation of dev_uart_info::uart_regs
Function Documentation
int32_t dw_uart_close (DEV_UART * uart_obj)
close a DesignWare UART device
Parameters
[in] uart_obj uart object structure pointer
Return values
E_OK Open successfully without any issues
E_OPNED Device is still opened, the device opn_cnt decreased by 1
E_OBJ Device object is not valid
Definition at line 618 of file dw_uart.c.
References dw_uart_abort_rx(), dw_uart_abort_tx(), DW_UART_CHECK_EXP, dw_uart_disable_device(), dw_uart_disable_interrupt(), dw_uart_flush_output(), E_OK, E_OPNED, dev_uart_info::extra, dev_uart_info::opn_cnt, dev_uart_info::rx_buf, dev_uart_info::status, dev_uart_info::tx_buf, dev_uart_info::uart_cbs, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_close(), dw_uart_1_close(), dw_uart_2_close(), and dw_uart_3_close().
int32_t dw_uart_control (DEV_UART * uart_obj, uint32_t ctrl_cmd, void * param)
control uart by ctrl command
Parameters
[in] uart_obj uart object structure pointer
[in] ctrl_cmd control command code to do specific uart work
[in,out] param parameters used to control uart or return something
Return values
E_OK Control device successfully
E_CLSED Device is not opened
E_DIS Device is disabled
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Control device failed, due to hardware issues
E_CTX Control device failed, due to different reasons like in transfer state
E_NOSPT Control command is not supported or not valid
Definition at line 662 of file dw_uart.c.
References dev_uart_info::baudrate, dev_buffer::buf, CHECK_ALIGN_4BYTES, DEV_ENABLED, dev_uart_info::dps_format, dw_uart_ctrl::dw_apb_bus_freq, dw_uart_abort_rx(), dw_uart_abort_tx(), DW_UART_BAUD2DIV, DW_UART_CHECK_EXP, dw_uart_dis_cbr(), dw_uart_disable_device(), dw_uart_ena_cbr(), dw_uart_enable_device(), dw_uart_flush_output(), dw_uart_get_rxavail(), dw_uart_get_txavail(), DW_UART_RDY_RCV, DW_UART_RDY_SND, dw_uart_ctrl::dw_uart_regbase, dw_uart_set_baud(), dw_uart_set_dps(), dw_uart_set_hwfc(), E_CLSED, E_NOSPT, E_OK, E_PAR, E_SYS, dev_uart_cbs::err_cb, dev_uart_info::hwfc, dev_buffer::len, dev_buffer::ofs, dev_uart_info::opn_cnt, dev_uart_info::rx_buf, dev_uart_cbs::rx_cb, dev_uart_info::status, dev_uart_info::tx_buf, dev_uart_cbs::tx_cb, dev_uart_info::uart_cbs, UART_CMD_ABORT_RX, UART_CMD_ABORT_TX, UART_CMD_BREAK_CLR, UART_CMD_BREAK_SET, UART_CMD_DIS_DEV, UART_CMD_ENA_DEV, UART_CMD_FLUSH_OUTPUT, UART_CMD_GET_RXAVAIL, UART_CMD_GET_STATUS, UART_CMD_GET_TXAVAIL, UART_CMD_SET_BAUD, UART_CMD_SET_DPS_FORMAT, UART_CMD_SET_ERRCB, UART_CMD_SET_HWFC, UART_CMD_SET_RXCB, UART_CMD_SET_RXINT, UART_CMD_SET_RXINT_BUF, UART_CMD_SET_TXCB, UART_CMD_SET_TXINT, UART_CMD_SET_TXINT_BUF, dev_uart_info::uart_ctrl, UART_FC_BOTH, UART_FC_NONE, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_control(), dw_uart_1_control(), dw_uart_2_control(), and dw_uart_3_control().
void dw_uart_isr (DEV_UART * uart_obj, void * ptr)
DesignWare UART interrupt processing routine.
Parameters
[in] uart_obj uart object structure pointer
[in] ptr extra information
Definition at line 894 of file dw_uart.c.
References dev_buffer::buf, dw_uart_dis_cbr(), dw_uart_getchar(), dw_uart_getready(), dw_uart_putchar(), dw_uart_putready(), DW_UART_RDY_RCV, DW_UART_RDY_SND, dw_uart_ctrl::dw_uart_regbase, E_OK, dev_uart_cbs::err_cb, dev_buffer::len, dev_buffer::ofs, dev_uart_info::rx_buf, dev_uart_cbs::rx_cb, dev_uart_info::tx_buf, dev_uart_cbs::tx_cb, dev_uart_info::uart_cbs, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_isr(), dw_uart_1_isr(), dw_uart_2_isr(), and dw_uart_3_isr().
int32_t dw_uart_open (DEV_UART * uart_obj, uint32_t baud)
open a designware uart device
Parameters
[in] uart_obj uart object structure pointer
[in] baud baudrate to initialized
Return values
E_OK Open successfully without any issues
E_OPNED If device was opened before with different baudrate, then return E_OPNED
E_OBJ Device object is not valid
E_PAR Parameter is not valid
E_NOSPT Open settings are not supported
Definition at line 551 of file dw_uart.c.
References dev_uart_info::baudrate, DEV_ENABLED, dev_uart_info::dps_format, dps_format_default, dw_uart_ctrl::dw_apb_bus_freq, DW_UART_BAUD2DIV, DW_UART_CHECK_EXP, dw_uart_disable_interrupt(), dw_uart_get_rxfifo_len(), dw_uart_get_txfifo_len(), dw_uart_init(), dw_uart_ctrl::dw_uart_int_handler, dw_uart_ctrl::dw_uart_regbase, E_OK, E_OPNED, E_PAR, dev_uart_info::extra, dev_uart_info::hwfc, hwfc_default, int_handler_install(), dw_uart_ctrl::intno, dev_uart_info::opn_cnt, dev_uart_info::rx_buf, dw_uart_ctrl::rx_fifo_len, dev_uart_info::status, dev_uart_info::tx_buf, dw_uart_ctrl::tx_fifo_len, dev_uart_info::uart_cbs, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_open(), dw_uart_1_open(), dw_uart_2_open(), and dw_uart_3_open().
int32_t dw_uart_read (DEV_UART * uart_obj, void * data, uint32_t len)
read data through DesignWare UART
Parameters
[in] uart_obj uart object structure pointer
[out] data data that need to read (data must be char type)
[in] len data count need to read
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Can't receive data from hardware due to hardware issues, such as device is disabled
Definition at line 861 of file dw_uart.c.
References DEV_ENABLED, DW_UART_CHECK_EXP, dw_uart_prcv_chr(), dw_uart_ctrl::dw_uart_regbase, E_CLSED, E_OK, E_PAR, E_SYS, dev_uart_info::opn_cnt, dev_uart_info::status, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_read(), dw_uart_1_read(), dw_uart_2_read(), and dw_uart_3_read().
int32_t dw_uart_write (DEV_UART * uart_obj, const void * data, uint32_t len)
send data through DesignWare UART
Parameters
[in] uart_obj uart object structure pointer
[in] data data that need to send (data must be char type)
[in] len data length need to send
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Can't write data to hardware due to hardware issues
Definition at line 823 of file dw_uart.c.
References DEV_ENABLED, DW_UART_CHECK_EXP, dw_uart_psnd_chr(), dw_uart_ctrl::dw_uart_regbase, E_CLSED, E_OK, E_PAR, E_SYS, dev_uart_info::opn_cnt, dev_uart_info::status, dev_uart_info::uart_ctrl, dev_uart::uart_info, and VALID_CHK_UART_INFO_OBJECT.
Referenced by dw_uart_0_write(), dw_uart_1_write(), dw_uart_2_write(), and dw_uart_3_write().