embARC: AXS Common Init Module
AXS Common Init Module
BSP Layer » AXS BSP » AXS Common Module
AXS Board Common Init Module.
Files
file axs.h
axs resource definitions
file axs_init.c
common axs init module
Macros
#define BOARD_CONSOLE_UART_ID DW_UART_2_ID
#define BOARD_CONSOLE_UART_BAUD UART_BAUDRATE_115200
#define BOARD_SYS_TIMER_ID TIMER_0
#define BOARD_SYS_TIMER_INTNO INTNO_TIMER0
#define BOARD_SYS_TIMER_HZ (1000)
#define BOARD_SYS_TIMER_MS_HZ (1000)
board timer count frequency (HZ)
#define BOARD_SYS_TIMER_MS_CONV (BOARD_SYS_TIMER_MS_HZ/BOARD_SYS_TIMER_HZ)
board timer count frequency convention based on the global timer counter
#define BOARD_OS_TIMER_ID TIMER_0
#define BOARD_OS_TIMER_INTNO INTNO_TIMER0
#define BOARD_CPU_CLOCK CLK_CPU
#define BOARD_DEV_CLOCK CLK_BUS_APB
#define BOARD_ONBOARD_NTSHELL_ID (AXS_NTSHELL_0_ID)
#define NTSHELL_CONSOLE_ID (AXS_NTSHELL_0_ID)
#define OSP_DELAY_OS_COMPAT_ENABLE (1)
#define OSP_DELAY_OS_COMPAT_DISABLE (0)
#define OSP_GET_CUR_SYSHZ() (gl_axs_sys_hz_cnt)
#define OSP_GET_CUR_MS() (gl_axs_ms_cnt)
#define OSP_GET_CUR_US() board_get_cur_us()
#define OSP_GET_CUR_HWTICKS() board_get_hwticks()
#define BOARD_LED_MASK (0x0)
#define BOARD_LED_CNT (0)
#define BOARD_BTN_MASK (0x0)
#define BOARD_BTN_CNT (0)
#define BOARD_SWT_MASK (0x0)
#define BOARD_SWT_CNT (0)
#define led_write(val, mask) EMBARC_PRINTF("Led out: val 0x%x, mask 0x%x\r\n", val, mask)
#define led_read(mask) (0x0)
#define led_toggle(mask)
#define switch_read(mask) (0x0)
#define button_read(mask) (0x0)
Functions
void board_init (void)
Board init routine MUST be called in each application.
void board_timer_update (uint32_t precision)
Update timer counter and other MS period operation in cycling interrupt and must be called periodically.
void board_delay_ms (uint32_t ms, uint8_t os_compat)
provide MS delay function
uint64_t board_get_hwticks (void)
get current cpu hardware ticks
uint64_t board_get_cur_us (void)
get current passed us since timer init
Detailed Description
AXS Board Common Init Module.
AXS timer/gpio/interrupt init process. Device-driver installation is done while getting the device object for the first time.
Function Documentation
board_delay_ms()
void board_delay_ms (uint32_t ms, uint8_t os_compat)
provide MS delay function
this function needs a 1-MS timer interrupt to work. For bare-metal, it is implemented in this file. For OS, you must call board_timer_update in the OS 1-MS timer interrupt when the bare-metal timer interrupt is not ready
Parameters
[in] ms MS to delay
[in] os_compat Enable or disable When this delay is enabled, use the OS delay function, if one is provided. See OSP_DELAY_OS_COMPAT_ENABLE and OSP_DELAY_OS_COMPAT_DISABLE
Definition at line 181 of file axs_timer.c.
Referenced by _hm1x_delay().
board_get_cur_us()
uint64_t board_get_cur_us (void)
get current passed us since timer init
Return values
us count in 64 bit format
us count in 64bit format
Definition at line 155 of file axs_timer.c.
board_get_hwticks()
uint64_t board_get_hwticks (void)
get current cpu hardware ticks
Return values
hardware ticks count in 64 bit format
hardware ticks count in 64bit format
Definition at line 139 of file axs_timer.c.
board_init()
void board_init (void)
Board init routine MUST be called in each application.
Note
It is better to disable interrupts when calling this function remember to enable interrupt when you want to use them
Definition at line 62 of file axs_init.c.
References axs_hardware_init(), axs_timer_init(), and timer_init().
board_timer_update()
void board_timer_update (uint32_t precision)
Update timer counter and other MS period operation in cycling interrupt and must be called periodically.
When the OS timer interrupt is in conflict with the bare-metal timer interrupt, put this function into the OS timer interrupt
Parameters
[in] precision interrupt-period precision in Hz
Definition at line 84 of file axs_timer.c.