embARC: UART Device HAL Interface
UART Device HAL Interface
Device HAL » Device HAL Definition
Definitions for uart device hardware layer (dev_uart.h)
Modules
UART Device Baudrate Definitions
Macros for uart baudrate.
UART Device Control Commands
Definitions for uart control command, used in UART IO Control.
UART Device Format Definitions
Macros for uart format.
UART Device Interface Definition
Contains definitions of uart device interface structure.
UART Interrupt callback functions
callback function structure for UART device
Files
file dev_uart.h
uart device hardware layer definitions
Enumerations
enum UART_HW_FLOW_CONTROL { UART_FC_NONE = 0, UART_FC_RTS = 1, UART_FC_CTS = 2, UART_FC_BOTH = 3 }
UART Device Hardware Flow Control Types Enum.
Functions
DEV_UART_PTR uart_get_dev (int32_t uart_id)
get an uart device by uart device id.
Variables
static const UART_HW_FLOW_CONTROL hwfc_default = UART_FC_NONE
Default hardware flow control method.
Detailed Description
Definitions for uart device hardware layer (dev_uart.h)
Provide unified APIs for uart driver to implement. Here is a diagram for the uart interface.
UART Device HAL Interface Diagram
Reference Links
Serial Port
6
Enumeration Type Documentation
enum UART_HW_FLOW_CONTROL
UART Device Hardware Flow Control Types Enum.
Enumerator
UART_FC_NONE
Non hardware flow control
UART_FC_RTS
Request To Send
UART_FC_CTS
Clear To Send
UART_FC_BOTH
Both hardware flow control methods
Definition at line 141 of file dev_uart.h.
Function Documentation
DEV_UART_PTR uart_get_dev (int32_t uart_id)
get an uart device by uart device id.
For how to use uart device hal refer to Functions in uart device structure
Parameters
[in] uart_id id of uart, defined by user
Return values
!NULL pointer to an uart device structure
NULL failed to find the uart device by uart_id
Note
need to implemented by user in user code
get an uart device by uart device id.
Definition at line 272 of file axs/drivers/uart/dw_uart_obj.c.
References dw_uart_0, DW_UART_0_ID, dw_uart_1, DW_UART_1_ID, dw_uart_2, DW_UART_2_ID, dw_uart_all_install(), nsim_uart_0, NSIM_UART_0_ID, and nsim_uart_all_install().
Referenced by hm1x_init().