embARC: NSIM Common Timer Module
NSIM Common Timer Module
BSP Layer » NSIM BSP » nSIM Common Module
provide basic board timer-related functions
Files
file nsim_timer.c
provide nsim board timer-related functions
file nsim_timer.h
nsim timer functions header
Macros
#define MAX_SYS_COUNTER_VALUE (0xffffffff)
#define BOARD_SYS_TIMER_HZ (1000)
#define HZ_COUNT_CONV(precision, base) ((precision)/(base))
Functions
void board_timer_update (uint32_t precision)
Update timer counter and other MS period operation in cycling interrupt and must be called periodically.
static void nsim_timer_isr (void *ptr)
nsim bare-metal timer interrupt.
void nsim_timer_init (void)
init bare-metal nsim board timer and interrupt
uint64_t board_get_hwticks (void)
get current cpu hardware ticks
uint64_t board_get_cur_us (void)
get current passed us since timer init
void board_delay_ms (uint32_t ms, uint8_t os_compat)
provide MS delay function
Variables
static uint32_t cyc_hz_count = (BOARD_CPU_CLOCK / BOARD_SYS_TIMER_HZ)
nsim board timer interrupt reset count
volatile uint64_t gl_nsim_sys_hz_cnt = 0
nsim board timer counter in timer interrupt
volatile uint32_t gl_nsim_ms_cnt = 0
nsim board 1ms counter
volatile uint64_t gl_nsim_sys_hz_cnt
nsim board timer counter in timer interrupt
volatile uint32_t gl_nsim_ms_cnt
nsim board 1ms counter
Detailed Description
provide basic board timer-related functions
Provide a 1 MS (default) timer interrupt, provide a 64-bit counter value (no clear) count in the timer interrupt, provide MS-precision delay, with OS enabled-support delay
Function Documentation
void board_delay_ms (uint32_t ms, uint8_t os_compat)
provide MS delay function
this function needs a 1-MS timer interrupt to work. For bare-metal, it is implemented in this file. For OS, you must call board_timer_update in the OS 1-MS timer interrupt when the bare-metal timer interrupt is not ready
Parameters
[in] ms MS to delay
[in] os_compat Enable or disable When this delay is enabled, use the OS delay function, if one is provided. See OSP_DELAY_OS_COMPAT_ENABLE and OSP_DELAY_OS_COMPAT_DISABLE
Definition at line 185 of file nsim_timer.c.
References board_get_cur_us().
Referenced by hm1x_delay(), and main().
uint64_t board_get_cur_us (void)
get current passed us since timer init
Return values
us count in 64bit format
Definition at line 159 of file nsim_timer.c.
References TIMER_0, and timer_current().
Referenced by board_delay_ms().
uint64_t board_get_hwticks (void)
get current cpu hardware ticks
Return values
hardware ticks count in 64bit format
Definition at line 143 of file nsim_timer.c.
References TIMER_0, and timer_current().
void board_timer_update (uint32_t precision)
Update timer counter and other MS period operation in cycling interrupt and must be called periodically.
When the OS timer interrupt is in conflict with the bare-metal timer interrupt, put this function into the OS timer interrupt
Parameters
[in] precision interrupt-period precision in Hz
Definition at line 87 of file nsim_timer.c.
References BOARD_SYS_TIMER_MS_HZ, gl_axs_ms_cnt, gl_axs_sys_hz_cnt, gl_nsim_ms_cnt, and gl_nsim_sys_hz_cnt.
Referenced by nsim_timer_isr().
void nsim_timer_init (void)
init bare-metal nsim board timer and interrupt
This function is called in board_init, and it initializes the 1-MS timer interrupt for bare-metal mode
Definition at line 128 of file nsim_timer.c.
References cyc_hz_count, int_disable(), int_enable(), int_handler_install(), nsim_timer_isr(), TIMER_CTRL_IE, TIMER_CTRL_NH, timer_present(), and timer_start().
Referenced by board_init().
static void nsim_timer_isr (void * ptr) static
nsim bare-metal timer interrupt.
the Interrupt frequency is based on the defined BOARD_SYS_TIMER_HZ
Definition at line 115 of file nsim_timer.c.
References board_timer_update(), and timer_int_clear().
Referenced by nsim_timer_init().