embARC: EMSK RF-MRF24J40 Driver
EMSK RF-MRF24J40 Driver
BSP Layer » EMSK BSP » EMSK Peripheral Driver Module » EMSK RF 802.15.4 Driver
EMSK RF MRF24J40 driver.
Files
file mrf24j40.c
RF MRF24J40 driver.
file mrf24j40.h
header file of Pmod MRF24J40MA driver for EMSK board
Data Structures
struct mrf24j40_def
Macros
#define DEBUG
#define EMSK_PMRF_0_SPI_CPULOCK_ENABLE
#define MRF_CHECK_EXP(EXPR, ERROR_CODE) CHECK_EXP(EXPR, ercd, ERROR_CODE, error_exit)
#define MRF_GPIO_SETUP(port_pin, port, pin)
#define MRF_GPIO_PORT_SETUP(port_pin, port) port = (port_pin & 0xffff0000) >>16
#define MRF_GPIO_PIN_SETUP(port_pin, pin) pin = port_pin & 0xffff
#define MRF24J40_BUF_SIZE 144
#define MRF24J40_RXFIFO_SIZE 144
#define MRF24J40_INT_RX 0x01
#define MRF24J40_INT_TX 0x02
#define MRF24J40_INT_SEC 0x04
#define MRF24J40_INT_SLP 0x08
#define MRF24J40_INT_ENC 0x10
#define MRF24J40_INT_DEC 0x20
#define IEEE_802_15_4_HAS_SEC(x) ((x >> 3) & 0x01)
#define IEEE_802_15_4_WANTS_ACK(x) ((x >> 5) & 0x01)
#define MRF24J40_TX_KEY 0x01
#define MRF24J40_RX_KEY 0x02
#define MRF24J40_UP_KEY MRF24J40_TX_KEY
#define MRF24J40_AES_CBC_MAC32 0x07
#define MRF24J40_AES_CBC_MAC64 0x06
#define MRF24J40_AES_CBC_MAC128 0x05
#define MRF24J40_AES_CCM32 0x04
#define MRF24J40_AES_CCM64 0x03
#define MRF24J40_AES_CCM128 0x02
#define MRF24J40_AES_CTR 0x01
#define MRF24J40_ALGO_NONE 0x00
#define MRF24J40_RXMCR 0x00
#define MRF24J40_PANIDL 0x01
#define MRF24J40_PANIDH 0x02
#define MRF24J40_SADRL 0x03
#define MRF24J40_SADRH 0x04
#define MRF24J40_EADR0 0x05
#define MRF24J40_EADR1 0x06
#define MRF24J40_EADR2 0x07
#define MRF24J40_EADR3 0x08
#define MRF24J40_EADR4 0x09
#define MRF24J40_EADR5 0x0A
#define MRF24J40_EADR6 0x0B
#define MRF24J40_EADR7 0x0C
#define MRF24J40_RXFLUSH 0x0D
#define MRF24J40_ORDER 0x10
#define MRF24J40_TXMCR 0x11
#define MRF24J40_ACKTMOUT 0x12
#define MRF24J40_ESLOTG1 0x13
#define MRF24J40_SYMTICKL 0x14
#define MRF24J40_SYMTICKH 0x15
#define MRF24J40_PACON0 0x16
#define MRF24J40_PACON1 0x17
#define MRF24J40_PACON2 0x18
#define MRF24J40_TXBCON0 0x1A
#define MRF24J40_TXNCON 0x1B
#define MRF24J40_TXG1CON 0x1C
#define MRF24J40_TXG2CON 0x1D
#define MRF24J40_ESLOTG23 0x1E
#define MRF24J40_ESLOTG45 0x1F
#define MRF24J40_ESLOTG67 0x20
#define MRF24J40_TXPEND 0x21
#define MRF24J40_WAKECON 0x22
#define MRF24J40_FRMOFFSET 0x23
#define MRF24J40_TXSTAT 0x24
#define MRF24J40_TXBCON1 0x25
#define MRF24J40_GATECLK 0x26
#define MRF24J40_TXTIME 0x27
#define MRF24J40_HSYMTMRL 0x28
#define MRF24J40_HSYMTMRH 0x29
#define MRF24J40_SOFTRST 0x2A
#define MRF24J40_SECCON0 0x2c
#define MRF24J40_SECCON1 0x2d
#define MRF24J40_TXSTBL 0x2e
#define MRF24J40_RXSR 0x30
#define MRF24J40_INTSTAT 0x31
#define MRF24J40_INTCON 0x32
#define MRF24J40_GPIO 0x33
#define MRF24J40_TRISGPIO 0x34
#define MRF24J40_SLPACK 0x35
#define MRF24J40_RFCTL 0x36
#define MRF24J40_SECCR2 0x37
#define MRF24J40_BBREG0 0x38
#define MRF24J40_BBREG1 0x39
#define MRF24J40_BBREG2 0x3A
#define MRF24J40_BBREG3 0x3B
#define MRF24J40_BBREG4 0x3C
#define MRF24J40_BBREG6 0x3E
#define MRF24J40_CCAEDTH 0x3F
#define MRF24J40_RFCON0 0x200
#define MRF24J40_RFCON1 0x201
#define MRF24J40_RFCON2 0x202
#define MRF24J40_RFCON3 0x203
#define MRF24J40_RFCON5 0x205
#define MRF24J40_RFCON6 0x206
#define MRF24J40_RFCON7 0x207
#define MRF24J40_RFCON8 0x208
#define MRF24J40_RFSTATE 0x20F
#define MRF24J40_RSSI 0x210
#define MRF24J40_SLPCON0 0x211
#define MRF24J40_SLPCON1 0x220
#define MRF24J40_WAKETIMEL 0x222
#define MRF24J40_WAKETIMEH 0x223
#define MRF24J40_AINCNT0 0x226
#define MRF24J40_AINCNT1 0x227
#define MRF24J40_AINCNT2 0x228
#define MRF24J40_AINCNT3 0x229
#define MRF24J40_ASSOEADR0 0x230
#define MRF24J40_ASSOEADR1 0x231
#define MRF24J40_ASSOEADR2 0x232
#define MRF24J40_ASSOEADR3 0x233
#define MRF24J40_ASSOEADR4 0x234
#define MRF24J40_ASSOEADR5 0x235
#define MRF24J40_ASSOEADR6 0x236
#define MRF24J40_ASSOEADR7 0x237
#define MRF24J40_ASSOSADR0 0x238
#define MRF24J40_ASSOSADR1 0x239
#define MRF24J40_UPNONCE0 0x240
#define MRF24J40_UPNONCE1 0x241
#define MRF24J40_UPNONCE2 0x242
#define MRF24J40_UPNONCE3 0x243
#define MRF24J40_UPNONCE4 0x244
#define MRF24J40_UPNONCE5 0x245
#define MRF24J40_UPNONCE6 0x246
#define MRF24J40_UPNONCE7 0x247
#define MRF24J40_UPNONCE8 0x248
#define MRF24J40_UPNONCE9 0x249
#define MRF24J40_UPNONCE10 0x24A
#define MRF24J40_UPNONCE11 0x24B
#define MRF24J40_UPNONCE12 0x24C
#define MRF24J40_TXNFIFO 0x000 /* - 0x07F, 128 bytes */
#define MRF24J40_TXBFIFO 0x080 /* - 0x0FF, 128 bytes */
#define MRF24J40_TXG1FIFO 0x100 /* - 0x17F, 128 bytes */
#define MRF24J40_TXG2FIFO 0x180 /* - 0x1FF, 128 bytes */
#define MRF24J40_SECKFIFO 0x280 /* - 0x2BF, 64 bytes */
#define MRF24J40_SECKTXNFIFO 0x280 /* - 0x28F, 16 bytes */
#define MRF24J40_SECKRXFIFO 0x2B0 /* - 0x2BF, 16 bytes */
#define MRF24J40_RXFIFO 0x300 /* - 0x38F, 144 bytes */
#define MRF24J40_NOACKRSP (1<<5)
#define MRF24J40_PANCOORD (1<<3)
#define MRF24J40_COORD (1<<2)
#define MRF24J40_ERRPKT (1<<1)
#define MRF24J40_PROMI (1)
#define MRF24J40_WAKEPOL (1<<6)
#define MRF24J40_WAKEPAD (1<<5)
#define MRF24J40_CMDONLY (1<<3)
#define MRF24J40_DATAONLY (1<<2)
#define MRF24J40_BCNONLY (1<<1)
#define MRF24J40__RXFLUSH (1)
#define MRF24J40_NOCSMA (1<<7)
#define MRF24J40_BATLIFEXT (1<<6)
#define MRF24J40_SLOTTED (1<<5)
#define MRF24J40_MACMINBE(x) ((x & 0x03)<<3)
#define MRF24J40_CSMABF(x) (x & 0x07)
#define MRF24J40_DRPACK (1<<7)
#define MRF24J40_FIFOEN (1<<7)
#define MRF24J40_TXONTS(x) (x & 0x3F)
#define MRF24J40_FPSTAT (1<<4)
#define MRF24J40_INDIRECT (1<<3)
#define MRF24J40_TXNACKREQ (1<<2)
#define MRF24J40_TXNSECEN (1<<1)
#define MRF24J40_TXNTRIG (1)
#define MRF24J40_FPACK (1)
#define MRF24J40_IMMWAKE (1<<7)
#define MRF24J40_REGWAKE (1<<6)
#define MRF24J40_CCAFAIL (1<<5)
#define MRF24J40_TXNSTAT (1)
#define MRF24J40_RSTPWR (1<<2)
#define MRF24J40_RSTBB (1<<1)
#define MRF24J40_RSTMAC (1)
#define MRF24J40_SECIGNORE (1<<7)
#define MRF24J40_SECSTART (1<<6)
#define MRF24J40_RXCIPHER(x) ((x & 0x07) << 3)
#define MRF24J40_TXNCIPHER(x) ((x & 0x07))
#define MRF24J40_DISDEC (1<<1)
#define MRF24J40_DISENC (1)
#define MRF24J40_RFSTBL(x) ((x & 0x0f) << 4)
#define MRF24J40_MSIFS(x) ((x & 0x0f))
#define MRF24J40_UPSECERR (1<<6)
#define MRF24J40_SECDECERR (1<<2)
#define MRF24J40_SLPIF (1<<7)
#define MRF24J40_WAKEIF (1<<6)
#define MRF24J40_HSYMTMRIF (1<<5)
#define MRF24J40_SECIF (1<<4)
#define MRF24J40_RXIF (1<<3)
#define MRF24J40_TXG2IF (1<<2)
#define MRF24J40_TXG1IF (1<<1)
#define MRF24J40_TXNIF (1)
#define MRF24J40_SLPIE (1<<7)
#define MRF24J40_WAKEIE (1<<6)
#define MRF24J40_HSYMTMRIE (1<<5)
#define MRF24J40_SECIE (1<<4)
#define MRF24J40_RXIE (1<<3)
#define MRF24J40_TXG2IE (1<<2)
#define MRF24J40_TXG1IE (1<<1)
#define MRF24J40_TXNIE (1)
#define MRF24J40__SLPACK (1<<7)
#define MRF24J40_WAKECNT_L(x) (x & 0x03F)
#define MRF24J40_WAKECNT_H(x) ((x & 0x03) << 3)
#define MRF24J40_RFRST (1<<2)
#define MRF24J40_RFTXMODE (1<<1)
#define MRF24J40_RFRXMODE (1)
#define MRF24J40_UPDEC (1<<7)
#define MRF24J40_UPENC (1<<6)
#define MRF24J40_TURBO (1)
#define MRF24J40_RXDECINV (1<<2)
#define MRF24J40_CCAMODE(x) ((x & 0x03) <<6)
#define MRF24J40_CCASTH(x) ((x & 0x0F) <<2)
#define MRF24J40_PREVALIDTH(x) ((x & 0x0F) <<4)
#define MRF24J40_CSTH(x) ((x & 0x07) << 5)
#define MRF24J40_RSSIMODE1 (1 << 7)
#define MRF24J40_RSSIMODE2 (1<<6)
#define MRF24J40_RSSIRDY (1)
#define MRF24J40_CHANNEL(x) ((x & 0x0F) << 4)
#define MRF24J40_RFOPT(x) ((x & 0x0F))
#define MRF24J40_VCOOPT(x) ((x & 0xFF))
#define MRF24J40_PLLEN (1<<7)
#define MRF24J40_TXPWRL(x) ((x & 0x03) << 6)
#define MRF24J40_TXPWRS(x) ((x & 0x07) << 3)
#define MRF24J40_TXFIL (1 << 7)
#define MRF24J40__20MRECVR (1 << 4)
#define MRF24J40_BATEN (1 << 3)
#define MRF24J40_SLPCLKSEL(x) ((x & 0x03) << 6)
#define MRF24J40_SLPCLKSEL_100k (MRF24J40_SLPCLKSEL(0x02))
#define MRF24J40_SLPCLKSEL_32k (MRF24J40_SLPCLKSEL(0x01))
#define MRF24J40_RFVCO (1 << 4)
#define MRF24J40_SLPCLKEN (1)
#define MRF24J40_CLKOUTDIS (1 << 5) /* CLKOUTEN' */
#define MRF24J40_SLPCLKDIV(x) ((x & 0x1F)) /* division ratio: 2^(SLPCLKDIV) */
Typedefs
typedef enum mrf24j40_chstate MRF24J40_CHSTATE
typedef struct mrf24j40_def MRF24J40_DEF
typedef struct mrf24j40_def * MRF24J40_DEF_PTR
Enumerations
enum mrf24j40_chstate { MRF24J40_EIO = 0, MRF24J40_EBUSY = 1 }
Functions
static int32_t spi_check_obj (MRF24J40_DEF *mrf24j40)
static int32_t gpio_check_obj (MRF24J40_DEF *mrf24j40)
static int32_t spi_read_long_ctrl_reg (MRF24J40_DEF *mrf24j40, uint16_t addr, uint8_t *val)
static int32_t spi_read_short_ctrl_reg (MRF24J40_DEF *mrf24j40, uint16_t addr, uint8_t *val)
static int32_t spi_write_long_ctrl_reg (MRF24J40_DEF *mrf24j40, uint16_t addr, uint8_t value)
static int32_t spi_write_short_ctrl_reg (MRF24J40_DEF *mrf24j40, uint8_t addr, uint8_t value)
static void mrf24j40_delay_us (uint32_t us)
static void mrf24j40_delay_ms (uint32_t ms)
static int32_t mrf24j40_hard_reset (MRF24J40_DEF *mrf24j40, uint8_t flag)
Hardware reset.
int32_t mrf24j40_read_long_ctrl_reg (MRF24J40_DEF *mrf24j40, uint16_t addr, uint8_t *val)
Read register in long address memory space.
int32_t mrf24j40_read_short_ctrl_reg (MRF24J40_DEF *mrf24j40, uint8_t addr, uint8_t *val)
Read register in short address memory space.
int32_t mrf24j40_write_long_ctrl_reg (MRF24J40_DEF *mrf24j40, uint16_t addr, uint8_t value)
Write register in long address memory space.
int32_t mrf24j40_write_short_ctrl_reg (MRF24J40_DEF *mrf24j40, uint8_t addr, uint8_t value)
Write register in short address memory space.
int32_t mrf24j40_rxfifo_flush (MRF24J40_DEF *mrf24j40)
Set RXFLUSH in RXFLUSH: Receive FIFO Flush Register.
int32_t mrf24j40_get_pending_frame (MRF24J40_DEF *mrf24j40, uint8_t *pend)
Get FPSTAT in TXNCON: Transmit Normal FIFO Control Register.
int32_t mrf24j40_reset (MRF24J40_DEF *mrf24j40)
Perform hardware Reset by asserting RESET pin.
static int32_t mrf24j40_wake_pin (MRF24J40_DEF *mrf24j40, uint8_t flag)
int32_t mrf24j40_sleep (MRF24J40_DEF *mrf24j40)
Perform hardware Reset by asserting RESET pin.
static int32_t mrf24j40_rf_reset (MRF24J40_DEF *mrf24j40)
Set RFCTL: RF Mode Control Register.
void mrf24j40_initialize (MRF24J40_DEF *mrf24j40)
Initialize MRF24J40.
int32_t mrf24j40_setup (MRF24J40_DEF *mrf24j40)
Setup MRF24J40 module.
int32_t mrf24j40_set_short_addr (MRF24J40_DEF *mrf24j40, uint8_t *addr)
Set short address in SADRL and SADRH.
int32_t mrf24j40_set_coordinator_short_addr (MRF24J40_DEF *mrf24j40, uint8_t *addr)
Set associated coordinator short address in ASSOSADR0 and ASSOSADR1.
int32_t mrf24j40_set_coordinator_eui (MRF24J40_DEF *mrf24j40, uint8_t *eui)
Set associated coordinator extended address from ASSOEADR0 to ASSOEADR7.
int32_t mrf24j40_set_eui (MRF24J40_DEF *mrf24j40, uint8_t *eui)
Set extended address from EADR0 to EADR7.
int32_t mrf24j40_set_pan (MRF24J40_DEF *mrf24j40, uint8_t *pan)
Set PAN ID in PANIDL and PANIDH.
static int32_t mrf24j40_set_key (MRF24J40_DEF *mrf24j40, uint16_t addr, uint8_t *key)
int32_t mrf24j40_set_tx_key (MRF24J40_DEF *mrf24j40, uint8_t *key)
Set key in address for SECKTXNFIFO.
int32_t mrf24j40_set_rx_key (MRF24J40_DEF *mrf24j40, uint8_t *key)
Set key in address for SECKRXFIFO.
int32_t mrf24j40_set_channel (MRF24J40_DEF *mrf24j40, int16_t ch)
Set CHANNEL in RFCON0: RF Control 0 Register.
int32_t mrf24j40_set_promiscuous (MRF24J40_DEF *mrf24j40, uint8_t crc_check)
Set PROMI in RXMCR: Receive MAC Control Register.
int32_t mrf24j40_set_coordinator (MRF24J40_DEF *mrf24j40, uint8_t mark)
Set PANCOORD in RXMCR: Receive MAC Control Register.
static int32_t mrf24j40_txpkt_frame_write (MRF24J40_DEF *mrf24j40, uint16_t address, uint8_t *frame, uint8_t hdr_len, uint8_t frame_len)
int32_t mrf24j40_txpkt (MRF24J40_DEF *mrf24j40)
Enable and transmit frame in TX Normal FIFO from tx_buf.
int32_t mrf24j40_set_cipher (MRF24J40_DEF *mrf24j40, uint8_t rxcipher, uint8_t txcipher)
Set RXCIPHER and TXNCIPHER in SECCON0: Security Control 0 Register.
int32_t mrf24j40_rx_sec_fail (MRF24J40_DEF *mrf24j40, uint8_t *err)
Read SECDECERR in RXSR: RX MAC Status Register.
static int32_t mrf24j40_rxpkt_frame_write (MRF24J40_DEF *mrf24j40, uint8_t *buf, uint8_t length)
int32_t mrf24j40_rxpkt (MRF24J40_DEF *mrf24j40, uint8_t *plqi, uint8_t *prssi)
Read RX packet in RX FIFO from rx_buf.
int32_t mrf24j40_set_decrypt_start (MRF24J40_DEF *mrf24j40, uint8_t accept)
Set SECIGNORE/SECSTART in SECCON0: Security Control 0 Register.
int32_t mrf24j40_txfifo_write (MRF24J40_DEF *mrf24j40, uint16_t address, uint8_t *data, uint8_t hdr_len, uint8_t len)
Write TX FIFO.
int32_t mrf24j40_set_transmit_trig (MRF24J40_DEF *mrf24j40)
Set TXNTRIG in TXNCON: Transmit normal FIFO control register.
int32_t mrf24j40_wakeup (MRF24J40_DEF *mrf24j40)
Detailed Description
EMSK RF MRF24J40 driver.
Implement the MRF24J40 driver using the DesignWare SPI device driver.
Macro Definition Documentation
#define MRF_GPIO_SETUP (port_pin, port, pin)
Value:
{ \
                port = (port_pin & 0xffff0000) >>16; \
                pin = port_pin & 0xffff; \
        }
Definition at line 76 of file mrf24j40.c.
Function Documentation
int32_t mrf24j40_get_pending_frame (MRF24J40_DEF * mrf24j40, uint8_t * pend)
Get FPSTAT in TXNCON: Transmit Normal FIFO Control Register.
Get status of the frame pending bit in the received Acknowledgement frame
Parameters
[in] mrf24j40 MRF24J40 object pointer
[out] pend Point of frame pending bit { 1: set frame pending bit, 2: clear frame pending bit }
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_PAR value point (pend) is NULL
E_SYS Error in SPI process
Definition at line 442 of file mrf24j40.c.
References E_OK, E_PAR, E_SYS, and mrf24j40_read_short_ctrl_reg().
static int32_t mrf24j40_hard_reset (MRF24J40_DEF * mrf24j40, uint8_t flag) static
Hardware reset.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] flag GPIO direction { 1: high, 2: low }
Return values
E_OK Control device successfully
E_SYS Error in GPIO process
Definition at line 291 of file mrf24j40.c.
References E_OK, E_SYS, gpio_get_dev(), and dev_gpio::gpio_write.
Referenced by mrf24j40_reset().
int32_t mrf24j40_read_long_ctrl_reg (MRF24J40_DEF * mrf24j40, uint16_t addr, uint8_t * val)
Read register in long address memory space.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] addr Register address
[out] val Point of value from control register
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_PAR value point (val) is NULL
E_SYS Error in SPI process
Definition at line 323 of file mrf24j40.c.
References E_OBJ, E_OK, and E_PAR.
Referenced by mrf24j40_initialize(), and mrf24j40_rxpkt().
int32_t mrf24j40_read_short_ctrl_reg (MRF24J40_DEF * mrf24j40, uint8_t addr, uint8_t * val)
Read register in short address memory space.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] addr Register address
[out] val Point of value from control register
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_PAR value point (val) is NULL
E_SYS Error in SPI process
Definition at line 351 of file mrf24j40.c.
References E_OBJ, E_OK, and E_PAR.
Referenced by mrf24j40_get_pending_frame(), mrf24j40_initialize(), mrf24j40_rf_reset(), mrf24j40_rx_sec_fail(), mrf24j40_rxfifo_flush(), mrf24j40_rxpkt(), mrf24j40_set_coordinator(), mrf24j40_set_decrypt_start(), mrf24j40_set_promiscuous(), mrf24j40_set_transmit_trig(), mrf24j40_sleep(), and mrf24j40_txpkt().
int32_t mrf24j40_reset (MRF24J40_DEF * mrf24j40)
Perform hardware Reset by asserting RESET pin.
The MRF24J40 will be released from Reset approximately 250 us after the RESET pin is released.
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in GPIO process
Definition at line 465 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, and mrf24j40_hard_reset().
Referenced by mrf24j40_initialize().
static int32_t mrf24j40_rf_reset (MRF24J40_DEF * mrf24j40) static
Set RFCTL: RF Mode Control Register.
Perform RF Reset by setting RFRST = 1 and then RFRST = 0
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in GPIO process
Definition at line 543 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
Referenced by mrf24j40_initialize(), and mrf24j40_set_channel().
int32_t mrf24j40_rx_sec_fail (MRF24J40_DEF * mrf24j40, uint8_t * err)
Read SECDECERR in RXSR: RX MAC Status Register.
Read security decryption error bit
Parameters
[in] mrf24j40 MRF24J40 object pointer
[out] err 0 Security decryption error occurred 1 Security decryption error did not occur
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI/GPIO process
Definition at line 1096 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_rxfifo_flush (MRF24J40_DEF * mrf24j40)
Set RXFLUSH in RXFLUSH: Receive FIFO Flush Register.
Reset RXFIFO address pointer to zero
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI process
Definition at line 417 of file mrf24j40.c.
References E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
Referenced by mrf24j40_initialize(), and mrf24j40_rxpkt().
int32_t mrf24j40_rxpkt (MRF24J40_DEF * mrf24j40, uint8_t * plqi, uint8_t * prssi)
Read RX packet in RX FIFO from rx_buf.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[out] *plqi Pointer of LQI in RX FIFO
[out] *prssi Pointer of RSSI in RX FIFO
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR Frame length is bigger than buffer size
E_SYS Error in SPI/GPIO process
Definition at line 1167 of file mrf24j40.c.
References E_OBJ, E_OK, E_PAR, E_SYS, mrf24j40_read_long_ctrl_reg(), mrf24j40_read_short_ctrl_reg(), mrf24j40_rxfifo_flush(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_channel (MRF24J40_DEF * mrf24j40, int16_t ch)
Set CHANNEL in RFCON0: RF Control 0 Register.
Set channel number
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] ch Channel number, 0000 = Channel 11 (2405 MHz) as default
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI/GPIO process
Definition at line 890 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_rf_reset(), and mrf24j40_write_long_ctrl_reg().
int32_t mrf24j40_set_cipher (MRF24J40_DEF * mrf24j40, uint8_t rxcipher, uint8_t txcipher)
Set RXCIPHER and TXNCIPHER in SECCON0: Security Control 0 Register.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] rxcipher RX FIFO security suite select bits
[in] txcipher TX normal FIFO security suite select bits
111 = AES-CBC-MAC-32 110 = AES-CBC-MAC-64 101 = AES-CBC-MAC-128 100 = AES-CMM-32 011 = AES-CMM-64 010 = AES-CMM-128 001 = AES-CTR 000 = None (default)
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI/GPIO process
Definition at line 1074 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_coordinator (MRF24J40_DEF * mrf24j40, uint8_t mark)
Set PANCOORD in RXMCR: Receive MAC Control Register.
Set device as PAN coordinator
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] mark 1 = Set as PAN coordinator 0 = Not Set as PAN coordinator
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR mark is not 0 or 1
E_SYS Error in SPI/GPIO process
Definition at line 947 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_coordinator_eui (MRF24J40_DEF * mrf24j40, uint8_t * eui)
Set associated coordinator extended address from ASSOEADR0 to ASSOEADR7.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] *eui Pointer of associated coordinator extended address, eui[0] to eui[7]
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR eui point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 730 of file mrf24j40.c.
References E_OK, E_PAR, E_SYS, and mrf24j40_write_long_ctrl_reg().
int32_t mrf24j40_set_coordinator_short_addr (MRF24J40_DEF * mrf24j40, uint8_t * addr)
Set associated coordinator short address in ASSOSADR0 and ASSOSADR1.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] *addr Pointer of associated coordinator short address
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR addr point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 709 of file mrf24j40.c.
References E_OK, E_PAR, E_SYS, and mrf24j40_write_long_ctrl_reg().
int32_t mrf24j40_set_decrypt_start (MRF24J40_DEF * mrf24j40, uint8_t accept)
Set SECIGNORE/SECSTART in SECCON0: Security Control 0 Register.
Set RX security decryption ignore/start bit
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] accept 1: start decryption process, 0: ignore decryption process
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI/GPIO process
Definition at line 1211 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_eui (MRF24J40_DEF * mrf24j40, uint8_t * eui)
Set extended address from EADR0 to EADR7.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] *eui Pointer of extended address, eui[0] to eui[7]
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR eui point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 757 of file mrf24j40.c.
References E_OK, E_PAR, E_SYS, and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_pan (MRF24J40_DEF * mrf24j40, uint8_t * pan)
Set PAN ID in PANIDL and PANIDH.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] *pan Pointer of PAN ID, pan[0] for low byte and pan[1] for high byte
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR pan point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 784 of file mrf24j40.c.
References E_OK, E_PAR, E_SYS, and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_promiscuous (MRF24J40_DEF * mrf24j40, uint8_t crc_check)
Set PROMI in RXMCR: Receive MAC Control Register.
Set promiscuous mode
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] crc_check 1 = Discard packet when there is a MAC address mismatch, illegal frame type, dPAN/sPAN or MAC short address mismatch, 0 = Receive all packet types with good CRC
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR crc_check is not 0 or 1
E_SYS Error in SPI/GPIO process
Definition at line 914 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_rx_key (MRF24J40_DEF * mrf24j40, uint8_t * key)
Set key in address for SECKRXFIFO.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] *key Pointer of security key (16 bytes)
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR key point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 869 of file mrf24j40.c.
References E_OBJ, E_OK, E_PAR, and E_SYS.
int32_t mrf24j40_set_short_addr (MRF24J40_DEF * mrf24j40, uint8_t * addr)
Set short address in SADRL and SADRH.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] addr Pointer of short address, addr[0] for low byte and addr[1] for high byte
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR addr point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 688 of file mrf24j40.c.
References E_OK, E_PAR, E_SYS, and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_transmit_trig (MRF24J40_DEF * mrf24j40)
Set TXNTRIG in TXNCON: Transmit normal FIFO control register.
Transmit frame in TX normal FIFO bit
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI/GPIO process
Definition at line 1256 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_set_tx_key (MRF24J40_DEF * mrf24j40, uint8_t * key)
Set key in address for SECKTXNFIFO.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] *key Pointer of security key (16 bytes)
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR key point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 848 of file mrf24j40.c.
References E_OBJ, E_OK, E_PAR, and E_SYS.
int32_t mrf24j40_setup (MRF24J40_DEF * mrf24j40)
Setup MRF24J40 module.
Setup MRF24J40 structure and initialize MRF24J40 hardware
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_CLSED GPIO is no open
Definition at line 640 of file mrf24j40.c.
References E_CLSED, E_OBJ, E_OK, E_OPNED, GPIO_CMD_DIS_BIT_INT, GPIO_CMD_SET_BIT_DIR_OUTPUT, dev_gpio::gpio_control, gpio_get_dev(), and dev_gpio::gpio_open.
int32_t mrf24j40_sleep (MRF24J40_DEF * mrf24j40)
Perform hardware Reset by asserting RESET pin.
The MRF24J40 will be released from Reset approximately 250 us after the RESET pin is released.
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in GPIO process
Definition at line 511 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_txfifo_write (MRF24J40_DEF * mrf24j40, uint16_t address, uint8_t * data, uint8_t hdr_len, uint8_t len)
Write TX FIFO.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] address FIFO Address (TX Normal FIFO)
[in] data Pointer of data for TX FIFO
[in] hdr_len Header legnth for TX FIFO
[in] len Frame length for TX FIFO
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI/GPIO process
Definition at line 1236 of file mrf24j40.c.
References E_OBJ, E_OK, and E_SYS.
int32_t mrf24j40_txpkt (MRF24J40_DEF * mrf24j40)
Enable and transmit frame in TX Normal FIFO from tx_buf.
Parameters
[in] mrf24j40 MRF24J40 object pointer
Return values
E_OK Setup device successfully
E_OBJ Device object is not valid or not exists
E_PAR key point is NULL
E_SYS Error in SPI/GPIO process
Definition at line 1029 of file mrf24j40.c.
References E_OBJ, E_OK, E_SYS, mrf24j40_read_short_ctrl_reg(), and mrf24j40_write_short_ctrl_reg().
int32_t mrf24j40_write_long_ctrl_reg (MRF24J40_DEF * mrf24j40, uint16_t addr, uint8_t value)
Write register in long address memory space.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] addr Register address
[in] value Value to control register
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI process
Definition at line 378 of file mrf24j40.c.
References E_OBJ, and E_OK.
Referenced by mrf24j40_initialize(), mrf24j40_set_channel(), mrf24j40_set_coordinator_eui(), and mrf24j40_set_coordinator_short_addr().
int32_t mrf24j40_write_short_ctrl_reg (MRF24J40_DEF * mrf24j40, uint8_t addr, uint8_t value)
Write register in short address memory space.
Parameters
[in] mrf24j40 MRF24J40 object pointer
[in] addr Register address
[in] value Value to control register
Return values
E_OK Control device successfully
E_OBJ Device object is not valid or not exists
E_SYS Error in SPI process
Definition at line 398 of file mrf24j40.c.
References E_OBJ, and E_OK.
Referenced by mrf24j40_initialize(), mrf24j40_rf_reset(), mrf24j40_rx_sec_fail(), mrf24j40_rxfifo_flush(), mrf24j40_rxpkt(), mrf24j40_set_cipher(), mrf24j40_set_coordinator(), mrf24j40_set_decrypt_start(), mrf24j40_set_eui(), mrf24j40_set_pan(), mrf24j40_set_promiscuous(), mrf24j40_set_short_addr(), mrf24j40_set_transmit_trig(), mrf24j40_sleep(), and mrf24j40_txpkt().