embARC: UART Device Interface Definition
UART Device Interface Definition
Device HAL » Device HAL Definition » UART Device HAL Interface
Contains definitions of uart device interface structure.
Data Structures
struct dev_uart_info
UART information struct definition.
struct dev_uart
UART device interface definition.
Macros
#define DEV_UART_INFO_SET_EXTRA_OBJECT(uart_info_ptr, extra_info) (uart_info_ptr)->extra = (void *)(extra_info)
Set extra information pointer of uart info.
#define DEV_UART_INFO_GET_EXTRA_OBJECT(uart_info_ptr) ((uart_info_ptr)->extra)
Get extra information pointer of uart info.
Typedefs
typedef struct dev_uart_info DEV_UART_INFO
UART information struct definition.
typedef struct dev_uart_info * DEV_UART_INFO_PTR
typedef struct dev_uart DEV_UART
UART device interface definition.
typedef struct dev_uart * DEV_UART_PTR
Variables
int32_t(* dev_uart::uart_open)(uint32_t baud)
int32_t(* dev_uart::uart_close)(void)
int32_t(* dev_uart::uart_control)(uint32_t ctrl_cmd, void *param)
int32_t(* dev_uart::uart_write)(const void *data, uint32_t len)
int32_t(* dev_uart::uart_read)(void *data, uint32_t len)
Detailed Description
Contains definitions of uart device interface structure.
This structure will be used in user implemented code, which was called Device Driver Implement Layer for uart to use in implementation code. Application developer should use the UART API provided here to access to UART devices. BSP developer should follow the API definition to implement UART device drivers.
Typedef Documentation
DEV_UART
typedef struct dev_uart DEV_UART
UART device interface definition.
Define uart device interface, like uart information structure, provide functions to open/close/control uart, send/receive data by uart
Note
All this details are implemented by user in user porting code
DEV_UART_INFO
typedef struct dev_uart_info DEV_UART_INFO
UART information struct definition.
informations about uart open count, working status, baudrate, uart registers and ctrl structure, uart dps format
Variable Documentation
uart_close
int32_t(* dev_uart::uart_close)(void)
Close uart device
close an uart device, just decrease the opn_cnt, if opn_cnt equals 0, then close the device
Return values
E_OK Close successfully without any issues(including scenario that device is already closed)
E_OPNED Device is still opened, the device opn_cnt decreased by 1
E_OBJ Device object is not valid
Definition at line 384 of file dev_uart.h.
Referenced by hm1x_deinit().
uart_control
int32_t(* dev_uart::uart_control)(uint32_t ctrl_cmd, void *param)
Control uart device
control an uart device by ctrl_cmd, with passed param. you can control uart device using predefined uart control commands defined using DEV_SET_SYSCMD (which must be implemented by bsp developer), such as change baudrate, flush output and more. And you can also control uart device using your own specified commands defined using DEV_SET_USRCMD, but these specified commands should be defined in your own uart device driver implementation.
Parameters
[in] ctrl_cmd control command, to change or get some thing related to uart
[in,out] param parameters that maybe argument of the command, or return values of the command
Return values
E_OK Control device successfully
E_CLSED Device is not opened
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Control device failed, due to hardware issues, such as device is disabled
E_CTX Control device failed, due to different reasons like in transfer state
E_NOSPT Control command is not supported or not valid
Definition at line 385 of file dev_uart.h.
Referenced by hm1x_read().
uart_open
int32_t(* dev_uart::uart_open)(uint32_t baud)
Open uart device
open an uart device with defined baudrate
Parameters
[in] baud initial baudrate of uart, must > 0
Return values
E_OK Open successfully without any issues
E_OPNED If device was opened before with different parameters, then just increase the opn_cnt and return E_OPNED
E_OBJ Device object is not valid
E_PAR Parameter is not valid
E_NOSPT Open settings are not supported
Definition at line 383 of file dev_uart.h.
uart_read
int32_t(* dev_uart::uart_read)(void *data, uint32_t len)
Read data from uart device(blocked)
receive data of defined len through uart(blocked).
Parameters
[out] data pointer to data need to received by uart, must not be NULL
[in] len length of data to be received, must > 0
Return values
>0 Byte count that was successfully received for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid
E_SYS Can't receive data from hardware due to hardware issues, such as device is disabled
Definition at line 387 of file dev_uart.h.
Referenced by hm1x_read().
uart_write
int32_t(* dev_uart::uart_write)(const void *data, uint32_t len)
Send data by uart device(blocked)
send data through uart with defined len(blocked).
Parameters
[in] data pointer to data need to send by uart, must not be NULL
[in] len length of data to be sent, must > 0
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid
E_SYS Can't write data to hardware due to hardware issues, such as device is disabled
Definition at line 386 of file dev_uart.h.
Referenced by hm1x_write().