embARC: EMSK SPI Flash Driver
EMSK SPI Flash Driver
BSP Layer » EMSK BSP » EMSK Peripheral Driver Module
EMSK On-board SPI Flash Driver.
Files
file spiflash.c
emsk on-board W25Q128BV spi flash driver
file spiflash.h
header file of emsk onbard W25Q128BV spi flash driver
Data Structures
struct image_t
Macros
#define SPI_LINE_SFLASH BOARD_SFLASH_SPI_LINE
#define SPI_ID_SFLASH BOARD_SFLASH_SPI_ID
#define SPI_FLASH_FREQ (BOARD_SPI_FREQ)
#define SPI_FLASH_CLKMODE (BOARD_SPI_CLKMODE)
#define SPI_FLASH_NOT_VALID (0xFFFFFFFF)
#define SPIFLASH_CHECK_EXP(EXPR, ERROR_CODE) CHECK_EXP(EXPR, ercd, ERROR_CODE, error_exit)
#define FLASH_PAGE_SIZE 0x100
#define FLASH_SECTOR_SIZE 0x1000
Functions
Inline int32_t spi_send_cmd (DEV_SPI_TRANSFER *xfer)
spi flash spi send command to operate spi flash
int32_t flash_init (void)
init spi flash related interface
int32_t flash_change_freq (uint32_t freq)
uint32_t flash_read_id (void)
read spi flash identification ID
uint32_t flash_read_status (void)
read the status of spi flash
int32_t flash_read (uint32_t address, uint32_t size, void *data)
read data from flash
int32_t flash_wait_ready (void)
Read status and wait while busy flag is set.
int32_t flash_write_enable (void)
enable to write flash
int32_t flash_erase (uint32_t address, uint32_t size)
flash erase in sectors
int32_t flash_write (uint32_t address, uint32_t size, const void *data)
write data to spi flash
Variables
static DEV_SPI * spi_flash
static uint32_t cs_flash = SPI_LINE_SFLASH
SPI Flash Commands
#define RDID 0x9F
#define RDSR 0x05
#define WRSR 0x01
#define WREN 0x06
#define WRDI 0x04
#define READ 0x03
#define SE 0x20
#define PP 0x02
Detailed Description
EMSK On-board SPI Flash Driver.
Realize driver for on-board W25Q128BV spi flash using Designware spi driver.
Macro Definition Documentation
#define PP 0x02
page program
Definition at line 70 of file spiflash.c.
Referenced by flash_write().
#define RDID 0x9F
read chip ID
Definition at line 63 of file spiflash.c.
Referenced by flash_read_id().
#define RDSR 0x05
read status register
Definition at line 64 of file spiflash.c.
Referenced by flash_read_status().
#define READ 0x03
read data bytes
Definition at line 68 of file spiflash.c.
Referenced by flash_read().
#define SE 0x20
sector erase
Definition at line 69 of file spiflash.c.
Referenced by flash_erase().
#define WRDI 0x04
write disable
Definition at line 67 of file spiflash.c.
#define WREN 0x06
write enablewaitDeviceReady
Definition at line 66 of file spiflash.c.
Referenced by flash_write_enable().
#define WRSR 0x01
write status register
Definition at line 65 of file spiflash.c.
Referenced by flash_write_enable().
Function Documentation
int32_t flash_erase (uint32_t address, uint32_t size)
flash erase in sectors
Parameters
[in] address erase start address of spi flash
[in] size erase size
Return values
-1 failed in erase operation
>=0 sector count erased
Definition at line 293 of file spiflash.c.
References DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, flash_wait_ready(), flash_write_enable(), SE, and spi_send_cmd().
int32_t flash_init (void)
init spi flash related interface
Return values
0 success
-1 fail
Definition at line 119 of file spiflash.c.
References CONV2VOID, DEV_MASTER_MODE, E_OK, SPI_CMD_MST_SET_FREQ, SPI_CMD_SET_CLK_MODE, SPI_CMD_SET_DUMMY_DATA, dev_spi::spi_control, spi_get_dev(), and dev_spi::spi_open.
int32_t flash_read (uint32_t address, uint32_t size, void * data)
read data from flash
Parameters
[in] address read start address of spi flash
[in] size read size of spi flash
[out] data data to store the return data
Return values
-1 failed in read operation
>=0 data size of data read
Definition at line 198 of file spiflash.c.
References DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, READ, and spi_send_cmd().
uint32_t flash_read_id (void)
read spi flash identification ID
Returns
the id of the spi flash
Definition at line 145 of file spiflash.c.
References DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, RDID, and spi_send_cmd().
uint32_t flash_read_status (void)
read the status of spi flash
Returns
current status of spi flash
Definition at line 170 of file spiflash.c.
References DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, RDSR, and spi_send_cmd().
Referenced by flash_wait_ready(), and flash_write_enable().
int32_t flash_wait_ready (void)
Read status and wait while busy flag is set.
Return values
0 success
-1 fail
Definition at line 225 of file spiflash.c.
References flash_read_status().
Referenced by flash_erase(), and flash_write().
int32_t flash_write (uint32_t address, uint32_t size, const void * data)
write data to spi flash
Parameters
[in] address start address
[in] size data size
[in] data pointer to data
Return values
>=0 written bytes number
<0 error
Definition at line 348 of file spiflash.c.
References DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, flash_wait_ready(), flash_write_enable(), PP, and spi_send_cmd().
int32_t flash_write_enable (void)
enable to write flash
Return values
0 success
-1 fail
Definition at line 242 of file spiflash.c.
References DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, flash_read_status(), spi_send_cmd(), WREN, and WRSR.
Referenced by flash_erase(), and flash_write().
Inline int32_t spi_send_cmd (DEV_SPI_TRANSFER * xfer)
spi flash spi send command to operate spi flash
Parameters
[in] xfer spi transfer that need to transfer to spi device
Return values
0 success
-1 fail
Definition at line 92 of file spiflash.c.
References CONV2VOID, cpu_lock_save(), cpu_unlock_restore(), E_OK, SPI_CMD_MST_DSEL_DEV, SPI_CMD_MST_SEL_DEV, SPI_CMD_TRANSFER_POLLING, and dev_spi::spi_control.
Referenced by flash_erase(), flash_read(), flash_read_id(), flash_read_status(), flash_write(), and flash_write_enable().