embARC: DesignWare SPI Function Declaration
DesignWare SPI Function Declaration
Device HAL » Device HAL Implementation » Designware Device Driver » Designware SPI Driver
contains declarations of designware spi functions.
Functions
int32_t dw_spi_open (DEV_SPI *spi_obj, uint32_t mode, uint32_t param)
open a designware spi device
int32_t dw_spi_close (DEV_SPI *spi_obj)
close a DesignWare SPI device
int32_t dw_spi_control (DEV_SPI *spi_obj, uint32_t ctrl_cmd, void *param)
control spi by ctrl command
int32_t dw_spi_write (DEV_SPI *spi_obj, const void *data, uint32_t len)
send data through DesignWare SPI
int32_t dw_spi_read (DEV_SPI *spi_obj, void *data, uint32_t len)
read data through DesignWare SPI
void dw_spi_isr (DEV_SPI *spi_obj, void *ptr)
DesignWare SPI interrupt processing routine.
Detailed Description
contains declarations of designware spi functions.
This are only used in dw_spi_obj.c
Function Documentation
int32_t dw_spi_close (DEV_SPI * spi_obj)
close a DesignWare SPI device
Parameters
[in] spi_obj spi object pointer
Return values
E_OK Close successfully without any issues(including scenario that device is already closed)
E_OPNED Device is still opened, the device opn_cnt decreased by 1
E_OBJ Device object is not valid
Definition at line 919 of file dw_spi.c.
References DEV_DISABLED, dw_spi_abort_rx(), dw_spi_abort_tx(), DW_SPI_CHECK_EXP, dw_spi_disable_device(), dw_spi_disable_interrupt(), dw_spi_ctrl::dw_xfer, E_OK, E_OPNED, dev_spi_info::extra, dev_spi_info::opn_cnt, dev_spi_info::spi_cbs, dev_spi_info::spi_ctrl, dev_spi::spi_info, dev_spi_info::status, VALID_CHK_SPI_INFO_OBJECT, and dev_spi_info::xfer.
Referenced by dw_spi_0_close(), dw_spi_1_close(), and dw_spi_2_close().
int32_t dw_spi_control (DEV_SPI * spi_obj, uint32_t ctrl_cmd, void * param)
control spi by ctrl command
Parameters
[in] spi_obj spi object pointer
[in] ctrl_cmd control command code to do specific spi work
[in,out] param parameters used to control spi or return something
Return values
E_OK Control device successfully
E_CLSED Device is not opened
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Control device failed, due to hardware issues, such as device is disabled
E_CTX Control device failed, due to different reasons like in transfer state
E_NOSPT Control command is not supported or not valid
Definition at line 963 of file dw_spi.c.
References dev_buffer::buf, CHECK_ALIGN_4BYTES, dev_spi_info::clk_mode, DEV_ENABLED, DEV_IN_XFER, DEV_MASTER_MODE, DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, dev_spi_info::dfs, dev_spi_info::dummy, dw_spi_abort_rx(), dw_spi_abort_tx(), dw_spi_abort_xfer(), DW_SPI_CHECK_EXP, dw_spi_deselect_slave(), dw_spi_dis_cbr(), dw_spi_disable_device(), dw_spi_ena_cbr(), dw_spi_enable_device(), dw_spi_get_rxavail(), dw_spi_get_txavail(), DW_SPI_RDY_RCV, DW_SPI_RDY_SND, DW_SPI_RDY_XFER, dw_spi_ctrl::dw_spi_regs, dw_spi_select_slave(), dw_spi_set_clockmode(), dw_spi_set_dfs(), dw_spi_set_freq(), E_CLSED, E_CTX, E_NOSPT, E_OK, E_PAR, E_SYS, dev_spi_cbs::err_cb, dev_spi_info::freq, dev_buffer::len, dev_spi_info::mode, dev_spi_info::opn_cnt, dev_spi_cbs::rx_cb, dev_spi_info::slave, dev_spi_info::spi_cbs, SPI_CMD_ABORT_RX, SPI_CMD_ABORT_TX, SPI_CMD_ABORT_XFER, SPI_CMD_DIS_DEV, SPI_CMD_ENA_DEV, SPI_CMD_FLUSH_RX, SPI_CMD_FLUSH_TX, SPI_CMD_GET_RXAVAIL, SPI_CMD_GET_STATUS, SPI_CMD_GET_TXAVAIL, SPI_CMD_MST_DSEL_DEV, SPI_CMD_MST_SEL_DEV, SPI_CMD_MST_SET_FREQ, SPI_CMD_RESET, SPI_CMD_SET_CLK_MODE, SPI_CMD_SET_DFS, SPI_CMD_SET_DUMMY_DATA, SPI_CMD_SET_ERRCB, SPI_CMD_SET_RXCB, SPI_CMD_SET_RXINT, SPI_CMD_SET_RXINT_BUF, SPI_CMD_SET_TXCB, SPI_CMD_SET_TXINT, SPI_CMD_SET_TXINT_BUF, SPI_CMD_SET_XFERCB, SPI_CMD_TRANSFER_INT, SPI_CMD_TRANSFER_POLLING, SPI_CPOL_0_CPHA_0, SPI_CPOL_1_CPHA_1, dev_spi_info::spi_ctrl, dev_spi::spi_info, SPI_SLAVE_NOT_SELECTED, dev_spi_info::status, dev_spi_cbs::tx_cb, VALID_CHK_SPI_INFO_OBJECT, dev_spi_info::xfer, and dev_spi_cbs::xfer_cb.
Referenced by dw_spi_0_control(), dw_spi_1_control(), and dw_spi_2_control().
void dw_spi_isr (DEV_SPI * spi_obj, void * ptr)
DesignWare SPI interrupt processing routine.
Parameters
[in] spi_info_ptr DEV_SPI_INFO *spi_info_ptr
[in] ptr extra information
Definition at line 1289 of file dw_spi.c.
References dw_spi_clear_interrupt_all(), dw_spi_dis_cbr(), dw_spi_disable_interrupt(), DW_SPI_IMR_RXOIM, DW_SPI_IMR_RXUIM, DW_SPI_IMR_TXEIM, DW_SPI_IMR_TXOIM, DW_SPI_IN_RX, DW_SPI_IN_TX, DW_SPI_IN_XFER, DW_SPI_RDY_RCV, DW_SPI_RDY_SND, DW_SPI_RDY_XFER, dw_spi_ctrl::dw_spi_regs, dw_spi_xfer_end(), dw_spi_ctrl::dw_xfer, E_OK, dev_spi_cbs::err_cb, dev_spi_cbs::rx_cb, dev_spi_info::spi_cbs, dev_spi_info::spi_ctrl, dev_spi::spi_info, dev_spi_info::status, dev_spi_cbs::tx_cb, VALID_CHK_SPI_INFO_OBJECT, and dev_spi_cbs::xfer_cb.
Referenced by dw_spi_0_isr(), dw_spi_1_isr(), and dw_spi_2_isr().
int32_t dw_spi_open (DEV_SPI * spi_obj, uint32_t mode, uint32_t param)
open a designware spi device
Parameters
[in] spi_obj spi object pointer
[in] mode spi working mode (master or slave)
[in] param parameter, for master, param is the freq, for slave, param is dfs
Return values
E_OK Open successfully without any issues
E_OPNED If device was opened before with different parameters, then just increase the opn_cnt and return E_OPNED
E_OBJ Device object is not valid
E_SYS Device is opened for different mode before, if you want to open it with different mode, you need to fully close it first.
E_PAR Parameter is not valid
E_NOSPT Open settings are not supported
Definition at line 825 of file dw_spi.c.
References dev_spi_info::clk_mode, DEV_ENABLED, DEV_MASTER_MODE, DEV_SLAVE_MODE, dev_spi_info::dfs, dev_spi_info::dummy, DW_SPI_CHECK_EXP, dw_spi_deselect_slave(), dw_spi_disable_interrupt(), dw_spi_get_rxfifo_len(), dw_spi_get_txfifo_len(), dw_spi_hw_init(), dw_spi_ctrl::dw_spi_int_handler, DW_SPI_MASTER_SUPPORTED, dw_spi_ctrl::dw_spi_regs, dw_spi_set_freq(), DW_SPI_SLAVE_SUPPORTED, E_NOSPT, E_OK, E_OPNED, E_PAR, E_SYS, dev_spi_info::extra, dev_spi_info::freq, int_handler_install(), dw_spi_ctrl::int_status, dw_spi_ctrl::intno, dev_spi_info::mode, dev_spi_info::opn_cnt, dw_spi_ctrl::rx_fifo_len, dev_spi_info::slave, dev_spi_info::spi_cbs, SPI_CPOL_0_CPHA_0, SPI_CPOL_1_CPHA_1, dev_spi_info::spi_ctrl, SPI_DFS_DEFAULT, dev_spi::spi_info, SPI_SLAVE_NOT_SELECTED, dev_spi_info::status, dw_spi_ctrl::support_modes, dw_spi_ctrl::tx_fifo_len, VALID_CHK_SPI_INFO_OBJECT, and dev_spi_info::xfer.
Referenced by dw_spi_0_open(), dw_spi_1_open(), and dw_spi_2_open().
int32_t dw_spi_read (DEV_SPI * spi_obj, void * data, uint32_t len)
read data through DesignWare SPI
Parameters
[in] spi_info_ptr spi information structure pointer
[out] data data that need to read (data must be char type)
[in] len data count need to read
Return values
>=0 data have been read
E_PAR arguments passed was wrong
E_OBJ spi has something error, nothing can be done
E_CLSED spi was closed, not available for control
<0 other error code not defined here
Definition at line 1251 of file dw_spi.c.
References DEV_ENABLED, DEV_IN_XFER, DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, dev_spi_info::dfs, DW_SPI_CHECK_EXP, E_CLSED, E_CTX, E_OK, E_PAR, E_SYS, dev_spi_info::opn_cnt, dev_spi_info::spi_ctrl, dev_spi::spi_info, dev_spi_info::status, and VALID_CHK_SPI_INFO_OBJECT.
Referenced by dw_spi_0_read(), dw_spi_1_read(), and dw_spi_2_read().
int32_t dw_spi_write (DEV_SPI * spi_obj, const void * data, uint32_t len)
send data through DesignWare SPI
Parameters
[in] spi_obj spi object pointer
[in] data pointer to data need to send by spi
[in] len length of data to be sent
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid
E_CTX Device is still in transfer state
E_SYS Can't write data to hardware due to hardware issues, such as device is disabled
Definition at line 1207 of file dw_spi.c.
References DEV_ENABLED, DEV_IN_XFER, DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, dev_spi_info::dfs, DW_SPI_CHECK_EXP, E_CLSED, E_CTX, E_OK, E_PAR, E_SYS, dev_spi_info::opn_cnt, dev_spi_info::spi_ctrl, dev_spi::spi_info, dev_spi_info::status, and VALID_CHK_SPI_INFO_OBJECT.
Referenced by dw_spi_0_write(), dw_spi_1_write(), and dw_spi_2_write().