embARC: embARC FreeRTOS kernel example with secureshield
embARC FreeRTOS kernel example with secureshield
embARC Applications » All embARC ApplicationsembARC Applications » embARC Applications for Different Operating Systems » | embARC Baremetal Applications
Test FreeRTOS working with secureshield runtime.
Files
file freertos/kernel_secure/background_container.c
main source of this example
file freertos/kernel_secure/background_container.h
background container head file
file freertos/kernel_secure/container1.c
freertos kernel secure example container1 source file
file freertos/kernel_secure/container1.h
freertos kernel secure example container1 head file
file freertos/kernel_secure/container2.c
freertos kernel secure example container2 source file
file freertos/kernel_secure/container2.h
freertos kernel secure example container2 head file
file freertos/kernel_secure/container_cfg.c
freertos kernel secure example container configuration file
Functions
static void task1 (void *par)
task1 in FreeRTOS
static void task2 (void *par)
task2 in FreeRTOS
static void interrupt_high_pri (void *p_excinf)
high priority interrupt
static void interrupt_low_pri (void *p_exinf)
low priority interrupt
static void perf_init (unsigned int id)
performance timer initialization
static void perf_start (void)
performance timer start
static unsigned int perf_end (void)
performance timer end, and return the time passed
void default_interrupt_handler (void *p_exinf)
int main (void)
call FreeRTOS API, create and start tasks
Variables
static TaskHandle_t task1_handle = NULL
handle of task1
static TaskHandle_t task2_handle = NULL
handle of task2
static volatile unsigned int start = 0
static unsigned int perf_id = 0xFF
static unsigned int t_int_t2
static unsigned int t_t2_t1
static unsigned int t_t1_int
static unsigned int t_int_nest
static unsigned int t_nest_int
static uint8_t public_data [SECRET_LEN]
Detailed Description
Test FreeRTOS working with secureshield runtime.
Extra Required Tools
Extra Required Peripherals
Design Concept
This example is designed to show how FreeRTOS is integrated with SecureShield. Here, trap_s is used to trigger a task context switch request. So application should not use trap exception.
As container switch is not with task switch. So during a container call, task scheduler should be suspended to avoid a task context.
Usage Manual
Here we take EMSK 2.3 EM7D for example, you can run the program using Metaware toolset.
Re-configure the EMSK 2.3 board to EM7D configuration.
Command: gmake BOARD=emsk BD_VER=23 CUR_CORE=arcem7d run
Running screenshot as follows
ScreenShot for FreeRTOS kernel with secureshield in embARC
Extra Comments
Function Documentation
static void interrupt_high_pri (void * p_excinf) static
high priority interrupt
Call xTaskResumeFromISR() to resume task2 that can be called from within ISR. If resuming the task2 should result in a context switch, call vPortYieldFromIsr() to generate task switch request.
Parameters
[in] *p_excinf
Definition at line 259 of file freertos/kernel_secure/background_container.c.
References perf_end(), perf_start(), and task2_handle.
Referenced by main().
static void interrupt_low_pri (void * p_exinf) static
low priority interrupt
write AUX_IRQ_HINT to raise higher priority interrtupt.
Parameters
[in] *p_excinf
Definition at line 274 of file freertos/kernel_secure/background_container.c.
References AUX_IRQ_HINT, perf_end(), and perf_start().
Referenced by main().
static void task1 (void * par) static
task1 in FreeRTOS
Call vTaskDelayUntil() to execute task1 with a fixed period 1 second.
Parameters
[in] *par
Definition at line 198 of file freertos/kernel_secure/background_container.c.
References AUX_IRQ_HINT, perf_end(), and perf_start().
Referenced by main().
static void task2 (void * par) static
task2 in FreeRTOS
Print information in task2 and suspend task2.
Parameters
[in] *par
Definition at line 228 of file freertos/kernel_secure/background_container.c.
References perf_end(), perf_init(), perf_start(), and TIMER_1.
Referenced by main().
Variable Documentation
task1_handle = NULL static
handle of task1
If task handle is not used, set Null.
Definition at line 89 of file freertos/kernel_secure/background_container.c.
Referenced by main().
task2_handle = NULL static
handle of task2
If task handle is not used, set Null.
Definition at line 95 of file freertos/kernel_secure/background_container.c.
Referenced by interrupt_high_pri(), and main().