embARC: SPI Device HAL Interface
SPI Device HAL Interface
Device HAL » Device HAL Definition
definitions for spi device hardware layer (dev_spi.h)
Modules
SPI Clock Mode
spi clock mode settings
SPI Device Control Commands
Definitions for spi control command, used in SPI IO Control.
SPI Device Structure
contains definitions of spi device structure.
SPI Interrupt callback functions
callback function structure for SPI device
SPI Slave Select Line
spi slave select line definition
Files
file dev_spi.h
spi device hardware layer definitions
Functions
DEV_SPI_PTR spi_get_dev (int32_t spi_id)
get an spi device by spi device id.
Detailed Description
definitions for spi device hardware layer (dev_spi.h)
provide interfaces for spi driver to implement Here is a diagram for the spi interface.
SPI Device HAL Interface Diagram
Function Documentation
spi_get_dev()
DEV_SPI_PTR spi_get_dev (int32_t spi_id)
get an spi device by spi device id.
For how to use spi device hal refer to Functions in spi device structure
Parameters
[in] spi_id id of spi, defined by user
Return values
!NULL pointer to an spi device structure
NULL failed to find the spi device by spi_id
Note
need to implemented by user in user code
get an spi device by spi device id.
Definition at line 275 of file emsk/drivers/ip/designware/spi/dw_spi_obj.c.
References dw_spi_0, DW_SPI_0_ID, dw_spi_1, DW_SPI_1_ID, dw_spi_2, DW_SPI_2_ID, and dw_spi_all_install().
Referenced by rw009_deselect(), and rw009_select().