embARC: DesignWare UART Driver Static Functions
DesignWare UART Driver Static Functions
Device HAL » Device HAL Implementation » Designware Device Driver » Designware UART Driver
Static or inline functions, variables for DesignWare UART handle uart operations, only used in this file.
Functions
Inline int32_t dw_uart_putready (DW_UART_REG *uart_reg_ptr)
test whether uart is ready to send, 1 ready, 0 not ready
Inline int32_t dw_uart_getready (DW_UART_REG *uart_reg_ptr)
test whether uart is ready to receive, 1 ready, 0 not ready
Inline void dw_uart_putchar (DW_UART_REG *uart_reg_ptr, char chr)
write char to uart send fifo
Inline int32_t dw_uart_getchar (DW_UART_REG *uart_reg_ptr)
read data from uart receive fifo, return data received
Inline int32_t dw_uart_snd_chr (DW_UART_REG *uart_reg_ptr, char chr)
send char by uart when available, mostly used in interrupt method, non-blocked function
Inline int32_t dw_uart_rcv_chr (DW_UART_REG *uart_reg_ptr)
receive one char from uart, mostly used in interrupt routine, non-blocked function
Inline void dw_uart_psnd_chr (DW_UART_REG *uart_reg_ptr, char chr)
send char by uart in poll method, blocked function
Inline int32_t dw_uart_prcv_chr (DW_UART_REG *uart_reg_ptr)
receive one char from uart in poll method, blocked function
Inline uint32_t dw_uart_get_txfifo_len (DW_UART_REG *uart_reg_ptr)
Get TX FIFO Length.
Inline uint32_t dw_uart_get_rxfifo_len (DW_UART_REG *uart_reg_ptr)
Get RX FIFO Length.
static int32_t dw_uart_set_dps (DW_UART_REG *uart_reg_ptr, UART_DPS_FORMAT *dps)
set designware uart DPS value
static void dw_uart_set_baud (DW_UART_REG *uart_reg_ptr, uint32_t baud_divisor)
set designware uart baudrate
Inline void dw_uart_software_reset (DW_UART_REG *uart_reg_ptr)
Do uart software reset.
static void dw_uart_set_hwfc (DW_UART_REG *uart_reg_ptr, UART_HW_FLOW_CONTROL hwfc)
set designware uart baudrate
Inline void dw_uart_set_break (DW_UART_REG *uart_reg_ptr)
Inline void dw_uart_clr_break (DW_UART_REG *uart_reg_ptr)
static void dw_uart_init (DW_UART_REG *uart_reg_ptr, uint32_t baud_divisor, UART_DPS_FORMAT *dps, UART_HW_FLOW_CONTROL hwfc)
init designware uart with selected baud
static void dw_uart_flush_output (DEV_UART_INFO *uart_info_ptr)
set designware uart baudrate
static void dw_uart_dis_cbr (DEV_UART_INFO *uart_info_ptr, uint32_t cbrtn)
disable designware uart send or receive interrupt
static void dw_uart_ena_cbr (DEV_UART_INFO *uart_info_ptr, uint32_t cbrtn)
enable DesignWare UART send or receive interrupt
static void dw_uart_enable_interrupt (DEV_UART_INFO *uart_info_ptr)
enable designware uart interrupt
static void dw_uart_disable_interrupt (DEV_UART_INFO *uart_info_ptr)
disable designware uart interrupt
static void dw_uart_enable_device (DEV_UART_INFO *uart_info_ptr)
enable designware uart
static void dw_uart_disable_device (DEV_UART_INFO *uart_info_ptr)
disable designware uart
static void dw_uart_abort_tx (DEV_UART *uart_obj)
abort current interrupt transmit transfer
static void dw_uart_abort_rx (DEV_UART *uart_obj)
abort current interrupt receive transfer
static int32_t dw_uart_get_txavail (DW_UART_CTRL *uart_ctrl_ptr)
Get available transmit fifo count.
static int32_t dw_uart_get_rxavail (DW_UART_CTRL *uart_ctrl_ptr)
Get available receive fifo count.
Variables
const uint8_t dw_uart_databits []
const uint8_t dw_uart_parity []
const uint8_t dw_uart_stopbits []
Detailed Description
Static or inline functions, variables for DesignWare UART handle uart operations, only used in this file.
Function Documentation
static void dw_uart_dis_cbr (DEV_UART_INFO * uart_info_ptr, uint32_t cbrtn) static
disable designware uart send or receive interrupt
Parameters
[in] DEV_UART_INFO *uart_info_ptr
[in] cbrtn control code of callback routine of send or receive
Definition at line 346 of file dw_uart.c.
References DW_UART_GINT_ENABLE, DW_UART_RDY_RCV, DW_UART_RDY_SND, dw_uart_ctrl::dw_uart_regbase, DW_UART_RXINT_ENABLE, DW_UART_TXINT_ENABLE, int_disable(), dw_uart_ctrl::int_status, dw_uart_ctrl::intno, and dev_uart_info::uart_ctrl.
Referenced by dw_uart_abort_rx(), dw_uart_abort_tx(), dw_uart_control(), dw_uart_disable_interrupt(), and dw_uart_isr().
static void dw_uart_disable_interrupt (DEV_UART_INFO * uart_info_ptr) static
disable designware uart interrupt
Parameters
uart_info_ptr uart information structure pointer
Definition at line 417 of file dw_uart.c.
References dw_uart_dis_cbr(), DW_UART_GINT_ENABLE, DW_UART_RDY_RCV, DW_UART_RDY_SND, DW_UART_RXINT_ENABLE, DW_UART_TXINT_ENABLE, int_disable(), dw_uart_ctrl::int_status, dw_uart_ctrl::intno, and dev_uart_info::uart_ctrl.
Referenced by dw_uart_close(), and dw_uart_open().
static void dw_uart_ena_cbr (DEV_UART_INFO * uart_info_ptr, uint32_t cbrtn) static
enable DesignWare UART send or receive interrupt
Parameters
[in] DEV_UART_INFO *uart_info_ptr
[in] cbrtn control code of callback routine of send or receive
Definition at line 376 of file dw_uart.c.
References DW_UART_GINT_ENABLE, DW_UART_RDY_RCV, DW_UART_RDY_SND, dw_uart_ctrl::dw_uart_regbase, DW_UART_RXINT_ENABLE, DW_UART_TXINT_ENABLE, int_enable(), dw_uart_ctrl::int_status, dw_uart_ctrl::intno, and dev_uart_info::uart_ctrl.
Referenced by dw_uart_control().
static void dw_uart_enable_interrupt (DEV_UART_INFO * uart_info_ptr) static
enable designware uart interrupt
Parameters
uart_info_ptr uart information structure pointer
Definition at line 405 of file dw_uart.c.
References DW_UART_GINT_ENABLE, dw_uart_ctrl::dw_uart_int_handler, int_enable(), int_handler_install(), dw_uart_ctrl::int_status, dw_uart_ctrl::intno, and dev_uart_info::uart_ctrl.
static void dw_uart_flush_output (DEV_UART_INFO * uart_info_ptr) static
set designware uart baudrate
Parameters
uart_info_ptr uart information structure pointer
Definition at line 318 of file dw_uart.c.
References dev_buffer::buf, dw_uart_psnd_chr(), dw_uart_ctrl::dw_uart_regbase, dev_buffer::len, dev_buffer::ofs, dev_uart_info::tx_buf, and dev_uart_info::uart_ctrl.
Referenced by dw_uart_close(), and dw_uart_control().
static void dw_uart_init (DW_UART_REG * uart_reg_ptr, uint32_t baud_divisor, UART_DPS_FORMAT * dps, UART_HW_FLOW_CONTROL hwfc) static
init designware uart with selected baud
Parameters
[in] uart_reg_ptr uart register structure pointer
[in] baud_divisor baudrate divisor
Definition at line 302 of file dw_uart.c.
References dw_uart_set_baud(), dw_uart_set_dps(), dw_uart_set_hwfc(), and dw_uart_software_reset().
Referenced by dw_uart_open().
Inline int32_t dw_uart_prcv_chr (DW_UART_REG * uart_reg_ptr)
receive one char from uart in poll method, blocked function
Parameters
[in] uart_reg_ptr uart register structure pointer
Returns
data received by the uart
Definition at line 169 of file dw_uart.c.
References dw_uart_getchar(), and dw_uart_getready().
Referenced by dw_uart_read().
Inline void dw_uart_psnd_chr (DW_UART_REG * uart_reg_ptr, char chr)
send char by uart in poll method, blocked function
Parameters
[in] uart_reg_ptr uart register structure pointer
[in] chr char to be sent
Definition at line 157 of file dw_uart.c.
References dw_uart_putchar(), and dw_uart_putready().
Referenced by dw_uart_flush_output(), and dw_uart_write().
Inline int32_t dw_uart_rcv_chr (DW_UART_REG * uart_reg_ptr)
receive one char from uart, mostly used in interrupt routine, non-blocked function
Parameters
[in] uart_reg_ptr uart register structure pointer
Returns
data received by the uart
Definition at line 148 of file dw_uart.c.
References dw_uart_getchar().
static void dw_uart_set_baud (DW_UART_REG * uart_reg_ptr, uint32_t baud_divisor) static
set designware uart baudrate
Parameters
uart_reg_ptr uart register structure
baud_divisor uart baudrate divisor
Definition at line 245 of file dw_uart.c.
Referenced by dw_uart_control(), dw_uart_disable_device(), dw_uart_enable_device(), and dw_uart_init().
static int32_t dw_uart_set_dps (DW_UART_REG * uart_reg_ptr, UART_DPS_FORMAT * dps) static
set designware uart DPS value
Parameters
uart_reg_ptr uart register structure
dps data bits/parity bit/stop bits parameter
Return values
0 Set ok
!0 Set failed
Definition at line 216 of file dw_uart.c.
References uart_dps_format::databits, uart_dps_format::parity, uart_dps_format::stopbits, UART_PARITY_SPACE, and UART_STPBITS_TWO.
Referenced by dw_uart_control(), and dw_uart_init().
static void dw_uart_set_hwfc (DW_UART_REG * uart_reg_ptr, UART_HW_FLOW_CONTROL hwfc) static
set designware uart baudrate
Parameters
uart_reg_ptr uart register structure
hwfc uart hardware flow control type
Note
Need to set corresponding pin functions
Definition at line 274 of file dw_uart.c.
References UART_FC_BOTH, UART_FC_CTS, UART_FC_NONE, and UART_FC_RTS.
Referenced by dw_uart_control(), and dw_uart_init().
Inline int32_t dw_uart_snd_chr (DW_UART_REG * uart_reg_ptr, char chr)
send char by uart when available, mostly used in interrupt method, non-blocked function
Parameters
[in] uart_reg_ptr uart register structure pointer
[in] chr char to be sent
Return values
0 send successfully
-1 not ready to send data
Definition at line 134 of file dw_uart.c.
References dw_uart_putchar(), and dw_uart_putready().
Inline void dw_uart_software_reset (DW_UART_REG * uart_reg_ptr)
Do uart software reset.
Parameters
uart_reg_ptr uart register structure
Definition at line 262 of file dw_uart.c.
Referenced by dw_uart_init().
Variable Documentation
const uint8_t dw_uart_databits[]
Initial value:
= {
        DW_UART_LCR_WORD_LEN5, DW_UART_LCR_WORD_LEN6,
        DW_UART_LCR_WORD_LEN7, DW_UART_LCR_WORD_LEN8}
Definition at line 93 of file dw_uart.c.
const uint8_t dw_uart_parity[]
Initial value:
= {
        DW_UART_LCR_PARITY_NONE, DW_UART_LCR_PARITY_ODD,
        DW_UART_LCR_PARITY_EVEN, DW_UART_LCR_PARITY_MASK,
        DW_UART_LCR_PARITY_SPACE
}
Definition at line 96 of file dw_uart.c.
const uint8_t dw_uart_stopbits[]
Initial value:
= {
        DW_UART_LCR_1_STOP_BIT, DW_UART_LCR_1D5_STOP_BIT,
        DW_UART_LCR_2_STOP_BIT
}
Definition at line 101 of file dw_uart.c.