embARC: EMSK DW IIC Object
EMSK DW IIC Object
BSP Layer » EMSK BSP » EMSK Peripheral Driver Module
EMSK Designware IIC Objects.
Files
file dw_iic_obj.c
designware iic object instantiation on emsk
file dw_iic_obj.h
header file of designware iic object instantiation on emsk
Macros
#define PERIPHERAL_BASE _arc_aux_read(AUX_DMP_PERIPHERAL)
Functions
DEV_IIC_PTR iic_get_dev (int32_t iic_id)
get one designware device structure
void dw_iic_all_install (void)
install all iic objects
EMSK DesignWare IIC 0 Object Instantiation
DEV_IIC dw_iic_0
DW_IIC_CTRL dw_iic_0_ctrl
static void dw_iic_0_isr (void *ptr)
designware iic 0 interrupt routine
static int32_t dw_iic_0_open (uint32_t mode, uint32_t param)
designware iic 0 open
static int32_t dw_iic_0_close (void)
designware iic 0 close
static int32_t dw_iic_0_control (uint32_t ctrl_cmd, void *param)
designware iic 0 control
static int32_t dw_iic_0_write (const void *data, uint32_t len)
designware iic 0 write
static int32_t dw_iic_0_read (void *data, uint32_t len)
designware iic 0 close
static void dw_iic_0_install (void)
install designware iic 0 to system
#define DW_IIC_0_RELBASE (REL_REGBASE_I2C0)
#define DW_IIC_0_INTNO (INTNO_I2C0)
#define DW_IIC_0_SLVADDR (0x55)
#define DW_IIC_0_TX_FIFO_LEN (32)
#define DW_IIC_0_RX_FIFO_LEN (32)
#define DW_IIC_0_MASTER_CODE (0)
#define DW_IIC_0_TARADDR (0x55)
EMSK DesignWare IIC 1 Object Instantiation
DEV_IIC dw_iic_1
DW_IIC_CTRL dw_iic_1_ctrl
static void dw_iic_1_isr (void *ptr)
designware iic 1 interrupt routine
static int32_t dw_iic_1_open (uint32_t mode, uint32_t param)
designware iic 1 open
static int32_t dw_iic_1_close (void)
designware iic 1 close
static int32_t dw_iic_1_control (uint32_t ctrl_cmd, void *param)
designware iic 1 control
static int32_t dw_iic_1_write (const void *data, uint32_t len)
designware iic 1 write
static int32_t dw_iic_1_read (void *data, uint32_t len)
designware iic 1 close
static void dw_iic_1_install (void)
install designware iic 1 to system
#define DW_IIC_1_RELBASE (REL_REGBASE_I2C1)
#define DW_IIC_1_INTNO (INTNO_I2C1)
#define DW_IIC_1_SLVADDR (0x56)
#define DW_IIC_1_TX_FIFO_LEN (32)
#define DW_IIC_1_RX_FIFO_LEN (32)
#define DW_IIC_1_MASTER_CODE (1)
#define DW_IIC_1_TARADDR (0x56)
DesignWare IIC Object Number
#define DW_IIC_NUM (1)
Designware IIC Object ID Macros
#define DW_IIC_0_ID 0
#define DW_IIC_1_ID 1
Designware IIC Object Control Macros
#define USE_DW_IIC_0 1
#define USE_DW_IIC_1 1
Detailed Description
EMSK Designware IIC Objects.
Realize the EMSK board iic object using designware iic device driver, only need to realize some designware iic structures combine with EMSK iic hardware resource. just like cpp class instantiation.
Macro Definition Documentation
#define DW_IIC_0_ID 0
iic 0 id macro
Definition at line 59 of file dw_iic_obj.h.
Referenced by iic_get_dev().
#define DW_IIC_0_INTNO (INTNO_I2C0)
designware iic 0 interrupt number
Definition at line 79 of file dw_iic_obj.c.
Referenced by dw_iic_0_install().
#define DW_IIC_0_RELBASE (REL_REGBASE_I2C0)
designware iic 0 relative baseaddr
Definition at line 78 of file dw_iic_obj.c.
Referenced by dw_iic_0_install().
#define DW_IIC_0_SLVADDR (0x55)
iic 0 slave address working in slave mode
Definition at line 80 of file dw_iic_obj.c.
#define DW_IIC_1_ID 1
iic 1 id macro
Definition at line 60 of file dw_iic_obj.h.
Referenced by iic_get_dev().
#define DW_IIC_1_INTNO (INTNO_I2C1)
designware iic 1 interrupt number
Definition at line 173 of file dw_iic_obj.c.
Referenced by dw_iic_1_install().
#define DW_IIC_1_RELBASE (REL_REGBASE_I2C1)
designware iic 1 relative baseaddr
Definition at line 172 of file dw_iic_obj.c.
Referenced by dw_iic_1_install().
#define DW_IIC_1_SLVADDR (0x56)
iic 1 slave address working in slave mode
Definition at line 174 of file dw_iic_obj.c.
#define DW_IIC_NUM (1)
DesignWare IIC valid number
Definition at line 52 of file dw_iic_obj.h.
#define USE_DW_IIC_0 1
enable use designware iic 0
Definition at line 67 of file dw_iic_obj.h.
#define USE_DW_IIC_1 1
enable use designware iic 1
Definition at line 68 of file dw_iic_obj.h.
Function Documentation
void dw_iic_all_install (void)
install all iic objects
Note
MUST be called during system init
Definition at line 292 of file dw_iic_obj.c.
References dw_iic_0_install(), and dw_iic_1_install().
Referenced by iic_get_dev().
DEV_IIC_PTR iic_get_dev (int32_t iic_id)
get one designware device structure
get an iic device by iic device id.
Definition at line 261 of file dw_iic_obj.c.
References dw_iic_0, DW_IIC_0_ID, dw_iic_1, DW_IIC_1_ID, and dw_iic_all_install().
Referenced by adt7420_reg_read(), adt7420_reg_write(), temp_sensor_init(), and temp_sensor_read().
Variable Documentation
DEV_IIC dw_iic_0
designware iic object
Definition at line 86 of file dw_iic_obj.c.
Referenced by dw_iic_0_install(), and iic_get_dev().
DW_IIC_CTRL dw_iic_0_ctrl
designware iic 0 ctrl
Definition at line 87 of file dw_iic_obj.c.
Referenced by dw_iic_0_install().
DEV_IIC dw_iic_1
designware iic 1 object
Definition at line 180 of file dw_iic_obj.c.
Referenced by dw_iic_1_install(), and iic_get_dev().
DW_IIC_CTRL dw_iic_1_ctrl
designware iic 1 ctrl
Definition at line 181 of file dw_iic_obj.c.
Referenced by dw_iic_1_install().