embARC: DesignWare SPI Driver Static Functions
DesignWare SPI Driver Static Functions
Device HAL » Device HAL Implementation » Designware Device Driver » Designware SPI Driver
Static or inline functions, variables for DesignWare SPI handle spi operations, only used in this file.
Functions
Inline void dw_spi_disable (DW_SPI_REG *spi_reg_ptr)
Disable designware spi device.
Inline void dw_spi_enable (DW_SPI_REG *spi_reg_ptr)
Enable designware spi device.
Inline void dw_spi_clear_interrupt_all (DW_SPI_REG *spi_reg_ptr)
Clear all designware spi interrupt.
Inline int32_t dw_spi_busy (DW_SPI_REG *spi_reg_ptr)
test whether spi is busy, busy return 1, else 0
Inline int32_t dw_spi_putready (DW_SPI_REG *spi_reg_ptr)
test whether spi is ready to send, 1 ready, 0 not ready
Inline int32_t dw_spi_getready (DW_SPI_REG *spi_reg_ptr)
test whether spi is read to receive, 1 ready, 0 not ready
Inline void dw_spi_putdata (DW_SPI_REG *spi_reg_ptr, int32_t data)
write data to spi send fifo
Inline int32_t dw_spi_getdata (DW_SPI_REG *spi_reg_ptr)
read data from spi receive fifo, return data received
Inline int32_t dw_spi_snd_dat (DW_SPI_REG *spi_reg_ptr, int32_t data)
send data by spi when available, mostly used in interrupt method, non-blocked function
Inline int32_t dw_spi_rcv_dat (DW_SPI_REG *spi_reg_ptr)
receive one char from spi, mostly used in interrupt routine, non-blocked function
Inline void dw_spi_psnd_dat (DW_SPI_REG *spi_reg_ptr, int32_t data)
send char by spi in poll method, blocked function
Inline int32_t dw_spi_prcv_dat (DW_SPI_REG *spi_reg_ptr)
receive one char from spi in poll method, blocked function
Inline void dw_spi_reset_fifo (DW_SPI_REG *spi_reg_ptr)
Reset designware FIFO by disable spi device, then enable device.
Inline void dw_spi_unmask_interrupt (DW_SPI_REG *spi_reg_ptr, uint32_t mask)
Enable designware spi bit interrupt with mask.
Inline void dw_spi_mask_interrupt (DW_SPI_REG *spi_reg_ptr, uint32_t mask)
Disable designware spi bit interrupt with mask.
Inline void dw_spi_set_freq (DW_SPI_CTRL *spi_ctrl_ptr, uint32_t freq)
Set designware spi device frequency.
static int32_t dw_spi_set_dfs (DW_SPI_REG *spi_reg_ptr, uint32_t dfs)
Set designware spi device data frame size.
Inline uint32_t dw_spi_select_clockmode (uint32_t clk_mode)
Choose proper designware spi clock mode setting value.
Inline int32_t dw_spi_set_clockmode (DW_SPI_REG *spi_reg_ptr, uint32_t clk_mode)
Set designware spi clock mode.
Inline int32_t dw_spi_select_slave (DW_SPI_REG *spi_reg_ptr, uint32_t slv_line)
Select a spi slave with slv_line.
Inline int32_t dw_spi_deselect_slave (DW_SPI_REG *spi_reg_ptr, uint32_t slv_line)
Deselect a spi device.
Inline void dw_spi_flush_tx (DW_SPI_REG *spi_reg_ptr)
Inline void dw_spi_flush_rx (DW_SPI_REG *spi_reg_ptr)
static uint32_t dw_spi_get_txfifo_len (DW_SPI_REG *spi_reg_ptr)
Get TX FIFO Length.
static uint32_t dw_spi_get_rxfifo_len (DW_SPI_REG *spi_reg_ptr)
Get RX FIFO Length.
static void dw_spi_hw_init (DW_SPI_CTRL *spi_ctrl_ptr, uint32_t clk_mode, uint32_t dfs)
Init Designware SPI Hardware.
static void dw_spi_enable_device (DEV_SPI_INFO *spi_info_ptr)
enable designware spi
static void dw_spi_disable_device (DEV_SPI_INFO *spi_info_ptr)
disable designware spi
static int32_t dw_spi_dis_cbr (DEV_SPI_INFO *spi_info_ptr, uint32_t cbrtn)
disable designware spi send or receive interrupt
static int32_t dw_spi_ena_cbr (DEV_SPI_INFO *spi_info_ptr, uint32_t cbrtn)
enable DesignWare SPI send or receive interrupt
static void dw_spi_enable_interrupt (DEV_SPI_INFO *spi_info_ptr)
enable designware spi interrupt
static void dw_spi_disable_interrupt (DEV_SPI_INFO *spi_info_ptr)
disable designware spi interrupt
static void dw_spi_reset_device (DEV_SPI_INFO *spi_info_ptr)
static int32_t dw_spi_abort_tx (DEV_SPI *spi_obj)
abort current interrupt transmit transfer
static int32_t dw_spi_abort_rx (DEV_SPI *spi_obj)
abort current interrupt receive transfer
static int32_t dw_spi_abort_xfer (DEV_SPI *spi_obj)
abort current interrupt transfer
static int32_t dw_spi_get_txavail (DW_SPI_CTRL *spi_ctrl_ptr)
Get available transmit fifo count.
static int32_t dw_spi_get_rxavail (DW_SPI_CTRL *spi_ctrl_ptr)
Get available receive fifo count.
static uint32_t dw_spi_tx_max (DW_SPI_CTRL *spi_ctrl_ptr)
static uint32_t dw_spi_rx_max (DW_SPI_CTRL *spi_ctrl_ptr)
Inline int32_t dw_spi_rx_end (DW_SPI_CTRL *spi_ctrl_ptr)
Inline int32_t dw_spi_tx_end (DW_SPI_CTRL *spi_ctrl_ptr)
Inline int32_t dw_spi_xfer_end (DW_SPI_CTRL *spi_ctrl_ptr)
1 for end, 0 for not end
static int32_t dw_spi_writer (DEV_SPI_INFO *spi_info_ptr)
static int32_t dw_spi_reader (DEV_SPI_INFO *spi_info_ptr)
Inline uint32_t dw_spi_nbytes (uint32_t dfs)
static void dw_spi_init_transfer (DW_SPI_CTRL *spi_ctrl_ptr, DEV_SPI_TRANSFER *xfer, uint32_t dfs)
static int32_t dw_spi_chk_xfer_aligned (DEV_SPI_TRANSFER *xfer, uint32_t dfs)
static uint32_t dw_spi_poll_transfer (DEV_SPI_INFO *spi_info_ptr)
Detailed Description
Static or inline functions, variables for DesignWare SPI handle spi operations, only used in this file.
Function Documentation
static int32_t dw_spi_dis_cbr (DEV_SPI_INFO * spi_info_ptr, uint32_t cbrtn) static
disable designware spi send or receive interrupt
Parameters
[in] DEV_SPI_INFO *spi_info_ptr
[in] cbrtn control code of callback routine of send or receive
Definition at line 397 of file dw_spi.c.
References DW_SPI_CHECK_EXP, DW_SPI_GINT_ENABLE, DW_SPI_IN_RX, DW_SPI_IN_TX, DW_SPI_IN_XFER, dw_spi_mask_interrupt(), DW_SPI_RDY_RCV, DW_SPI_RDY_SND, DW_SPI_RDY_XFER, dw_spi_ctrl::dw_spi_regs, E_CTX, E_OK, int_disable(), dw_spi_ctrl::int_status, dw_spi_ctrl::intno, dev_spi_info::spi_ctrl, and dev_spi_info::status.
Referenced by dw_spi_abort_rx(), dw_spi_abort_tx(), dw_spi_abort_xfer(), dw_spi_control(), dw_spi_disable_interrupt(), and dw_spi_isr().
static void dw_spi_disable_interrupt (DEV_SPI_INFO * spi_info_ptr) static
disable designware spi interrupt
Parameters
spi_info_ptr spi information structure pointer
Definition at line 483 of file dw_spi.c.
References dw_spi_dis_cbr(), DW_SPI_GINT_ENABLE, DW_SPI_IN_XFER, dw_spi_mask_interrupt(), DW_SPI_RDY_RCV, DW_SPI_RDY_SND, DW_SPI_RDY_XFER, dw_spi_ctrl::dw_spi_regs, int_disable(), dw_spi_ctrl::int_status, dw_spi_ctrl::intno, dev_spi_info::spi_ctrl, and dev_spi_info::status.
Referenced by dw_spi_close(), dw_spi_isr(), and dw_spi_open().
static int32_t dw_spi_ena_cbr (DEV_SPI_INFO * spi_info_ptr, uint32_t cbrtn) static
enable DesignWare SPI send or receive interrupt
Parameters
[in] DEV_SPI_INFO *spi_info_ptr
[in] cbrtn control code of callback routine of send or receive
Definition at line 437 of file dw_spi.c.
References DW_SPI_CHECK_EXP, DW_SPI_GINT_ENABLE, DW_SPI_IN_RX, DW_SPI_IN_TX, DW_SPI_IN_XFER, DW_SPI_RDY_RCV, DW_SPI_RDY_SND, DW_SPI_RDY_XFER, dw_spi_ctrl::dw_spi_regs, dw_spi_unmask_interrupt(), E_CTX, E_OK, int_enable(), dw_spi_ctrl::int_status, dw_spi_ctrl::intno, dev_spi_info::spi_ctrl, and dev_spi_info::status.
Referenced by dw_spi_control().
static void dw_spi_enable_interrupt (DEV_SPI_INFO * spi_info_ptr) static
enable designware spi interrupt
Parameters
spi_info_ptr spi information structure pointer
Definition at line 471 of file dw_spi.c.
References DW_SPI_GINT_ENABLE, dw_spi_ctrl::dw_spi_int_handler, int_enable(), int_handler_install(), dw_spi_ctrl::int_status, dw_spi_ctrl::intno, and dev_spi_info::spi_ctrl.
static uint32_t dw_spi_get_txfifo_len (DW_SPI_REG * spi_reg_ptr) static
Get TX FIFO Length.
calculate spi fifo length using fifo threshold method If you attempt to set bits [7:0] of this register to a value greater than or equal to the depth of the FIFO, this field is not written and retains its current value.
Definition at line 292 of file dw_spi.c.
References DW_SPI_MAX_FIFO_LENGTH, and DW_SPI_MIN_FIFO_LENGTH.
Referenced by dw_spi_open().
Inline int32_t dw_spi_prcv_dat (DW_SPI_REG * spi_reg_ptr)
receive one char from spi in poll method, blocked function
Parameters
[in] spi_reg_ptr spi register structure pointer
Returns
data received by the spi
Definition at line 182 of file dw_spi.c.
References dw_spi_getdata(), and dw_spi_getready().
Inline void dw_spi_psnd_dat (DW_SPI_REG * spi_reg_ptr, int32_t data)
send char by spi in poll method, blocked function
Parameters
[in] spi_reg_ptr spi register structure pointer
[in] data data to be sent
Definition at line 170 of file dw_spi.c.
References dw_spi_putdata(), and dw_spi_putready().
Inline int32_t dw_spi_rcv_dat (DW_SPI_REG * spi_reg_ptr)
receive one char from spi, mostly used in interrupt routine, non-blocked function
Parameters
[in] spi_reg_ptr spi register structure pointer
Returns
data received by the spi
Definition at line 161 of file dw_spi.c.
References dw_spi_getdata().
Inline int32_t dw_spi_snd_dat (DW_SPI_REG * spi_reg_ptr, int32_t data)
send data by spi when available, mostly used in interrupt method, non-blocked function
Parameters
[in] spi_reg_ptr spi register structure pointer
[in] data data to be sent
Return values
E_OK send successfully
E_OBJ not ready to send data
Definition at line 147 of file dw_spi.c.
References dw_spi_putdata(), dw_spi_putready(), E_OBJ, and E_OK.