embARC: IIC Device HAL Interface
IIC Device HAL Interface
Device HAL » Device HAL Definition
definitions for iic device hardware layer (dev_iic.h)
Modules
IIC Device Control Commands
Definitions for iic control command, used in IIC IO Control.
IIC Device Structure
contains definitions of iic device structure.
IIC Interrupt callback functions
callback function structure for IIC device
IIC Related Configurations
Macros for IIC device related configurations.
Files
file dev_iic.h
iic device hardware layer definitions
Functions
DEV_IIC_PTR iic_get_dev (int32_t iic_id)
get an iic device by iic device id.
Detailed Description
definitions for iic device hardware layer (dev_iic.h)
provide interfaces for iic driver to implement Here is a diagram for the iic interface.
IIC Device HAL Interface Diagram
Function Documentation
iic_get_dev()
DEV_IIC_PTR iic_get_dev (int32_t iic_id)
get an iic device by iic device id.
For how to use iic device hal refer to Functions in iic device structure
Parameters
[in] iic_id id of iic, defined by user
Return values
!NULL pointer to an iic device structure
NULL failed to find the iic device by iic_id
Note
need to implemented by user in user code
get an iic device by iic device id.
Definition at line 255 of file emsk/drivers/ip/designware/iic/dw_iic_obj.c.
References dw_iic_0, DW_IIC_0_ID, dw_iic_1, DW_IIC_1_ID, dw_iic_2, DW_IIC_2_ID, and dw_iic_all_install().
Referenced by _ad7991_reg_read(), _ad7991_reg_write(), _adt7420_reg_read(), _adt7420_reg_write(), _tcn75_reg_read(), _tcn75_reg_write(), ad7991_adc_deinit(), ad7991_adc_init(), adt7420_sensor_deinit(), adt7420_sensor_init(), tcn75_sensor_deinit(), and tcn75_sensor_init().