embARC: DesignWare IIC Driver Function API Implement
DesignWare IIC Driver Function API Implement
Device HAL » Device HAL Implementation » Designware Device Driver » Designware IIC Driver
implement device hal iic api with DesignWare IIC
Functions
int32_t dw_iic_open (DEV_IIC *iic_obj, uint32_t mode, uint32_t param)
open a designware iic device
int32_t dw_iic_close (DEV_IIC *iic_obj)
Close a DesignWare IIC device.
int32_t dw_iic_control (DEV_IIC *iic_obj, uint32_t ctrl_cmd, void *param)
Control iic by ctrl command.
int32_t dw_iic_write (DEV_IIC *iic_obj, const void *data, uint32_t len)
poll transmit data through DesignWare IIC as master or slave
int32_t dw_iic_read (DEV_IIC *iic_obj, void *data, uint32_t len)
read data through DesignWare IIC
void dw_iic_isr (DEV_IIC *iic_obj, void *ptr)
DesignWare IIC interrupt processing routine.
Detailed Description
implement device hal iic api with DesignWare IIC
Function Documentation
int32_t dw_iic_close (DEV_IIC * iic_obj)
Close a DesignWare IIC device.
Parameters
[in] iic_obj iic device object pointer
Return values
E_OK Close successfully without any issues(including secenary that device is already closed)
E_OPNED Device is still opened, the device opn_cnt decreased by 1
E_OBJ Device object is not valid
Definition at line 1156 of file dw_iic.c.
References DEV_DISABLED, dw_iic_abort_rx(), dw_iic_abort_tx(), DW_IIC_CHECK_EXP, dw_iic_disable_device(), dw_iic_disable_interrupt(), E_OK, E_OPNED, dev_iic_info::extra, dev_iic_info::iic_cbs, dev_iic::iic_info, IIC_MODE_STOP, dev_iic_info::next_cond, dev_iic_info::opn_cnt, dev_iic_info::rx_buf, dev_iic_info::status, dev_iic_info::tx_buf, and VALID_CHK_IIC_INFO_OBJECT.
Referenced by dw_iic_0_close().
int32_t dw_iic_control (DEV_IIC * iic_obj, uint32_t ctrl_cmd, void * param)
Control iic by ctrl command.
Parameters
[in] iic_obj iic device object pointer
[in] ctrl_cmd control command, to change or get some thing related to iic
[in,out] param parameters that maybe argument of the command, or return values of the command, must not be NULL
Return values
E_OK Control device successfully
E_CLSED Device is not opened
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Control device failed, due to hardware issues, such as device is disabled
E_CTX Control device failed, due to different reasons like in transfer state
E_NOSPT Control command is not supported or not valid
Definition at line 1200 of file dw_iic.c.
References dev_iic_info::addr_mode, dev_buffer::buf, CHECK_ALIGN_4BYTES, dev_iic_info::cur_state, DEV_ENABLED, DEV_MASTER_MODE, DEV_SLAVE_MODE, dw_iic_abort_rx(), dw_iic_abort_tx(), DW_IIC_CHECK_EXP, dw_iic_dis_cbr(), dw_iic_disable_device(), dw_iic_ena_cbr(), dw_iic_enable_device(), dw_iic_get_rxavail(), dw_iic_get_txavail(), DW_IIC_RDY_RCV, DW_IIC_RDY_SND, dw_iic_ctrl::dw_iic_regs, dw_iic_ctrl::dw_iic_rxbuf, dw_iic_set_mstaddr_mode(), dw_iic_set_slvaddr(), dw_iic_set_slvaddr_mode(), dw_iic_set_speedmode(), dw_iic_set_taraddr(), E_CLSED, E_CTX, E_NOSPT, E_OK, E_PAR, E_SYS, dev_iic_cbs::err_cb, IIC_10BIT_ADDRESS, IIC_10BIT_ADDRESS_MASK, IIC_7BIT_ADDRESS, IIC_7BIT_ADDRESS_MASK, dev_iic_info::iic_cbs, IIC_CMD_ABORT_RX, IIC_CMD_ABORT_TX, IIC_CMD_DIS_DEV, IIC_CMD_ENA_DEV, IIC_CMD_FLUSH_RX, IIC_CMD_FLUSH_TX, IIC_CMD_GET_RXAVAIL, IIC_CMD_GET_STATUS, IIC_CMD_GET_TXAVAIL, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_SPEED_MODE, IIC_CMD_MST_SET_TAR_ADDR, IIC_CMD_RESET, IIC_CMD_SET_ADDR_MODE, IIC_CMD_SET_ERRCB, IIC_CMD_SET_RXCB, IIC_CMD_SET_RXINT, IIC_CMD_SET_RXINT_BUF, IIC_CMD_SET_TXCB, IIC_CMD_SET_TXINT, IIC_CMD_SET_TXINT_BUF, IIC_CMD_SLV_GET_SLV_STATE, IIC_CMD_SLV_SET_SLV_ADDR, dev_iic_info::iic_ctrl, IIC_FREE, IIC_IN_RX, IIC_IN_TX, dev_iic::iic_info, IIC_MODE_RESTART, IIC_MODE_STOP, IIC_SPEED_STANDARD, IIC_SPEED_ULTRA, dev_buffer::len, dev_iic_info::mode, dev_iic_info::next_cond, dev_buffer::ofs, dev_iic_info::opn_cnt, dev_iic_info::rx_buf, dev_iic_cbs::rx_cb, dev_iic_info::slv_addr, dev_iic_info::speed_mode, dev_iic_info::status, dev_iic_info::tar_addr, dev_iic_info::tx_buf, dev_iic_cbs::tx_cb, and VALID_CHK_IIC_INFO_OBJECT.
Referenced by dw_iic_0_control().
void dw_iic_isr (DEV_IIC * iic_obj, void * ptr)
DesignWare IIC interrupt processing routine.
Parameters
[in] iic_info_ptr DEV_IIC *iic_obj
[in] ptr extra information
Definition at line 1562 of file dw_iic.c.
References dev_iic_info::cur_state, DEV_MASTER_MODE, dw_iic_mst_int_read(), dw_iic_mst_int_write(), dw_iic_slv_int_process(), E_OK, IIC_IN_TX, dev_iic::iic_info, dev_iic_info::mode, and VALID_CHK_IIC_INFO_OBJECT.
Referenced by dw_iic_0_isr().
int32_t dw_iic_open (DEV_IIC * iic_obj, uint32_t mode, uint32_t param)
open a designware iic device
Parameters
[in] iic_obj iic device object pointer
[in] mode iic working mode (master or slave)
[in] param When mode is DEV_MASTER_MODE, param stands for speed mode, when mode is DEV_SLAVE_MODE, param stands for slave device 7bit address
Return values
E_OK Open successfully without any issues
E_OPNED If device was opened before with different parameters, then just increase the opn_cnt and return E_OPNED
E_OBJ Device object is not valid
E_SYS Device is opened for different mode before, if you want to open it with different mode, you need to fully close it first.
E_PAR Parameter is not valid
E_NOSPT Open settings are not supported
Definition at line 1058 of file dw_iic.c.
References dev_iic_info::addr_mode, dev_iic_info::cur_state, DEV_ENABLED, DEV_MASTER_MODE, DEV_SLAVE_MODE, DW_IIC_CHECK_EXP, dw_iic_disable_device(), dw_iic_disable_interrupt(), dw_iic_get_rxfifo_len(), dw_iic_get_txfifo_len(), dw_iic_ctrl::dw_iic_int_handler, dw_iic_master_init(), DW_IIC_MASTER_SUPPORTED, dw_iic_ctrl::dw_iic_regs, dw_iic_ctrl::dw_iic_rxbuf, dw_iic_slave_init(), DW_IIC_SLAVE_SUPPORTED, E_NOSPT, E_OK, E_OPNED, E_PAR, E_SYS, dev_iic_info::err_state, dev_iic_info::extra, IIC_10BIT_ADDRESS, IIC_10BIT_ADDRESS_MASK, IIC_7BIT_ADDRESS, IIC_7BIT_ADDRESS_MASK, dev_iic_info::iic_cbs, dev_iic_info::iic_ctrl, IIC_ERR_NONE, IIC_FREE, dev_iic::iic_info, IIC_MODE_STOP, dw_iic_ctrl::iic_rx_over, IIC_SPEED_STANDARD, IIC_SPEED_ULTRA, dw_iic_ctrl::iic_tx_over, int_handler_install(), dw_iic_ctrl::int_status, dw_iic_ctrl::intno, dev_iic_info::mode, dev_iic_info::next_cond, dev_iic_info::opn_cnt, dev_iic_info::rx_buf, dw_iic_ctrl::rx_fifo_len, dev_iic_info::slv_addr, dev_iic_info::speed_mode, dev_iic_info::status, dw_iic_ctrl::support_modes, dev_iic_info::tar_addr, dev_iic_info::tx_buf, dw_iic_ctrl::tx_fifo_len, and VALID_CHK_IIC_INFO_OBJECT.
Referenced by dw_iic_0_open().
int32_t dw_iic_read (DEV_IIC * iic_obj, void * data, uint32_t len)
read data through DesignWare IIC
Parameters
[in] iic_obj iic device object pointer
[out] data data that need to read (data must be uint8_t type)
[in] len data count need to read
Return values
>0 Byte count that was successfully received for poll method, it might can't send that much due to different error state.
E_OBJ Device object is not valid or not exists
E_CTX Device is still in transfer state
E_PAR Parameter is not valid
E_SYS Can't receive data from hardware due to hardware issues, such as device is disabled
Definition at line 1492 of file dw_iic.c.
References DEV_ENABLED, DEV_MASTER_MODE, DW_IIC_CHECK_EXP, dw_iic_mst_read_data(), dw_iic_slv_read_data(), E_CLSED, E_OK, E_PAR, E_SYS, dev_iic_info::err_state, IC_DATA_CMD_NONE, IC_DATA_CMD_RESTART, IC_DATA_CMD_STOP, dev_iic_info::iic_ctrl, IIC_ERR_NONE, dev_iic::iic_info, IIC_MODE_STOP, dev_iic_info::mode, dev_iic_info::next_cond, dev_iic_info::opn_cnt, dev_iic_info::status, and VALID_CHK_IIC_INFO_OBJECT.
Referenced by dw_iic_0_read().
int32_t dw_iic_write (DEV_IIC * iic_obj, const void * data, uint32_t len)
poll transmit data through DesignWare IIC as master or slave
Parameters
[in] iic_obj iic device object pointer
[in] data data that need to send (data must be uint8_t type)
[in] len data length need to send
Return values
>0 Byte count that was successfully sent for poll method, it might can't send that much due to different error state.
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid
E_CTX Device is still in transfer state
E_SYS Can't write data to hardware due to hardware issues, such as device is disabled
Definition at line 1421 of file dw_iic.c.
References DEV_ENABLED, DEV_MASTER_MODE, DW_IIC_CHECK_EXP, dw_iic_mst_write_data(), dw_iic_slv_write_data(), E_CLSED, E_OK, E_PAR, E_SYS, dev_iic_info::err_state, IC_DATA_CMD_NONE, IC_DATA_CMD_RESTART, IC_DATA_CMD_STOP, dev_iic_info::iic_ctrl, IIC_ERR_NONE, dev_iic::iic_info, IIC_MODE_STOP, dev_iic_info::mode, dev_iic_info::next_cond, dev_iic_info::opn_cnt, dev_iic_info::status, and VALID_CHK_IIC_INFO_OBJECT.
Referenced by dw_iic_0_write().