embARC: embARC IoT iBaby Smarthome Node Lamp Node
embARC IoT iBaby Smarthome Node Lamp Node
embARC Applications » All embARC ApplicationsembARC Applications » embARC Applications for Different Operating Systems » | embARC FreeRTOS ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC LwIP ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC FatFS ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC AWS IoT Applications
embARC IoT iBaby Smarthome Node Lamp Node
Files
file btn.c
emsk button driver for ibaby lamp node
file btn.h
button driver related header file
file lamp.c
lamp driver for ibaby lamp node
file lamp.h
lamp driver related header file
file lamp_work.c
function for control lamp to work lamp turn on or turn off
file lamp_work.h
Header File of lamp working function.
file lamp_node/function/lwm2m/lwm2m.c
function for LwM2M Client start
file lamp_node/function/print_msg/print_msg.c
function for print out message
file application/ibaby_smarthome_multinode/src/lamp_node/lwm2m_client/lwm2mclient.c
Implementation for LwM2M client.
file application/ibaby_smarthome_multinode/src/lamp_node/main.c
main source of iBaby Smarthome Node Lamp Node
Data Structures
struct data_lamp_node
Macros
#define BTN_L_BIT_OFFSET (0)
#define BTN_R_BIT_OFFSET (1)
#define BTN_A_BIT_OFFSET (2)
#define BTN_BIT_MASK (7)
#define BTN_ACTIVE_LOW (0)
#define BTN_ACTIVE_HIGH (1)
#define LED0 (0x01)
#define LED1 (0x02)
#define LED2 (0x04)
#define LED3 (0x08)
#define LED4 (0x10)
#define LED5 (0x20)
#define LED6 (0x40)
#define LED7 (0x80)
#define LED_ON (0xff)
#define LED_OFF (0x0)
#define STACK_DEPTH_LAMP (128) /* stack depth for lamp work : word(4*bytes) */
#define TIME_DELAY_LAMP_MS (1000)
#define STACK_DEPTH_LWM2M (20480) /* stack depth for lwm2mClient : word(4*bytes) */
Functions
static void btn_l_isr (void *ptr)
interrupt service routine for button L
static void btn_r_isr (void *ptr)
interrupt service routine for button R
static void btn_a_isr (void *ptr)
interrupt service routine for button A
void btn_init (void)
initialize GPIO for button
void lamp_init (void)
initialize GPIO for lamp using led on emsk to simulate desk lamp
void lamp_on (void)
turn on lamp
void lamp_off (void)
turn off lamp
static void task_lamp (void *par)
task for lamp working
void lamp_start (void)
function for lamp working
static void task_lwm2m_client (void *par)
int32_t lwm2m_client_start (void)
function to be LwM2M Client
void print_msg_func (void)
print message for debug major function
int main (void)
main entry
Variables
static TaskHandle_t task_lamp_handle = NULL
static lwm2m_client_info c_info
static int lwm2m_client_conn_stat = 0
static int lwm2m_client_start_flag = 0
static const char * p_port = (char *)"5683"
static const char * p_server = (char *)"192.168.43.199"
static const char * p_client_name = (char *)"ln"
static TaskHandle_t task_lwm2m_client_handle = NULL
macros for settings
#define LWM2M_CLIENT (1)
#define PRINT_DEBUG_FUNC (1)
macros for freertos task
#define TSKPRI_HIGH (configMAX_PRIORITIES-2)
#define TSKPRI_MID (configMAX_PRIORITIES-3)
#define TSKPRI_LOW (configMAX_PRIORITIES-4)
macros for reported data
data_lamp_node data_report_ln
data_lamp_node data_report_ln_old
Detailed Description
embARC IoT iBaby Smarthome Node Lamp Node
Extra Required Tools
Extra Required Peripherals
Digilent PMOD WIFI(MRF24WG0MA)
Design Concept
All modules should be connected to EMSK. This application is designed to show how to connect EMSK and iBaby Smarthome Gateway using embARC. This a simple application example than iBaby Wearable Node, it can help user add extensional nodes to iBaby Smarthome. Here we use the LED0 on emsk to simulate the desk lamp, it makes the application more simple and easy to learn.
Usage Manual
Before compiling this example, you need to change some macro in common.h to customize your own project.
It can report the following information to the iBaby Smarthome Gateway.
the flag of Lamp working state (bool) - The Lamp is ON or OFF.
EMSK can send the above data to iBaby Smarthome Gateway with LwM2M.
Extra Comments
Macro Definition Documentation
#define LWM2M_CLIENT (1)
set 1 to be lwm2m client
Definition at line 47 of file lamp_node/function/common.h.
#define PRINT_DEBUG_FUNC (1)
set 1 to print out message for debug major function
Definition at line 49 of file lamp_node/function/common.h.
#define TSKPRI_HIGH (configMAX_PRIORITIES-2)
< freertos task priority high priority
Definition at line 58 of file lamp_node/function/common.h.
Referenced by hrate_detector_start().
#define TSKPRI_LOW (configMAX_PRIORITIES-4)
low priority
Definition at line 60 of file lamp_node/function/common.h.
#define TSKPRI_MID (configMAX_PRIORITIES-3)
middle priority
Definition at line 59 of file lamp_node/function/common.h.
Referenced by lamp_start(), and sleep_monitor_start().
Function Documentation
void btn_init (void)
initialize GPIO for button
< initialize GPIO for button
Definition at line 86 of file btn.c.
References btn_a_isr(), btn_l_isr(), btn_r_isr(), GPIO_CMD_ENA_BIT_INT, GPIO_CMD_SET_BIT_INT_CFG, GPIO_CMD_SET_BIT_ISR, dev_gpio::gpio_control, gpio_get_dev(), dev_gpio_int_cfg::int_bit_debounce, dev_gpio_bit_isr::int_bit_handler, dev_gpio_int_cfg::int_bit_mask, dev_gpio_bit_isr::int_bit_ofs, dev_gpio_int_cfg::int_bit_polarity, and dev_gpio_int_cfg::int_bit_type.
Referenced by main().