embARC: embARC FreeRTOS Kernel Example
embARC FreeRTOS Kernel Example
embARC Applications » All embARC ApplicationsembARC Applications » embARC Applications for Different Operating Systems » | embARC FreeRTOS Applications
embARC Example for testing FreeRTOS task switch and interrupt/exception handling
Files
file example/freertos/kernel/main.c
main source file of the freertos demo
Data Structures
struct _sample
Macros
#define SWI_INTNO 20
#define MAX_SAMPLES 1000
#define TASK_DELAY_MS 10
Typedefs
typedef struct _sample sample
Functions
static void task1 (void *par)
task1 in FreeRTOS
static void task2 (void *par)
task2 in FreeRTOS
static void trap_exception (void *p_excinf)
trap exception
static void soft_interrupt (void *p_exinf)
soft interrupt
static void perf_init (unsigned int id)
performance timer initialization
static void perf_start (void)
performance timer start
static unsigned int perf_end (void)
performance timer end, and return the time passed
int main (void)
call FreeRTOS API, create and start tasks
Variables
static TaskHandle_t task1_handle = NULL
handle of task1
static TaskHandle_t task2_handle = NULL
handle of task2
static volatile unsigned int start = 0
static unsigned int perf_id = 0xFF
static sample x
static sample x_aver = {0}
static sample sample_array [MAX_SAMPLES]
static int sample_count = 0
Detailed Description
embARC Example for testing FreeRTOS task switch and interrupt/exception handling
Extra Required Tools
Extra Required Peripherals
Design Concept
This example is designed to show the functionality of FreeRTOS.
Usage Manual
Test case for show how FreeRTOS is working by task switching and interrupt/exception processing.
ScreenShot of freertos-demo under freertos
Extra Comments
Function Documentation
static void soft_interrupt (void * p_exinf) static
soft interrupt
Call trap_s instruction to raise the exception.
Parameters
[in] *p_excinf
Definition at line 297 of file example/freertos/kernel/main.c.
References perf_end(), and perf_start().
Referenced by main().
static void task1 (void * par) static
task1 in FreeRTOS
Call vTaskDelayUntil() to execute task1 with a fixed period 1 second.
Parameters
[in] *par
Definition at line 193 of file example/freertos/kernel/main.c.
References AUX_IRQ_HINT, perf_end(), perf_start(), and task2_handle.
Referenced by main().
static void task2 (void * par) static
task2 in FreeRTOS
Print information in task2 and suspend task2.
Parameters
[in] *par
Definition at line 216 of file example/freertos/kernel/main.c.
References perf_end(), perf_init(), perf_start(), task1_handle, task2_handle, and TIMER_1.
Referenced by main().
static void trap_exception (void * p_excinf) static
trap exception
Call xTaskResumeFromISR() to resume task2 that can be called from within ISR. If resuming the task2 should result in a context switch, call vPortYieldFromIsr() to generate task switch request.
Parameters
[in] *p_excinf
Definition at line 286 of file example/freertos/kernel/main.c.
References perf_end(), and perf_start().
Referenced by main().
Variable Documentation
task1_handle = NULL static
handle of task1
If task handle is not used, set Null.
Definition at line 87 of file example/freertos/kernel/main.c.
Referenced by main(), and task2().
task2_handle = NULL static
handle of task2
If task handle is not used, set Null.
Definition at line 93 of file example/freertos/kernel/main.c.
Referenced by main(), task1(), and task2().