embARC: Internal Timer
Internal Timer
ARC HAL » Internal Components
ARC internal timer management.
Files
file arc_timer.c
implementation of internal timer related functions
file arc_timer.h
header file of ARC internal timer
Functions
int32_t timer_present (const uint32_t no)
check whether the specific timer present
int32_t timer_start (const uint32_t no, const uint32_t mode, const uint32_t val)
start the specific timer
int32_t timer_stop (const uint32_t no)
stop and clear the specific timer
int32_t timer_current (const uint32_t no, void *val)
get timer current tick
int32_t timer_int_clear (const uint32_t no)
clear the interrupt pending bit of timer
void timer_init (void)
init internal timer
arc internal timers names
#define TIMER_0 0
#define TIMER_1 1
#define TIMER_RTC 2
bit definition of RTC CTRL reg
#define TIMER_RTC_ENABLE 0x01
#define TIMER_RTC_CLEAR 0x02 /* clears the AUX_RTC_LOW and AUX_RTC_HIGH */
#define TIMER_RTC_STATUS_A0 0x40000000
#define TIMER_RTC_STATUS_A1 0x80000000
bit definition of timer CTRL reg
#define TIMER_CTRL_IE (1 << 0)
#define TIMER_CTRL_NH (1 << 1)
#define TIMER_CTRL_W (1 << 2)
#define TIMER_CTRL_IP (1 << 3)
Detailed Description
ARC internal timer management.
The processor timers include two independent 32-bit timers and a 64-bit real-time counter (RTC). Timer 0 and timer 1 are identical in operation. The only difference is that these timers are connected to different interrupts. The Timers cannot be included in a configuration without interrupts. Each timer is optional and when present, it is connected to a fixed interrupt; interrupt 16 for timer 0 and interrupt 17 for timer 1. The processor timers are connected to a system clock signal that operates even when the ARCv2-based processor is in the sleep state. The timers can be used to generate interrupt signals that wake the processor from SLEEP state.
The processor timers automatically reset and restart their operation after reaching the limit value. The processor timers can be programmed to count only the clock cycles when the processor is not halted. The processor timers can also be programmed to generate an interrupt or to generate a system Reset upon reaching the limit value.
The 64-bit RTC does not generate any interrupts. This timer is used to count the clock cycles automatically.
Macro Definition Documentation
#define TIMER_0 0
macro name for arc internal timer 0
Definition at line 54 of file arc_timer.h.
Referenced by board_get_cur_us(), board_get_hwticks(), main(), timer0_isr(), timer_current(), timer_init(), timer_int_clear(), timer_present(), timer_start(), and timer_stop().
#define TIMER_1 1
macro name for arc internal timer 1
Definition at line 55 of file arc_timer.h.
Referenced by main(), task2(), timer1_isr(), timer_current(), timer_init(), timer_int_clear(), timer_present(), timer_start(), and timer_stop().
#define TIMER_CTRL_IE (1 << 0)
Interrupt when count reaches limit
Definition at line 76 of file arc_timer.h.
Referenced by axs_timer_init(), emsk_timer_init(), main(), and nsim_timer_init().
#define TIMER_CTRL_IP (1 << 3)
interrupt pending
Definition at line 79 of file arc_timer.h.
Referenced by timer_int_clear().
#define TIMER_CTRL_NH (1 << 1)
Count only when CPU NOT halted
Definition at line 77 of file arc_timer.h.
Referenced by axs_timer_init(), emsk_timer_init(), nsim_timer_init(), and perf_init().
#define TIMER_CTRL_W (1 << 2)
watchdog enable
Definition at line 78 of file arc_timer.h.
Referenced by main().
#define TIMER_RTC 2
macro name for arc internal RTC
Definition at line 56 of file arc_timer.h.
Referenced by timer_current(), timer_init(), timer_present(), timer_start(), and timer_stop().
#define TIMER_RTC_ENABLE 0x01
enable RTC
Definition at line 65 of file arc_timer.h.
#define TIMER_RTC_STATUS_A0 0x40000000
track bit of atomicity of reads of RTC
Definition at line 67 of file arc_timer.h.
#define TIMER_RTC_STATUS_A1 0x80000000
track bit of atomicity of reads of RTC
Definition at line 68 of file arc_timer.h.
Function Documentation
int32_t timer_current (const uint32_t no, void * val)
get timer current tick
Parameters
[in] no timer number
[out] val,timer value
Returns
0 success, -1 failure
Definition at line 147 of file arc_timer.c.
References AUX_RTC_LOW, AUX_TIMER0_CNT, AUX_TIMER1_CNT, TIMER_0, TIMER_1, timer_present(), and TIMER_RTC.
Referenced by board_get_cur_us(), board_get_hwticks(), main(), perf_end(), and perf_start().
int32_t timer_int_clear (const uint32_t no)
clear the interrupt pending bit of timer
Parameters
[in] no timer number
Returns
0 success, -1 failure
Definition at line 176 of file arc_timer.c.
References AUX_TIMER0_CTRL, AUX_TIMER1_CTRL, TIMER_0, TIMER_1, TIMER_CTRL_IP, and timer_present().
Referenced by axs_timer_isr(), emsk_timer_isr(), nsim_timer_isr(), timer0_isr(), and timer1_isr().
int32_t timer_present (const uint32_t no)
check whether the specific timer present
Parameters
[in] no timer number
Returns
1 present, 0 not present
Definition at line 49 of file arc_timer.c.
References AUX_BCR_TIMERS, TIMER_0, TIMER_1, and TIMER_RTC.
Referenced by axs_timer_init(), emsk_timer_init(), main(), nsim_timer_init(), timer_current(), timer_int_clear(), timer_start(), and timer_stop().
int32_t timer_start (const uint32_t no, const uint32_t mode, const uint32_t val)
start the specific timer
Parameters
[in] no timer number
[in] mode timer mode
[in] val timer limit value (not for RTC)
Returns
0 success, -1 failure
Definition at line 78 of file arc_timer.c.
References AUX_RTC_CTRL, AUX_TIMER0_CNT, AUX_TIMER0_CTRL, AUX_TIMER0_LIMIT, AUX_TIMER1_CNT, AUX_TIMER1_CTRL, AUX_TIMER1_LIMIT, TIMER_0, TIMER_1, timer_present(), and TIMER_RTC.
Referenced by axs_timer_init(), emsk_timer_init(), main(), nsim_timer_init(), and perf_init().
int32_t timer_stop (const uint32_t no)
stop and clear the specific timer
Parameters
[in] no timer number
Returns
0 success, -1 failure
Definition at line 113 of file arc_timer.c.
References AUX_RTC_CTRL, AUX_TIMER0_CNT, AUX_TIMER0_CTRL, AUX_TIMER0_LIMIT, AUX_TIMER1_CNT, AUX_TIMER1_CTRL, AUX_TIMER1_LIMIT, TIMER_0, TIMER_1, timer_present(), and TIMER_RTC.
Referenced by main(), and timer_init().