embARC: EMBARC_APP_FREERTOS_IBABY_SMARTHOME_NODES_WEARABLE_NODE
EMBARC_APP_FREERTOS_IBABY_SMARTHOME_NODES_WEARABLE_NODE
Files
file acceleration.h
acceleration sensor driver related header file
Data Structures
struct __accValues
Macros
#define ACC_SENSOR_IIC_ID DW_IIC_1_ID
#define MPU6050_A0_PIN 0
I2C address of PmodIMU4 can be selected via AD0: 0x68, 0x69 AD0 connect to GND is 0x68.
#define MPU6050_ADDRESS (0x68 + MPU6050_A0_PIN)
#define ACC_SENSOR_ADDR MPU6050_ADDRESS
#define EMSK_IMU_SENSOR_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
Typedefs
typedef struct __accValues acc_values
Functions
int32_t acc_sensor_init (uint32_t slv_addr)
acceleration sensor initialize
int32_t acc_sensor_read (acc_values *accel_val)
read acceleration sensor value
void hrate_detector_start (void)
function for starting heartrate detecting
Detailed Description
Macro Definition Documentation
#define ACC_SENSOR_IIC_ID DW_IIC_1_ID
< using IIC 1 interface
Definition at line 47 of file acceleration.h.
Referenced by acc_sensor_init(), acc_sensor_read(), mpu6050_reg_read(), and mpu6050_reg_write().
#define EMSK_IMU_SENSOR_CHECK_EXP_NORTN (EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
struct for acceleration data storaged
Definition at line 60 of file acceleration.h.
Referenced by acc_sensor_init(), mpu6050_reg_read(), and mpu6050_reg_write().
#define MPU6050_A0_PIN 0
I2C address of PmodIMU4 can be selected via AD0: 0x68, 0x69 AD0 connect to GND is 0x68.
< MPU6050 address I2C Serial Bus Address Selection Pin
Definition at line 54 of file acceleration.h.
#define MPU6050_ADDRESS (0x68 + MPU6050_A0_PIN)
acceleration sensor address
Definition at line 55 of file acceleration.h.
Function Documentation
int32_t acc_sensor_init (uint32_t slv_addr)
acceleration sensor initialize
Parameters
[in] slv_addr imu sensor iic slave address
Return values
E_OK initialize success
!E_OK initialize failed
Definition at line 176 of file acceleration.c.
References ACC_SENSOR_IIC_ID, CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, EMSK_IMU_SENSOR_CHECK_EXP_NORTN, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, IIC_SPEED_STANDARD, and mpu6050_reg_write().
Referenced by main().
int32_t acc_sensor_read (acc_values * acc_temp)
read acceleration sensor value
Parameters
[out] val return acceleration data
Return values
E_OK read success
!E_OK read failed
Definition at line 205 of file acceleration.c.
References ACC_SENSOR_IIC_ID, E_OBJ, E_OK, iic_get_dev(), and mpu6050_reg_read().
Referenced by task_sleep_monitor().