embARC: SPI Device Structure
SPI Device Structure
Device HAL » Device HAL Definition » SPI Device HAL Interface
contains definitions of spi device structure.
Data Structures
struct dev_spi_transfer
spi read and write data structure used by SPI_CMD_TRANSFER spi write then read data
struct dev_spi_info
spi information struct definition
struct dev_spi
spi device interface definition
Macros
#define DEV_SPI_XFER_SET_TXBUF(xfer, buf, ofs, len)
Set tx buffer of device spi transfer.
#define DEV_SPI_XFER_SET_RXBUF(xfer, buf, ofs, len)
Set rx buffer of device spi transfer.
#define DEV_SPI_XFER_CALC_TOTLEN(xfer)
Calculate total length of current transfer without next transfer.
#define DEV_SPI_XFER_SET_NEXT(xfer, next_xfer) (xfer)->next = (next_xfer);
Set next SPI transfer.
#define DEV_SPI_XFER_INIT(xfer)
Init spi transfer.
#define DEV_SPI_INFO_SET_EXTRA_OBJECT(spi_info_ptr, extra_info) (spi_info_ptr)->extra = (void *)(extra_info)
Set extra information pointer of spi info.
#define DEV_SPI_INFO_GET_EXTRA_OBJECT(spi_info_ptr) ((spi_info_ptr)->extra)
Get extra information pointer of spi info.
#define SPI_DFS_DEFAULT 8
#define SPI_SLAVE_NOT_SELECTED (0xFF)
#define SPI_DUMMY_DEFAULT (0xFF)
Typedefs
typedef struct dev_spi_transfer DEV_SPI_TRANSFER
typedef struct dev_spi_transfer * DEV_SPI_TRANSFER_PTR
typedef struct dev_spi_info DEV_SPI_INFO
spi information struct definition
typedef struct dev_spi_info * DEV_SPI_INFO_PTR
typedef struct dev_spi DEV_SPI
spi device interface definition
typedef struct dev_spi * DEV_SPI_PTR
Variables
int32_t(* dev_spi::spi_open)(uint32_t mode, uint32_t param)
int32_t(* dev_spi::spi_close)(void)
int32_t(* dev_spi::spi_control)(uint32_t ctrl_cmd, void *param)
int32_t(* dev_spi::spi_write)(const void *data, uint32_t len)
int32_t(* dev_spi::spi_read)(void *data, uint32_t len)
Detailed Description
contains definitions of spi device structure.
this structure will be used in user implemented code, which was called Device Driver Implement Layer for spi to realize in user code.
Macro Definition Documentation
#define DEV_SPI_XFER_CALC_TOTLEN (xfer)
Value:
(xfer)->tot_len =       \
                                ((xfer)->tx_totlen > (xfer)->rx_totlen) ? (xfer)->tx_totlen : (xfer)->rx_totlen ;
Calculate total length of current transfer without next transfer.
Definition at line 424 of file dev_spi.h.
#define DEV_SPI_XFER_INIT (xfer)
Value:
{               \
                                        (xfer)->tx_idx = 0;                     \
                                        (xfer)->rx_idx = 0;                     \
                                        (xfer)->tx_totlen = ((xfer)->tx_len     \
                                                        + (xfer)->tx_ofs) ;     \
                                        (xfer)->rx_totlen = ((xfer)->rx_len     \
                                                        + (xfer)->rx_ofs) ;     \
                    DEV_SPI_XFER_CALC_TOTLEN(xfer);            \
                                }
Init spi transfer.
Definition at line 431 of file dev_spi.h.
#define DEV_SPI_XFER_SET_RXBUF (xfer, buf, ofs, len)
Value:
{               \
                                        (xfer)->rx_buf = (uint8_t *)(buf);      \
                                        (xfer)->rx_len = (uint32_t)(len);       \
                                        (xfer)->rx_ofs = (uint32_t)(ofs);       \
                                        (xfer)->rx_idx = 0;                     \
                                        (xfer)->rx_totlen = ( (uint32_t)(len)   \
                                                        + (uint32_t)(ofs) ) ;   \
                                }
Set rx buffer of device spi transfer.
Definition at line 414 of file dev_spi.h.
Referenced by dw_spi_control(), dw_spi_read(), dw_spi_write(), flash_erase(), flash_read(), flash_read_id(), flash_read_status(), flash_write(), flash_write_enable(), and rw009_xfer().
#define DEV_SPI_XFER_SET_TXBUF (xfer, buf, ofs, len)
Value:
{               \
                                        (xfer)->tx_buf = (uint8_t *)(buf);      \
                                        (xfer)->tx_len = (uint32_t)(len);       \
                                        (xfer)->tx_ofs = (uint32_t)(ofs);       \
                                        (xfer)->tx_idx = 0;                     \
                                        (xfer)->tx_totlen = ( (uint32_t)(len)   \
                                                        + (uint32_t)(ofs) ) ;   \
                                }
Set tx buffer of device spi transfer.
Definition at line 404 of file dev_spi.h.
Referenced by dw_spi_control(), dw_spi_read(), dw_spi_write(), flash_erase(), flash_read(), flash_read_id(), flash_read_status(), flash_write(), flash_write_enable(), and rw009_xfer().
#define SPI_DFS_DEFAULT 8
Default spi data frame size
Definition at line 468 of file dev_spi.h.
Referenced by dw_spi_0_install(), dw_spi_1_install(), and dw_spi_open().
#define SPI_DUMMY_DEFAULT (0xFF)
default dummy value for first open
Definition at line 470 of file dev_spi.h.
#define SPI_SLAVE_NOT_SELECTED (0xFF)
Slave is not selected
Definition at line 469 of file dev_spi.h.
Referenced by dw_spi_0_install(), dw_spi_1_install(), dw_spi_control(), and dw_spi_open().
Typedef Documentation
typedef struct dev_spi DEV_SPI
spi device interface definition
define spi device interface, like spi information structure, fuctions to get spi info, open/close/control spi, send/receive data by spi
Note
all this details are implemented by user in user porting code
typedef struct dev_spi_info DEV_SPI_INFO
spi information struct definition
informations about spi open state, working state, frequency, spi registers, working method, interrupt number
Variable Documentation
int32_t(* dev_spi::spi_close)(void)
close spi device
close an spi device, just decrease the opn_cnt, if opn_cnt equals 0, then close the device
Return values
E_OK Close successfully without any issues(including scenario that device is already closed)
E_OPNED Device is still opened, the device opn_cnt decreased by 1
E_OBJ Device object is not valid
Definition at line 483 of file dev_spi.h.
Referenced by dw_spi_0_install(), and dw_spi_1_install().
int32_t(* dev_spi::spi_control)(uint32_t ctrl_cmd, void *param)
control spi device
control an spi device by ctrl_cmd, with passed param. you can control spi device using predefined spi control commands defined using DEV_SET_SYSCMD (which must be implemented by bsp developer), such as set spi master frequency, flush tx and more. And you can also control spi device using your own specified commands defined using DEV_SET_USRCMD, but these specified commands should be defined in your own spi device driver implementation.
Parameters
[in] ctrl_cmd control command, to change or get some thing related to spi
[in,out] param parameters that maybe argument of the command, or return values of the command, must not be NULL
Return values
E_OK Control device successfully
E_CLSED Device is not opened
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid for current control command
E_SYS Control device failed, due to hardware issues, such as device is disabled
E_CTX Control device failed, due to different reasons like in transfer state
E_NOSPT Control command is not supported or not valid
Definition at line 484 of file dev_spi.h.
Referenced by dw_spi_0_install(), dw_spi_1_install(), flash_init(), rw009_deselect(), rw009_select(), rw009_xfer(), and spi_send_cmd().
int32_t(* dev_spi::spi_open)(uint32_t mode, uint32_t param)
open spi device in master/slave mode, \ when in master mode, param stands for frequency, \ when in slave mode, param stands for clock mode
open an spi device with selected mode (master or slave) with defined param
Parameters
[in] mode working mode (master or slave)
[in] param When mode is DEV_MASTER_MODE, param stands for frequency, when mode is DEV_SLAVE_MODE, param stands for slave clock mode
Return values
E_OK Open successfully without any issues
E_OPNED If device was opened before with different parameters, then just increase the opn_cnt and return E_OPNED
E_OBJ Device object is not valid
E_SYS Device is opened for different mode before, if you want to open it with different mode, you need to fully close it first.
E_PAR Parameter is not valid
E_NOSPT Open settings are not supported
Definition at line 480 of file dev_spi.h.
Referenced by dw_spi_0_install(), dw_spi_1_install(), and flash_init().
int32_t(* dev_spi::spi_read)(void *data, uint32_t len)
read data from spi device (blocking method)
receive data of defined len through spi from slave device .
Parameters
[out] data pointer to data need to received by spi
[in] len length of data to be received
Return values
>0 Byte count that was successfully received for poll method
E_OBJ Device object is not valid or not exists
E_CTX Device is still in transfer state
E_PAR Parameter is not valid
E_SYS Can't receive data from hardware due to hardware issues, such as device is disabled
Definition at line 486 of file dev_spi.h.
Referenced by dw_spi_0_install(), dw_spi_1_install(), and rw009_xfer().
int32_t(* dev_spi::spi_write)(const void *data, uint32_t len)
send data to spi device (blocking method)
send data through spi with defined len to slave device .
Parameters
[in] data pointer to data need to send by spi
[in] len length of data to be sent
Return values
>0 Byte count that was successfully sent for poll method
E_OBJ Device object is not valid or not exists
E_PAR Parameter is not valid
E_CTX Device is still in transfer state
E_SYS Can't write data to hardware due to hardware issues, such as device is disabled
Definition at line 485 of file dev_spi.h.
Referenced by dw_spi_0_install(), dw_spi_1_install(), and rw009_xfer().