embARC: HSDK Interrupt Management
HSDK Interrupt Management
BSP Layer » HSDK BSP
Files
file hsdk_interrupt.c
to add
file hsdk_interrupt.h
to add
Functions
static void hsdk_int_handler_default (void *ptr)
static void arc_connect_int_isr (void *ptr)
int32_t int_disable (const uint32_t intno)
disable the specific interrupt
int32_t int_enable (const uint32_t intno)
enable the specific int
int32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
int32_t int_ipm_get (void)
get the interrupt priority mask
int32_t int_ipm_set (int32_t intpri)
set the interrupt priority mask
int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
int32_t int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
int32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
int32_t int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
int32_t int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
void cpu_lock (void)
lock cpu, disable interrupts
void cpu_unlock (void)
unlock cpu, enable interrupts to happen
uint32_t cpu_lock_save (void)
lock cpu and staus
void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
void hsdk_interrupt_init (void)
Variables
static INT_HANDLER hsdk_int_handler_table [ARC_CONNECT_NUM_INT_ALL]
Detailed Description
Function Documentation
uint32_t cpu_lock_save (void)
lock cpu and staus
lock cpu and return status
Returns
cpu status
Definition at line 306 of file hsdk_interrupt.c.
References arc_lock_save().
Referenced by int_pri_set().
void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Parameters
[in] status cpu status saved by cpu_lock_save
Definition at line 316 of file hsdk_interrupt.c.
References arc_unlock_restore().
Referenced by int_pri_set().
int32_t int_disable (const uint32_t intno)
disable the specific interrupt
Parameters
[in] intno interrupt number
Definition at line 105 of file hsdk_interrupt.c.
References arc_int_disable(), and NUM_EXC_CPU.
int32_t int_enable (const uint32_t intno)
enable the specific int
Parameters
[in] intno interrupt number
Definition at line 123 of file hsdk_interrupt.c.
References arc_int_enable(), and NUM_EXC_CPU.
int32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
Parameters
[in] intno interrupt number
Returns
0 disabled, 1 enabled, < 0 error
Definition at line 142 of file hsdk_interrupt.c.
References arc_int_enabled(), AUX_IRQ_ENABLE, AUX_IRQ_SELECT, and NUM_EXC_CPU.
int32_t int_ipm_get (void)
get the interrupt priority mask
Returns
interrupt priority mask, negative num
Definition at line 162 of file hsdk_interrupt.c.
References arc_int_ipm_get(), and INT_PRI_MIN.
int32_t int_ipm_set (int32_t intpri)
set the interrupt priority mask
Parameters
[in] intpri interrupt priority
Definition at line 173 of file hsdk_interrupt.c.
References arc_int_ipm_set(), INT_PRI_MAX, and INT_PRI_MIN.
int32_t int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Parameters
[in] intno interrupt number
[in] level,0-level trigger, 1-pluse triggered
Returns
0 ok, -1 error
Definition at line 262 of file hsdk_interrupt.c.
References arc_int_level_config(), and NUM_EXC_CPU.
int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
Parameters
[in] intno interrupt number
Returns
<0 interrupt priority, 0 error
Definition at line 191 of file hsdk_interrupt.c.
References arc_int_pri_get(), INT_PRI_MIN, and NUM_EXC_CPU.
int32_t int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
Parameters
[in] intno interrupt number
[in] intpri interrupt priority
Definition at line 206 of file hsdk_interrupt.c.
References arc_int_pri_set(), cpu_lock_save(), cpu_unlock_restore(), INT_PRI_MIN, and NUM_EXC_CPU.
int32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
Parameters
[in] intno interrupt number
Returns
1 pending, 0 no pending, -1 error
Definition at line 227 of file hsdk_interrupt.c.
References arc_int_probe(), and NUM_EXC_CPU.
int32_t int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Parameters
[in] intno interrupt number
Returns
0 ok, -1 error
Definition at line 242 of file hsdk_interrupt.c.
References arc_int_sw_trigger(), and NUM_EXC_CPU.
Variable Documentation
INT_HANDLER hsdk_int_handler_table[ARC_CONNECT_NUM_INT_ALL] static
Initial value:
= {
        [0 ... ARC_CONNECT_NUM_INT_ALL-1] = hsdk_int_handler_default
}
Definition at line 59 of file hsdk_interrupt.c.