embARC: embARC IOT iLight synthesize
embARC IOT iLight synthesize
embARC Applications » All embARC ApplicationsembARC Applications » embARC Applications for Different Operating Systems » | embARC FreeRTOS ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC FatFS Applications
embARC IOT iLight smartdevice
Files
file mpu6050.c
emsk mpu6050 sensor driver for iLight
file mpu6050.h
emsk mpu6050 sensor driver for iLight
file light_driver.c
light control driver for ilight.
file light_driver.h
light control driver for ilight.
file rtc.c
emsk rtc for iLight
file rtc.h
emsk rtc for iLight
file word.c
word model for iLight
file word.h
word model for iLight
file ble_int.c
function for bluetooth initial and interupt to devide mode
file ble_int.h
Header File of bluetooth.
file IMU.c
Header file of action recognition function.
file IMU.h
Header file of action recognition function.
file light_mode.h
light control mode related header file
file fft.c
function for calculate the frequency data capture from microphone
file fft.h
Fast Fourier transform of the data.
file fft.h
Fast Fourier transform of the data.
file fft_list.c
list for speeding up fft calculation
file fft_tab.c
list for speeding up the calculation of sin or cos
file mic.c
mic used in ilight
file mic.h
mic used in ilight
file scope.c
virtual scope for iLight
file scope.h
virtual scope for iLight
file application/ilight_smartdevice/src/main.c
main source of iLight Smartdevice
file task.c
task in FreeRTOS
file task.h
Header File of task function.
Data Structures
union RGB_T
Llight color data structure r,g,b reresents the RGB color data.
struct RGB_T::rgb_s
struct _rtc
struct acc_upbuf
struct acc_special
struct imu_mpu6050_update
struct compx
struct mode_info
Macros
#define SMPLRT_DIV 0x19
MPU6050 internal register address macro definition Gyroscope sampling rate, typical: 0x07 (125Hz)
#define LPF_CONFIG 0x1A
#define MPU_GYRO_CFG_REG 0x1B
#define MPU_ACCEL_CFG_REG 0x1C
#define MPU_INT_EN_REG 0X38
#define MPU_USER_CTRL_REG 0X6A
#define MPU_FIFO_EN_REG 0X23
#define MPU_INTBP_CFG_REG 0X37
#define MPU_PWR_MGMT1_REG 0x6B
#define MPU_PWR_MGMT2_REG 0X6C
#define TEMP_OUT_H 0x41
#define TEMP_OUT_L 0x42
#define GYRO_XOUT_H 0x43
#define GYRO_XOUT_L 0x44
#define GYRO_YOUT_H 0x45
#define GYRO_YOUT_L 0x46
#define GYRO_ZOUT_H 0x47
#define GYRO_ZOUT_L 0x48
#define WHO_AM_I 0x75
#define MUPADDRESS 0xD0
#define ACCEL_XOUT_H 0x3B
#define ACCEL_XOUT_L 0x3C
#define ACCEL_YOUT_H 0x3D
#define ACCEL_YOUT_L 0x3E
#define ACCEL_ZOUT_H 0x3F
#define ACCEL_ZOUT_L 0x40
#define MPU6050_IIC_NUM DW_IIC_0_ID
#define GPIO_OUT_PORT_MIDDLE (DW_GPIO_PORT_A)
#define GPIO_OUT_OFFSET_MIDDLE (11)
#define GPIO_OUT_MASK_MIDDLE (1 << GPIO_OUT_OFFSET_MIDDLE)
#define GPIO_H_CFG_MIDDLE (1 << GPIO_OUT_OFFSET_MIDDLE)
#define GPIO_OUT_PORT_SIDE (DW_GPIO_PORT_C)
#define GPIO_OUT_OFFSET_SIDE (19)
#define GPIO_OUT_MASK_SIDE (1 << GPIO_OUT_OFFSET_SIDE)
#define GPIO_H_CFG_SIDE (1 << GPIO_OUT_OFFSET_SIDE)
#define LIGHT_ROW_MIDDLE 0x010
#define LIGHT_ROW_SIDE 0x101
#define LIGHT_NUM_MIDDLE 16
#define LIGHT_NUM_SIDE 34
#define RTC_ADDR_IIC 0xa2
Some macro definitions of date register The macro definition of IIC address of RTC device.
#define RTC_ADDR_WEEK 0x06
#define RTC_ADDR_HOUR 0x04
#define RTC_ADDR_MIN 0x03
#define RTC_ADDR_SEC 0x02
#define CLOCK_START 0x11
#define RTC_WEEK_MON 0
#define RTC_WEEK_TUES 1
#define RTC_WEEK_WEDNES 2
#define RTC_WEEK_THURS 3
#define RTC_WEEK_FRI 4
#define RTC_WEEK_SATUR 5
#define RTC_WEEK_SUN 6
#define SHOW_DELAY 1
#define BLE_RX_HEAD_FIRST '@' /* protocol of data transmission, the first head sign */
#define BLE_RX_HEAD_SECOND '#' /* protocol of data transmission, the second head sign */
#define BLE_RX_WEATHER_MODE '0' /* protocol of data transmission, the sign of mode */
#define BLE_RX_RUNNING_MODE '1'
#define BLE_RX_ALARM_MODE '2'
#define BLE_RX_RIDING_MODE '3'
#define BLE_RX_LIGHTING_MODE '4'
#define BLE_RX_CLOCK_MODE '5'
#define BLE_RX_FANSE_MODE '6'
#define BLE_RX_TIME_MODE '7'
#define BLE_RX_MUSIC_MODE '8'
#define BLE_RX_COMFOR_MODE '9'
#define BLE_RX_MIN_MODE '0'
#define BLE_FREQUENCY_SLOW '0' /* protocol of data transmission, the frequency of lighting mode */
#define BLE_FREQUENCY_NORMAL '1'
#define BLE_FREQUENCY_FAST '2'
#define BLE_FREQUENCY_VERY_FAST '3'
#define BLE_TAG_BRIGHT '1' /* protocol of data transmission, the brightness of lighting mode */
#define BLE_TAG_FREQUENCE '2'
#define BLE_TAG_COOL_OR_WARM '2'
#define BLE_TAG_ANIMATION '3'
#define BLE_TAG_LIGHT_WARM '1' /* protocol of data transmission, the chroma of lighting mode */
#define BLE_TAG_LIGHT_COOL '0'
#define BLE_TAG_LIGHT_ANIM '1' /* protocol of data transmission, the flag of lighting mode to dispaly animated light */
#define BLE_TAG_LIGHT_NOT_ANIM '0'
#define INITIAL_STATE 0 /* the stage sign, means the bluetooth stage */
#define FIRST_STATE 1
#define SECOND_STATE 2
#define THIRD_STATE 3
#define FOURTH_STATE 4
#define BLE_STATE_BYTE (BLE_RX_HANDLE_BUF_MAX-1)
#define BLE_DATA_LEN_BYTE (BLE_RX_HANDLE_BUF_MAX-2)
#define BLE_DATA_CNT_BYTE (BLE_RX_HANDLE_BUF_MAX-3)
#define BLE_MODE_TAG_BYTE (BLE_RX_HANDLE_BUF_MAX-4)
#define BLE_MODE_AUX_TAG_BYTE (BLE_RX_HANDLE_BUF_MAX-5)
#define BLE_LIGHT_TAG_BYTE (BLE_RX_HANDLE_BUF_MAX-6)
#define BLE_COLOR_TAG_BYTE (BLE_RX_HANDLE_BUF_MAX-7)
#define BLE_MODE_TIME_RX_LEN 4 /* protocol of data transmission, the data of time mode is 4 bytes */
#define BLE_MODE_WEATHER_RX_LEN 4 /* protocol of data transmission, the data of weather mode is 4 bytes */
#define BLE_RX_HANDLE_BUF_MAX 25 /* the max length of bluetooth buffer handle */
#define BLE_UART_EN (1)
Function for initialization of bluetooth Only used without scope.
#define WAVE_P 1
#define WAVE_N 2
#define WAVE_PN 6
#define WAVE_NP 9
#define WAVE_NN 10
#define WAVE_PNP 25
#define WAVE_PNN 26
#define WAVE_NPN 38
#define WAVE_PNPN 102
#define WAVE_NPNP 153
#define WAVE_NPNN 154
#define WAVE_NNPN 166
#define WAVE_PNPNP 409
#define WAVE_PNNPN 422
#define WAVE_NPNPN 614
#define WAVE_NPNPP 618
#define WAVE_PNPNPN 1638
#define GET_PEAK_PO 0x11 /* The flag of getting the first positive peak order */
#define GET_PEAK_NE 0x10 /* The flag of getting the first negative peak order */
#define JUDGE_WAVE_PO_THRESHOLD 0.3 /* The threshold of determing the acceleration waveform peak is positive */
#define JUDGE_WAVE_NE_THRESHOLD 0.5 /* The threshold of determing the acceleration waveform peak is negative */
#define JUDGE_SYMBOL_THRESHOLD 800 /* The threshold of determing the symbol of acc */
#define JUDGE_START_THRESHOLD 200
#define JUDGE_STOP_THRESHOLD 40
#define JUDGE_YACC_SWING_THRESHOLD 400
#define JUDGE_YACC_CIRLE_THRESHOLD 300
#define PEAK_WAVE_NEGATIVE 0x02 /* The record of negative peak */
#define PEAK_WAVE_POSITIVE 0x01 /* The record of negative peak */
#define ACC_FILTER_NUM 10 /* The number of filtering windows */
#define ACC_BUF_WINDOW_NUM 15 /* The number of dynamically updated caches */
#define ACTION_LEFT 0x01
#define ACTION_RIGHT 0x02
#define ACTION_OVER 0X03
#define ACTION_START 0x04
#define ACTION_SHAKING 0x05
#define ACC_DATA_CON_NUM 120
#define GYRO_RNG 2
#define ACCEL_RNG 3
#define LIGHT_MODE_CLOCK 0x10
#define LIGHT_MODE_RUNNING 0x11
#define LIGHT_MODE_ALARM 0X12
#define LIGHT_MODE_RIDING 0x13
#define LIGHT_MODE_WARM_LIGHTING 0x14
#define LIGHT_MODE_CO_LIGHTING 0x15
#define LIGHT_MODE_TIMING_FIT 0x16
#define LIGHT_MODE_TIMING_LAND 0x17
#define LIGHT_MODE_COMFOR 0x18
#define LIGHT_MODE_MUSIC 0x19
#define LIGHT_MODE_ANIMATION 0x1a
#define LIGHT_MODE_WEATHER 0X1b
#define LIGHT_MODE_SHAKING 0x1c
#define LIGHT_MODE_SOS 0x1d
#define FREQUENCY_SLOW 4
#define FREQUENCY_NORMAL 3
#define FREQUENCY_FAST 2
#define FREQUENCY_VERY_FAST 1
#define fft_16
#define fft_N 16
#define M 4
#define MPU_PERIOD_TICK 15
#define REC_PERIOD_TICK 30
#define MIC_PERIOD_TICK 5
#define ALARM_PERIOD_TICK 15000
#define INIT_MODE 0x11
#define INIT_BRIGHT 0
#define INIT_FREQUENCE 0
#define INIT_TIME 0
#define INIT_TEMPERTURE 0
#define INIT_HUMIDITY 0
#define INIT_WEATHER 0
#define FANCE_TXT_LEN_MAX 20
#define LED_WAIT_TIME_MAX 1000
#define MIN_MODE LIGHT_MODE_RUNNING
#define MAX_MODE LIGHT_MODE_SOS
#define MIN_BRIGHT 1
#define MAX_BRIGHT 127
#define INIT_MODE_INFO
Typedefs
typedef struct _rtc _RTC
typedef struct acc_upbuf ACC_UPBUF
typedef struct acc_special ACC_SPECIAL
typedef struct imu_mpu6050_update MPU050_UPDATA
typedef struct imu_mpu6050_update * MPU050_UPDATA_PTR
Functions
static void iic_mpu6050_int (void)
Initialize the IIC device and set the slave address to MPU6050.
static void mpu6050_write_reg (uint8_t regaddr, uint8_t val)
MPU6050 write register function.
static uint8_t mpu6050_read_reg (uint8_t regaddr)
MPU6050 read register function.
void mpu6050_init (uint8_t gyro_rng, uint8_t accel_rng)
MPU6050 init.
void iic_point_mpu (void)
Set the IIC slave address to MPU6050.
int mpu6050_get_data (uint8_t regaddr)
Get the MPU6050 data.
void light_ctr_gpio_init ()
Initialize light control gpio.2 pins will be initialized in this function,and output low after initialization.
void light_send_bit_0 (uint16_t row)
The light control function sends one bit data,0.The duration of the high level is 0.35us, the error is 150ns.The duration of the low level is 0.8us,the error is 150ns.
void light_ctr_reset ()
reset side row led
void light_send_bit_1 (uint16_t row)
The light control function sends one bit data,1.
void light_send_colordata (uint32_t color_data, uint16_t row)
Send 24 bits data to control one led.
void delay_10us (uint32_t mul)
Delay 10 us.
void light_ctr_rgb (uint64_t mask, uint16_t row, uint8_t red, uint8_t green, uint8_t blue)
Lighting control function.
uint64_t light_ctr_mask_lshift (uint64_t aim_num, uint64_t shift_num)
Perform a left shift operation on the parameter.
void light_ctr_rgb_update (uint64_t mask, uint16_t row, uint8_t red, uint8_t green, uint8_t blue)
void pcf8563_iic_init ()
initialize pcf8563
void pcf8653_write_data (uint8_t address, uint8_t time_data)
Write one byte date to RTC.
uint8_t he2bcd (uint8_t num)
Converts data from decimal to BCD.
void pcf8563_data_read (uint8_t address, uint8_t count, uint8_t *buff)
Read data from pcf8563.
void pcf8563_bcd2de ()
Converts data from BCD to decimal.
void iic0_point_rtc (void)
make the slave device of iic be rtc.
uint8_t pcf8563_date_updata (uint8_t clock_day, uint8_t clock_hour, uint8_t clock_min)
updata the time data.
void P8563_settime ()
Set the time value 8.
void P8563_init ()
Set initial time of 13:13:30,06,27,TUE,2017.
void cnt_stop ()
Set initial time of 13:13:30,06,27,TUE,2017.
void cnt_start (uint8_t time)
Set initial time of 13:13:30,06,27,TUE,2017.
void check_cnt ()
Set initial time of 13:13:30,06,27,TUE,2017.
void pcf8653_time_reset (uint8_t week, uint8_t hour, uint8_t minute, uint8_t sec)
void light_show_word (uint8_t num)
Show a word num The word you want to show according to the model matrix.
static void ble_rx_state_second (mode_info *ble_mode_info_ptr, uint8_t *ble_rx_handle_ptr, uint8_t data)
Function for deviding music mode and comfortable mode.
static void ble_rx_state_third (mode_info *ble_mode_info_ptr, uint8_t *ble_rx_handle_ptr, uint8_t data)
Function for deviding weather moderunning modealarm moderiding modelighting modeclock modetime mode and fans mode.
static void ble_rx_state_forth (mode_info *ble_mode_info_ptr, uint8_t *ble_rx_handle_ptr, uint8_t data)
Function for deviding weather moderunning modealarm moderiding mode lighting modeclock modetime mode and fans mode.
Inline void ble_data_recesive (uint8_t data)
Recive data from bluetooth.
static void ble_irs (void *ptr)
The isr of bluetooth.
uint32_t ble_uart_init (uint32_t baudrate)
Initialize the bluetooth device.
uint32_t ble_send (uint8_t *psend, uint8_t cnt)
Send data by bluetooth.
void imu_init (uint8_t gyro_rng, uint8_t acc_rng)
Init the device which is used to get data of acceleration.
void imu_get_stastp_point (void)
Get the start and stop point and set the first position of partern_rec_startflag.
void imu_shaing_get_stastp_point (void)
Get the start and stop point of shaking and set the first position of partern_rec_startflag.
int8_t imu_get_shaking_start (void)
Get the point of start of shaking.
void imu_acc_feature_get (int32_t *point, float multi_throd, uint32_t *recognition, uint8_t *peak_order, uint8_t peak_flag)
Get some features of the data of action that is caputured.
void imu_mpu6050_update (void)
Update x_axis,y_axis,z_axis's date of acceleration an filter.
uint8_t imu_get_action_shaking (void)
According to the data that buffered,recongnize the action of shaking.
uint8_t imu_pattern_recongnition (void)
Recongnize the type of action and return value related.
void light_mode_test (void)
Test light in different color.
void light_ctr_init (void)
Init those Pmods which is used to control lights.
void light_mode_alloff (void)
Turn off all the lights.
void light_mode_change_success (void)
Show the mode change successfully.
void light_mode_music (uint8_t *fftOut)
Music mode.
void light_mode_change_flag (uint8_t mode)
used to indicates that the ilight is switching mode and different color represents different mode
void light_mode_top_pack (uint8_t mode, uint8_t bri, uint8_t freq, uint8_t time, uint8_t *string, uint8_t weather)
Light control function Top pack.
void fft_Data (uint16_t *fftIn, compx *fftData)
fast fourier transform step1 (prepar).
void fft_Convert (compx *xin)
fast fourier transform step2 (transform).
void fft_powerMag (compx *fftData, uint8_t *fftOut)
fast fourier transform step3 (compress).
uint8_t adc_get (void)
Adc value get of mic.
void mic_init (void)
Initial the mic.
void iic_point_mic (void)
IIC address point to mic.
static uint16_t crc_check (uint8_t *pbuf, uint8_t crc_cnt)
CRC check.
uint32_t scope_init (uint32_t baudrate)
Initial the scope.
uint32_t output_data (int16_t *out_data)
Output the date to scope.
void main ()
uint8_t task_init (void)
create all the task at appropriate order.
Variables
static DEV_IIC * mpu_iic_port
static uint32_t point = (MUPADDRESS >> 1)
uint8_t color_row
uint8_t light_num
static RGB_T ilight_middle [LIGHT_NUM_MIDDLE]
Light control array definition.
static RGB_T ilight_side [LIGHT_NUM_SIDE]
Light control array definition.
static RGB_T * piLight
static DEV_GPIO_PTR port_gpio_middle
Some variables definition related gpio initialization .
static DW_GPIO_PORT_PTR port_middle
static DEV_GPIO_INFO_PTR port_info_ptr_middle
static DEV_GPIO_PTR port_gpio_side
Some variables definition related gpio initialization .
static DW_GPIO_PORT_PTR port_side
static DEV_GPIO_INFO_PTR port_info_ptr_side
static uint32_t low_val_middle = 0
static uint32_t low_val_side = 0
static uint32_t temp_reg_middle
static uint32_t temp_reg_side
volatile uint32_t delay_num
uint8_t color_row
uint8_t light_num
DEV_IIC * IIC_port
uint32_t point = (RTC_ADDR_IIC >> 1)
_RTC rtc
DEV_GPIO_PTR port_gpio_rtc
DW_GPIO_PORT_PTR port_rtc
DEV_GPIO_INFO_PTR port_info_ptr_rtc
DEV_GPIO_INT_CFG_PTR port_int_ptr_rtc
DEV_GPIO_BIT_ISR_PTR port_isr_ptr_rtc
_RTC rtc
uint64_t word [26][8]
static DEV_UART * ble_uart
static uint8_t ble_rx_buffer
static DEV_BUFFER ble_uart_int_buffer
static MPU050_UPDATA n_data
static ACC_UPBUF acc_upbuf
static ACC_SPECIAL acc_special_data
MPU050_UPDATA * imu_mpu6050_update_ptr = &n_data
static uint8_t partern_rec_startflag
Action captures state variables.
static uint8_t shaking_rec_startflag
MPU050_UPDATA * imu_mpu6050_update_ptr
const int List [fft_N]
const float sin_tab [fft_N/2]
const float cos_tab [fft_N/2]
const int List [16]
const float sin_tab [8]
const float cos_tab [8]
static DEV_IIC * adc_iic_port
static DEV_UART * scope_uart
TaskHandle_t pattern_change_task_handle
SemaphoreHandle_t recognition_semaphore
QueueHandle_t led_queue
QueueHandle_t mode_info_queue
uint8_t color_row
uint8_t light_num
Detailed Description
embARC IOT iLight smartdevice
Extra Required Tools
Extra Required Peripherals
PCF8563 MPU6050 HM-10 MLX90614
Design Concept
All sensor modules should be connected to EMSK. This application is designed to make a smart device to facilitate the daily life.
Usage Manual
It can report the following information to the iLight.
- the Motion Intensity (uint16_t) - Connected to J3 (Based on Acceleration sensor)
- the MIC (uint8_t) - Connected to J3 (Based on AD conversion)
- the Middle lights(uint16_t) - Connected to J1
- the Side lights (uint64_t) - Connected to J4 (Based on Acceleration sensor)
Extra Comments
Macro Definition Documentation
#define ACCEL_RNG 3
MPU6050 data update structure
Definition at line 58 of file IMU.h.
#define ACCEL_XOUT_L 0x3C
Y-axis acceleration measurement value register,ACCEL_YOUT_H is those high 8 bits
Definition at line 56 of file mpu6050.h.
#define ACCEL_YOUT_L 0x3E
Z-axis acceleration measurement value register,ACCEL_ZOUT_H is those high 8 bits
Definition at line 59 of file mpu6050.h.
#define ACCEL_ZOUT_L 0x40
using IIC interface 0
Definition at line 62 of file mpu6050.h.
#define ACTION_LEFT 0x01
< The type of action definition
Definition at line 48 of file IMU.h.
Referenced by imu_pattern_recongnition(), and mpu_task().
#define ACTION_SHAKING 0x05
The max number of data
Definition at line 52 of file IMU.h.
Referenced by imu_get_action_shaking(), light_mode_fitness(), and light_mode_timing_land().
#define CLOCK_START 0x11
Some macro definitions of week's date
Definition at line 63 of file rtc.h.
Referenced by pcf8563_date_updata().
#define GPIO_H_CFG_SIDE (1 << GPIO_OUT_OFFSET_SIDE)
define led row to distinguish controller pin
Definition at line 56 of file light_driver.h.
Referenced by light_ctr_gpio_init().
#define GPIO_OUT_PORT_MIDDLE (DW_GPIO_PORT_A)
< using GPIO A11 & C19 as LED controller Pin
Definition at line 48 of file light_driver.h.
Referenced by light_ctr_gpio_init().
#define INIT_MODE_INFO
Value:
{       \
        INIT_MODE,              \
        INIT_BRIGHT,            \
        INIT_FREQUENCE,         \
        INIT_TIME,              \
        INIT_WEATHER,           \
        INIT_TEMPERTURE,        \
        INIT_HUMIDITY,          \
        {0}                     \
}
Definition at line 70 of file task.h.
#define LIGHT_MODE_CLOCK 0x10
< Light mode definition
Definition at line 48 of file light_mode.h.
Referenced by ble_rx_state_third().
#define LIGHT_MODE_SOS 0x1d
Frequency definition
Definition at line 61 of file light_mode.h.
Referenced by light_mode_change_flag(), and light_mode_top_pack().
#define LIGHT_ROW_SIDE 0x101
the led numbers of a row
Definition at line 60 of file light_driver.h.
Referenced by light_change_alldouble(), light_mode_alarm(), light_mode_alloff(), light_mode_animation(), light_mode_change_flag(), light_mode_change_success(), light_mode_fitness(), light_mode_lighting_cold(), light_mode_lighting_warm(), light_mode_music(), light_mode_ride(), light_mode_run(), light_mode_sos(), light_mode_test(), light_mode_timing_land(), and light_mode_weather().
#define MPU6050_IIC_NUM DW_IIC_0_ID
MPU6050 init function.parameter: gyro_rng,gyro parameter setting,0(250/s),1(500/2),2(1000/s),3(2000/s)
Definition at line 65 of file mpu6050.h.
Referenced by iic_mpu6050_int().
#define MUPADDRESS 0xD0
<IIC write when the address byte data, + 1 for the read X-axis acceleration measurement value register,ACCEL_XOUT_H is those high 8 bits
Definition at line 53 of file mpu6050.h.
#define RTC_ADDR_HOUR 0x04
The macro definition of register date of minute
Definition at line 57 of file rtc.h.
#define RTC_ADDR_IIC 0xa2
Some macro definitions of date register The macro definition of IIC address of RTC device.
The macro definition of register date of week
Definition at line 53 of file rtc.h.
#define RTC_ADDR_MIN 0x03
The macro definition of register date of second
Definition at line 59 of file rtc.h.
#define RTC_ADDR_WEEK 0x06
The macro definition of register date of hour
Definition at line 55 of file rtc.h.
Function Documentation
uint8_t adc_get (void)
Adc value get of mic.
Get the adc value of mic using iic0.
Parameters
[out] the value of adc convert
Definition at line 54 of file mic.c.
Referenced by light_mode_music_task().
Inline void ble_data_recesive (uint8_t data)
Recive data from bluetooth.
Transfer the data to the useful format.
Parameters
data:the data received
Definition at line 318 of file ble_int.c.
References ble_rx_state_forth(), ble_rx_state_second(), and ble_rx_state_third().
Referenced by ble_irs().
static void ble_irs (void * ptr) static
The isr of bluetooth.
The callback function of bluetooth isr.
Parameters
ptr nonsense
Definition at line 344 of file ble_int.c.
References ble_data_recesive(), E_OK, UART_CMD_SET_RXINT, UART_CMD_SET_RXINT_BUF, and dev_uart::uart_control.
Referenced by ble_uart_init().
static void ble_rx_state_second (mode_info * ble_mode_info_ptr, uint8_t * ble_rx_handle_ptr, uint8_t data) static
Function for deviding music mode and comfortable mode.
Parameters
[in] ble_mode_info_ptr. used to trans data received.
[in] ble_rx_handle_ptr.
[in] data.used to judge mode.
Definition at line 114 of file ble_int.c.
Referenced by ble_data_recesive().
uint32_t ble_send (uint8_t * psend, uint8_t cnt)
Send data by bluetooth.
Send cnt bytes using bluetooth in uart0.
Parameters
psend the buffer of date sended in uart0 cnt: the number of bytes to send
-1 for error 0 for succeed
Definition at line 411 of file ble_int.c.
References dev_uart::uart_write.
uint32_t ble_uart_init (uint32_t baudrate)
Initialize the bluetooth device.
Initialize the uart0 driver for bluetooth
Parameters
baudrate the baudrate of uart0
-1 for error,0 for succeed
Function for sending data to bluetooth
Definition at line 370 of file ble_int.c.
References ble_irs(), DEV_BUFFER_INIT, DW_UART_0_ID, E_OK, E_OPNED, UART_CMD_SET_BAUD, UART_CMD_SET_RXCB, UART_CMD_SET_RXINT, UART_CMD_SET_RXINT_BUF, dev_uart::uart_control, uart_get_dev(), and dev_uart::uart_open.
static uint16_t crc_check (uint8_t * pbuf, uint8_t crc_cnt) static
CRC check.
Software crc check.
Parameters
pbuf the buffer of date to crc check,crc_cnt: the number of bytes to crc check
the result of crc check
Definition at line 61 of file scope.c.
Referenced by output_data().
void delay_10us (uint32_t mul)
Delay 10 us.
Implement the delay effect by executing empty statement. parameter mul One unit represents 10 us.
Definition at line 241 of file light_driver.c.
Referenced by led_display_task(), light_ctr_reset(), and light_ctr_rgb().
void fft_Convert (compx * xin)
fast fourier transform step2 (transform).
fast fourier transform step2.
fast fourier transform the data in array.
Parameters
[in] the pointer of input data array and the result would be store in this array after transform.
Definition at line 70 of file fft.c.
Referenced by light_mode_music_task().
void fft_Data (uint16_t * fftIn, compx * fftData)
fast fourier transform step1 (prepar).
fast fourier transform step1.
Transform real number data to complex number data struct.
Parameters
[in] the pointer of adc data array.
[in] the pointer of output complex number data struct.
Definition at line 56 of file fft.c.
Referenced by light_mode_music_task().
void fft_powerMag (compx * fftData, uint8_t * fftOut)
fast fourier transform step3 (compress).
fast fourier transform step3.
reduce the size of data by calculate the absolute value of complex data.
Parameters
[in] the pointer of the complex data after transform.
[in] the pointer of the array storing the compress data.
Definition at line 102 of file fft.c.
Referenced by light_mode_music_task().
uint8_t he2bcd (uint8_t num)
Converts data from decimal to BCD.
num The data you want to convert
Return values
num The data after converting
Definition at line 102 of file rtc.c.
void iic_point_mic (void)
IIC address point to mic.
IIC address point to mic.
Definition at line 80 of file mic.c.
References E_OK, IIC_CMD_MST_SET_TAR_ADDR, and dev_iic::iic_control.
Referenced by pattern_change_task().
void imu_acc_feature_get (int32_t * point, float multi_throd, uint32_t * recognition, uint8_t * peak_order, uint8_t peak_flag)
Get some features of the data of action that is caputured.
Parameters
*point The address of the highest bit 0f the acceleration buffer that need to obtain the eigenvalue.
multi_throd Set the threshold for positive and negative feature judgments.z:0.3,y:0.4.
recognition. The value of the wave of action.Set the last 2 bits PEAK_WAVE_NEGATIVE when get a negative peak.
peak_order. The order of the peak of y axies or z axies.
peak_flag. Sign of get the position of first positive or negative peak.
Definition at line 207 of file IMU.c.
Referenced by imu_get_action_shaking(), and imu_pattern_recongnition().
uint8_t imu_get_action_shaking (void)
According to the data that buffered,recongnize the action of shaking.
Return values
ACTION_SHAKING. Capture the action of shaking.
1 Not get the action of shaking.
Definition at line 380 of file IMU.c.
References ACTION_SHAKING, imu_acc_feature_get(), imu_get_stastp_point(), and imu_shaing_get_stastp_point().
Referenced by light_mode_fitness(), and light_mode_timing_land().
int8_t imu_get_shaking_start (void)
Get the point of start of shaking.
Return values
ACTION_START Get the start point of shaking.
1 Not get the start point.
function get the action of shaking
Definition at line 189 of file IMU.c.
Referenced by light_mode_shaking().
void imu_init (uint8_t gyro_rng, uint8_t acc_rng)
Init the device which is used to get data of acceleration.
gyro_rng Set the range of gyro,0(250 degree/s),1(500 degree/2),2(1000 degree/s),3(2000 degree/s). accel_rng Set the range of accelerometer,0(2g),1(4g),2(8g),3(16g).
function pattern recognition
Definition at line 129 of file IMU.c.
References mpu6050_init().
void imu_mpu6050_update (void)
Update x_axis,y_axis,z_axis's date of acceleration an filter.
Parameters
none.
Definition at line 300 of file IMU.c.
References mpu6050_get_data(), and partern_rec_startflag.
Referenced by mpu_task().
uint8_t imu_pattern_recongnition (void)
Recongnize the type of action and return value related.
Return values
ACTION_START Captured the action of T whiched represent the sign of mode changing.
ACTION_LEFT Captured the action of LEFT which represent change mode in left.
ACTION_RIGHT Captured the action of RIGHT which represent change mode in right.
ACTION_OVER Captured the action of ACTION_OVER which represent the sign of stop mode changing. 0 Can't recongnize the type of action.
function get the start of action of shaking,used in light_mode_word()
Definition at line 411 of file IMU.c.
References ACTION_LEFT, imu_acc_feature_get(), imu_get_stastp_point(), and partern_rec_startflag.
Referenced by mpu_task().
uint64_t light_ctr_mask_lshift (uint64_t aim_num, uint64_t shift_num)
Perform a left shift operation on the parameter.
Because the translater will set those bits which is higher than 32 high,so if you want to avoid this bug you have to set at least one bit high which is higher than 32.
Parameters
aim_num The number which you want to perform.
shift num How many bits you want to shift.
Return values
aim_num<<shift_num
Definition at line 296 of file light_driver.c.
Referenced by light_mode_ride(), and light_mode_timing_land().
void light_ctr_rgb (uint64_t mask, uint16_t row, uint8_t red, uint8_t green, uint8_t blue)
Lighting control function.
Update specify arrays and send those arrays to control lamp beats.
Parameters
mask Those bits which are setted one mark those lamp beats that are going to be changed.
row Indicates which pin is going to send data.If it is not LIGHT_ROW_MIDDLE,it will be LIGHT_SIDE by default.
rgb The data of clolor.
Definition at line 255 of file light_driver.c.
References delay_10us(), ilight_middle, ilight_side, and light_num.
Referenced by light_change_alldouble(), light_mode_alarm(), light_mode_alloff(), light_mode_animation(), light_mode_change_flag(), light_mode_change_success(), light_mode_comfor(), light_mode_fitness(), light_mode_lighting_cold(), light_mode_lighting_warm(), light_mode_music(), light_mode_ride(), light_mode_run(), light_mode_sos(), light_mode_test(), light_mode_timing_land(), light_mode_weather(), and light_show_word().
void light_mode_alloff (void)
Turn off all the lights.
Send 0x00,0x00,0x00 to all the lights to turn off lights.
Definition at line 145 of file light_mode.c.
References light_ctr_rgb(), and LIGHT_ROW_SIDE.
Referenced by light_change_alldouble(), light_mode_alarm(), light_mode_change_flag(), light_mode_change_success(), light_mode_fitness(), light_mode_music(), light_mode_run(), light_mode_shaking(), light_mode_sos(), light_mode_timing_land(), and light_mode_weather().
void light_mode_change_flag (uint8_t mode)
used to indicates that the ilight is switching mode and different color represents different mode
Parameters
mode. The number of mode right now.
Definition at line 906 of file light_mode.c.
References light_change_alldouble(), light_ctr_rgb(), light_mode_alloff(), LIGHT_MODE_SOS, and LIGHT_ROW_SIDE.
Referenced by mpu_task().
void light_mode_music (uint8_t * fftOut)
Music mode.
LED flash with music rhythm
Parameters
fftout Audio Signal after fft transform
Definition at line 581 of file light_mode.c.
References light_ctr_rgb(), light_mode_alloff(), and LIGHT_ROW_SIDE.
Referenced by light_mode_music_task().
void light_mode_top_pack (uint8_t mode, uint8_t bri, uint8_t freq, uint8_t time, uint8_t * string, uint8_t weather)
Light control function Top pack.
Parameters
mode The light mode that you want to choose.
bri The brightness of all lights.
freq The speed of lights moving.
time Used in timing mode.
string Used in shaking mode.
Definition at line 1006 of file light_mode.c.
References light_change_alldouble(), light_mode_alarm(), light_mode_animation(), light_mode_change_success(), light_mode_comfor(), light_mode_fitness(), light_mode_lighting_cold(), light_mode_lighting_warm(), light_mode_ride(), light_mode_run(), light_mode_shaking(), LIGHT_MODE_SOS, light_mode_sos(), light_mode_timing_land(), and light_mode_weather().
Referenced by light_mode_task().
void light_send_bit_0 (uint16_t row)
The light control function sends one bit data,0.The duration of the high level is 0.35us, the error is 150ns.The duration of the low level is 0.8us,the error is 150ns.
Parameters
row Indicates which pin is going to send data.If it is not LIGHT_ROW_MIDDLE,it will be LIGHT_SIDE by default.
Definition at line 143 of file light_driver.c.
References dw_gpio_port::no, and dw_gpio_port::regs.
Referenced by light_send_colordata().
void light_send_bit_1 (uint16_t row)
The light control function sends one bit data,1.
The duration of the high level is 0.7us,the error is 150ns.The duration of the low level is 0.6us,the error is 150ns.
Parameters
row Indicates which pin is going to send data.If it is not LIGHT_ROW_MIDDLE,it will be LIGHT_SIDE by default.
Definition at line 184 of file light_driver.c.
References dw_gpio_port::no, and dw_gpio_port::regs.
Referenced by light_send_colordata().
void light_send_colordata (uint32_t color_data, uint16_t row)
Send 24 bits data to control one led.
According to parameter send 24 bits color data to light one beat.
Parameters
color_data The low 24 bits of the parameter is effective.
row Indicates which pin is going to send data.If it is not LIGHT_ROW_MIDDLE,it will be LIGHT_SIDE by default.
Definition at line 223 of file light_driver.c.
References light_send_bit_0(), and light_send_bit_1().
Referenced by led_display_task().
void mic_init (void)
Initial the mic.
Initial the mic using iic0.
Definition at line 68 of file mic.c.
References DW_IIC_0_ID, and iic_get_dev().
int mpu6050_get_data (uint8_t regaddr)
Get the MPU6050 data.
regaddr the address of the register that you want to get.
Return values
data the data you get after processing
Make the IIC point to mpu
Definition at line 180 of file mpu6050.c.
References mpu6050_read_reg().
Referenced by imu_mpu6050_update().
void mpu6050_init (uint8_t gyro_rng, uint8_t accel_rng)
MPU6050 init.
Parameters
gyro_rng Set the range of gyro,0(250 degree/s),1(500 degree/2),2(1000 degree/s),3(2000 degree/s).
accel_rng Set the range of accelerometer,0(2g),1(4g),2(8g),3(16g).
Get the specify register data
Definition at line 134 of file mpu6050.c.
References iic_mpu6050_int(), mpu6050_write_reg(), and SMPLRT_DIV.
Referenced by imu_init().
static uint8_t mpu6050_read_reg (uint8_t regaddr) static
MPU6050 read register function.
regaddr The address of the register that you want to write.
Return values
The valuation of the register.
Definition at line 116 of file mpu6050.c.
References IIC_CMD_MST_SET_NEXT_COND, dev_iic::iic_control, IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by mpu6050_get_data().
static void mpu6050_write_reg (uint8_t regaddr, uint8_t val) static
MPU6050 write register function.
regaddr The address of the register that you want to write. val The valuation that you want to write.
Definition at line 97 of file mpu6050.c.
References IIC_CMD_MST_SET_NEXT_COND, dev_iic::iic_control, IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by mpu6050_init().
uint32_t output_data (int16_t * out_data)
Output the date to scope.
Output the date to scope.
Parameters
[in] out_data four date sended to scope
[out] -1 for error, 0 for succeed
Definition at line 109 of file scope.c.
References crc_check(), and dev_uart::uart_write.
void pcf8563_data_read (uint8_t address, uint8_t count, uint8_t * buff)
Read data from pcf8563.
Parameters
address The address of data you want to read
count The length of data
buff The data read buff
Definition at line 117 of file rtc.c.
References E_OK, IIC_CMD_MST_SET_NEXT_COND, dev_iic::iic_control, IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by check_cnt(), and pcf8563_date_updata().
void pcf8563_iic_init (void)
initialize pcf8563
Update the date of week,hour,minute,and second
Definition at line 61 of file rtc.c.
References DEV_MASTER_MODE, DW_IIC_0_ID, E_OK, IIC_CMD_ENA_DEV, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, and IIC_SPEED_STANDARD.
void pcf8653_write_data (uint8_t address, uint8_t time_data)
Write one byte date to RTC.
address Befor write dataake the slave device address point to pcf8653. time_data The time data you want to write
Definition at line 83 of file rtc.c.
References E_OK, IIC_CMD_MST_SET_NEXT_COND, dev_iic::iic_control, IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by check_cnt(), cnt_start(), cnt_stop(), and P8563_settime().
uint32_t scope_init (uint32_t baudrate)
Initial the scope.
Initial the scope using uart0
Parameters
[in] baudrate the baudrate of uart0
[out] -1 for error, 0 for succeed
< Initial the scope using uart0
< Attention: only use without blueteeth Output the date to scope
Definition at line 86 of file scope.c.
References DW_UART_0_ID, E_OPNED, UART_CMD_SET_BAUD, dev_uart::uart_control, uart_get_dev(), and dev_uart::uart_open.
Variable Documentation
const float cos_tab[8]
Initial value:
= {
        1.0000, 0.9239, 0.7071, 0.3827, 0.0000, -0.3827, -0.7071, -0.9239
}
Definition at line 55 of file fft_tab.c.
RGB_T ilight_middle[LIGHT_NUM_MIDDLE] static
Light control array definition.
Middle row of the lamp beads.
Definition at line 61 of file light_driver.c.
Referenced by light_ctr_rgb().
RGB_T ilight_side[LIGHT_NUM_SIDE] static
Light control array definition.
Both sides of the lamp beads.
Definition at line 67 of file light_driver.c.
Referenced by light_ctr_rgb().
MPU050_UPDATA* imu_mpu6050_update_ptr
function init the mpu6050
Definition at line 72 of file IMU.h.
Referenced by light_mode_ride().
uint8_t light_num
The underlying lighting control module function
Definition at line 55 of file light_driver.c.
Referenced by led_display_task(), and light_ctr_rgb().
uint8_t light_num
The underlying lighting control module function
Definition at line 55 of file light_driver.c.
uint8_t light_num
The underlying lighting control module function
Definition at line 55 of file light_driver.c.
Referenced by led_display_task(), and light_ctr_rgb().
const int List[16]
Initial value:
= {
        0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15
}
Definition at line 51 of file fft_list.c.
uint8_t partern_rec_startflag static
Action captures state variables.
7 bit Capture success flag,1 represents one capture is complete 6:1 bit The type of action which is captured. 0 bit Set 1 if capture the start signal of action.
Definition at line 121 of file IMU.c.
Referenced by imu_get_stastp_point(), imu_mpu6050_update(), and imu_pattern_recongnition().
DEV_GPIO_PTR port_gpio_middle static
Some variables definition related gpio initialization .
Middle row of lights.
Definition at line 74 of file light_driver.c.
DEV_GPIO_PTR port_gpio_side static
Some variables definition related gpio initialization .
Middle row of lights.
Definition at line 82 of file light_driver.c.
_RTC rtc
Initialize the RTC's IIC device
Definition at line 56 of file rtc.c.
_RTC rtc
Initialize the RTC's IIC device
Definition at line 56 of file rtc.c.
const float sin_tab[8]
Initial value:
= {
        -0.0000, -0.3827, -0.7071, -0.9239, -1.0000, -0.9239, -0.7071, -0.3827
}
Definition at line 51 of file fft_tab.c.
uint64_t word[26][8]
Initial value:
=       {
                {0x0000, 0x0700, 0x3800, 0xc800, 0x3800, 0x0700, 0x0000}, {0x0000, 0xff00, 0x9100, 0x9100, 0x9100, 0x6e00, 0x0000},
                {0x0000, 0x7e00, 0x8100, 0x8100, 0x8100, 0x4200, 0x0000}, {0x0000, 0xff00, 0x8100, 0x8100, 0x8100, 0x4200, 0x3c00},
                {0x0000, 0xff00, 0x9100, 0x9100, 0x9100, 0x9100, 0x0000}, {0x0000, 0xff00, 0x9000, 0x9000, 0x9000, 0x9000, 0x0000},
                {0x0000, 0x3c00, 0x4200, 0x8100, 0x8900, 0x8900, 0x4e00}, {0x0000, 0x7f00, 0x0800, 0x0800, 0x0800, 0x7f00, 0x0000},
                {0x0000, 0x8100, 0x8100, 0xff00, 0x8100, 0x8100, 0x0000}, {0x0000, 0x0400, 0x8200, 0x8200, 0xfc00, 0x8000, 0x0000},
                {0x0000, 0x7f00, 0x0800, 0x1400, 0x2200, 0x0000, 0x0000},
        {0x3000, 0x7800, 0x7c00, 0x3e00, 0x7c00, 0x7800, 0x3000},
                {0X3f00, 0x4000, 0x3800, 0x0600, 0x3800, 0x4000, 0X3f00}, {0x0000, 0x7f00, 0x6000, 0x3800, 0x0c00, 0x0600, 0xef00},
                {0X3c00, 0x4200, 0x8100, 0x8100, 0x8100, 0x4200, 0X3c00}, {0x0000, 0xff00, 0x8800, 0x8800, 0x8800, 0x7000, 0X0000},
                {0x0000, 0X3c00, 0x4200, 0x8100, 0x8500, 0x4200, 0X3d00}, {0x0000, 0xff00, 0x9800, 0x9c00, 0x9600, 0x9300, 0x6100},
                {0x0000, 0x6200, 0x9100, 0x9100, 0x8900, 0x8600, 0X0000}, {0x0000, 0x8000, 0x8000, 0xff00, 0x8000, 0x8000, 0X0000},
                {0x0000, 0xfc00, 0x0200, 0x0100, 0x0100, 0x0200, 0xfc00}, {0xe000, 0x1c00, 0x0200, 0x0100, 0x0200, 0x1c00, 0xe000},
                {0xe000, 0x1c00, 0x0300, 0x1c00, 0x0300, 0x1c00, 0xe000}, {0x8100, 0x4200, 0x2400, 0x1800, 0x2400, 0x4200, 0x8100},
                {0x8000, 0x4000, 0x3000, 0x0f00, 0x3000, 0x4000, 0x8000}, {0x8100, 0x8300, 0x8d00, 0x9900, 0xb100, 0xc100, 0x8100}
}
Definition at line 50 of file word.c.