embARC: AXS 103 Interrupt Management
AXS 103 Interrupt Management
BSP Layer » AXS BSP » AXS 103
Files
file axs_103_interrupt.c
to add
file axs_103_interrupt.h
to add
Data Structures
struct dw_ictl_reg
struct ictl_gpio_reg
Typedefs
typedef volatile struct dw_ictl_reg DW_ICTL_REG
typedef volatile struct
dw_ictl_reg * DW_ICTL_REG_PTR
typedef volatile struct
ictl_gpio_reg ICTL_GPIO_REG
typedef volatile struct
ictl_gpio_reg * ICTL_GPIO_REG_PTR
Functions
void dw_ictl_int_enable (DW_ICTL_REG_PTR reg, uint32_t intno)
void dw_ictl_int_disable (DW_ICTL_REG_PTR reg, uint32_t intno)
uint32_t dw_ictl_int_enabled (DW_ICTL_REG_PTR reg, uint32_t intno)
uint32_t dw_ictl_int_probe (DW_ICTL_REG_PTR reg, uint32_t intno)
void dw_ictl_int_sw_trigger (DW_ICTL_REG_PTR reg, uint32_t intno)
void ictl_gpio_int_enable (ICTL_GPIO_REG_PTR reg, uint32_t intno)
void ictl_gpio_int_disable (ICTL_GPIO_REG_PTR reg, uint32_t intno)
uint32_t ictl_gpio_int_enabled (ICTL_GPIO_REG_PTR reg, uint32_t intno)
uint32_t ictl_gpio_int_probe (ICTL_GPIO_REG_PTR reg, uint32_t intno)
void ictl_gpio_int_level_config (ICTL_GPIO_REG_PTR reg, uint32_t intno, uint32_t level)
void ictl_gpio_int_polarity_config (ICTL_GPIO_REG_PTR reg, uint32_t intno, uint32_t polarity)
void ictl_gpio_int_clear (ICTL_GPIO_REG_PTR reg, uint32_t intno)
static void axs_103_int_handler_default (void *ptr)
static void dw_ictl_int_isr (void *ptr)
static void ictl_gpio_int_isr (void *ptr)
int32_t int_disable (const uint32_t intno)
disable the specific interrupt
int32_t int_enable (const uint32_t intno)
enable the specific int
int32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
int32_t int_ipm_get (void)
get the interrupt priority mask
int32_t int_ipm_set (int32_t intpri)
set the interrupt priority mask
int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
int32_t int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
int32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
int32_t int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
int32_t int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
void cpu_lock (void)
lock cpu, disable interrupts
void cpu_unlock (void)
unlock cpu, enable interrupts to happen
uint32_t cpu_lock_save (void)
lock cpu and staus
void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
void axs_interrupt_init (void)
Variables
static ICTL_GPIO_REG_PTR ictl_gpio_ptr = (ICTL_GPIO_REG_PTR)(REGBASE_ICTL_CPU)
static DW_ICTL_REG_PTR dw_ictl_ptr = (DW_ICTL_REG_PTR)(REGBASE_ICTL)
static INT_HANDLER axs_103_int_handler_table [NUM_INT_ALL]
Detailed Description
Function Documentation
uint32_t cpu_lock_save (void)
lock cpu and staus
lock cpu and return status
Returns
cpu status
Definition at line 490 of file axs_103_interrupt.c.
References arc_lock_save().
void cpu_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Parameters
[in] status cpu status saved by cpu_lock_save
Definition at line 500 of file axs_103_interrupt.c.
References arc_unlock_restore().
int32_t int_disable (const uint32_t intno)
disable the specific interrupt
Parameters
[in] intno interrupt number
Definition at line 246 of file axs_103_interrupt.c.
References arc_int_disable(), INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_enable (const uint32_t intno)
enable the specific int
Parameters
[in] intno interrupt number
Definition at line 271 of file axs_103_interrupt.c.
References arc_int_enable(), INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_enabled (const uint32_t intno)
check whether the specific int is enabled
Parameters
[in] intno interrupt number
Returns
0 disabled, 1 enabled, < 0 error
Definition at line 297 of file axs_103_interrupt.c.
References arc_int_enabled(), INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_ipm_get (void)
get the interrupt priority mask
Returns
interrupt priority mask, negative num
Definition at line 319 of file axs_103_interrupt.c.
References arc_int_ipm_get(), and INT_PRI_MIN.
int32_t int_ipm_set (int32_t intpri)
set the interrupt priority mask
Parameters
[in] intpri interrupt priority
Definition at line 330 of file axs_103_interrupt.c.
References arc_int_ipm_set(), INT_PRI_MAX, and INT_PRI_MIN.
int32_t int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Parameters
[in] intno interrupt number
[in] level,0-level trigger, 1-pluse triggered
Returns
0 ok, -1 error
Definition at line 449 of file axs_103_interrupt.c.
References arc_int_level_config(), INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_pri_get (const uint32_t intno)
get current interrupt priority mask
Parameters
[in] intno interrupt number
Returns
<0 interrupt priority, 0 error
Definition at line 348 of file axs_103_interrupt.c.
References arc_int_pri_get(), INT_PRI_MIN, INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_pri_set (const uint32_t intno, int32_t intpri)
set interrupt priority
Parameters
[in] intno interrupt number
[in] intpri interrupt priority
Definition at line 371 of file axs_103_interrupt.c.
References arc_int_pri_set(), INT_PRI_MIN, INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_probe (const uint32_t intno)
probe the pending status of interrupt
Parameters
[in] intno interrupt number
Returns
1 pending, 0 no pending, -1 error
Definition at line 399 of file axs_103_interrupt.c.
References arc_int_probe(), INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
int32_t int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Parameters
[in] intno interrupt number
Returns
0 ok, -1 error
Definition at line 423 of file axs_103_interrupt.c.
References arc_int_sw_trigger(), INTNO_ICTL_CPU, INTNO_ICTL_MB, and NUM_EXC_CPU.
Variable Documentation
INT_HANDLER axs_103_int_handler_table[NUM_INT_ALL] static
Initial value:
= {
        [0 ... NUM_INT_ALL-1] = axs_103_int_handler_default
}
Definition at line 207 of file axs_103_interrupt.c.