embARC: GPIO Device HAL Interface
GPIO Device HAL Interface
Device HAL » Device HAL Definition
definitions for gpio device hardware layer (dev_gpio.h)
Modules
GPIO Device Control Commands
Definitions for gpio control command, used in GPIO IO Control.
GPIO Device Int Configuration Settings
definition of gpio interrupt type
GPIO Device Interface Definition
contains definitions of gpio device structure.
GPIO Port Direction Definition
Define macros to indicate gpio directions.
Files
file dev_gpio.h
gpio device hardware layer definitions
Functions
DEV_GPIO_PTR gpio_get_dev (int32_t gpio_id)
get an gpio device by gpio device id.
Detailed Description
definitions for gpio device hardware layer (dev_gpio.h)
provide interfaces for gpio driver to implement Here is a diagram for the gpio interface.
GPIO Device HAL Interface Diagram
Function Documentation
DEV_GPIO_PTR gpio_get_dev (int32_t gpio_id)
get an gpio device by gpio device id.
For how to use gpio device hal refer to Functions in gpio device structure
Parameters
[in] gpio_id id of gpio, defined by user
Return values
!NULL pointer to an gpio device structure
NULL failed to find the gpio device by gpio_id
Note
need to implemented by user in user code
Definition at line 194 of file axs/drivers/gpio/dw_gpio_obj.c.
Referenced by axc003_gpio_init(), emsk_button_init(), emsk_led_init(), and emsk_switch_init().