embARC: embARC IoT iBaby Smarthome Node Wearable Node
embARC IoT iBaby Smarthome Node Wearable Node
embARC Applications » All embARC ApplicationsembARC Applications » embARC Applications for Different Operating Systems » | embARC FreeRTOS ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC LwIP ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC FatFS ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC AWS IoT Applications
embARC IoT iBaby Smarthome Node Wearable Node
Files
file acceleration.c
emsk acceleration sensor driver for ibaby wearable node
file acceleration.h
acceleration sensor driver related header file
file body_temperature.c
emsk temperature sensor driver for ibaby wearable node
file body_temperature.h
temperature sensor driver related header file
file heartrate.c
emsk heartrate sensor driver for ibaby wearable node
file heartrate.h
heartrate sensor driver related header file
file timer1.c
emsk timer1 for ibaby wearable node
file timer1.h
timer1 related header file
file wearable_node/function/lwm2m/lwm2m.c
function for LwM2M Client start
file wearable_node/function/print_msg/print_msg.c
function for print out message
file process_acc.c
function for acceleration data processing awake event detecting, sleep downward detecting, sleep monitoring
file process_acc.h
Header File of acceleration data processing function awake event detecting, sleep downward detecting, sleep monitoring.
file process_hrate.c
function for heartrate data processing
file application/ibaby_smarthome_multinode/src/wearable_node/lwm2m_client/lwm2mclient.c
Implementation for LwM2M client.
file application/ibaby_smarthome_multinode/src/wearable_node/main.c
main source of iBaby Smarthome Node Wearable Node
Data Structures
union _acc_data
struct __accValues
union _btemp_data
union _hrate_data
struct data_wearable_node
Macros
#define MPU6050_REG_SAMPLE_RATE 0x19 /* Gyro sample rate */
#define MPU6050_REG_EXT_SYNC_DISABLE 0x1A /* Ext sync disable */
#define MPU6050_REG_GYRO_FULL_SCALE 0x1B /* Gyro full scale */
#define MPU6050_REG_ACCEL_FULL_SCALE 0x1C /* Accel full scale */
#define MPU6050_REG_POWER_MANAGEMENT 0x6B /* Power management */
#define MPU6050_REG_ACCEL_XOUT_H 0x3B /* Accel_x out[15:8] */
#define MPU6050_REG_ACCEL_XOUT_L 0x3C /* Accel_x out[7:1] */
#define MPU6050_REG_ACCEL_YOUT_H 0x3D /* Accel_y out[15:8] */
#define MPU6050_REG_ACCEL_YOUT_L 0x3E /* Accel_y out[7:1] */
#define MPU6050_REG_ACCEL_ZOUT_H 0x3F /* Accel_z out[15:8] */
#define MPU6050_REG_ACCEL_ZOUT_L 0x40 /* Accel_z out[7:1] */
#define MPU6050_REG_TEMP_OUT_H 0x41 /* Temp out[15:8] */
#define MPU6050_REG_TEMP_OUT_L 0x42 /* Temp out[7:1] */
#define MPU6050_REG_GYRO_XOUT_H 0x43 /* Gyro_x out[15:8] */
#define MPU6050_REG_GYRO_XOUT_L 0x44 /* Gyro_x out[7:1] */
#define MPU6050_REG_GYRO_YOUT_H 0x45 /* Gyro_y out[15:8] */
#define MPU6050_REG_GYRO_YOUT_L 0x46 /* Gyro_y out[7:1] */
#define MPU6050_REG_GYRO_ZOUT_H 0x47 /* Gyro_z out[15:8] */
#define MPU6050_REG_GYRO_ZOUT_L 0x48 /* Gyro_z out[7:1] */
#define ACC_SENSOR_IIC_ID DW_IIC_1_ID
#define MPU6050_A0_PIN 0
I2C address of PmodIMU4 can be selected via AD0: 0x68, 0x69 AD0 connect to GND is 0x68.
#define MPU6050_ADDRESS (0x68 + MPU6050_A0_PIN)
#define ACC_SENSOR_ADDR MPU6050_ADDRESS
#define EMSK_IMU_SENSOR_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
#define TMP112_REG_TMP 0x00 /* Temperature Register */
#define TMP112_REG_CONG 0x01 /* Configuration Register */
#define TMP112_REG_TLOW 0x02 /* T Low Register */
#define TMP112_REG_THIGH 0x03 /* T High Register */
#define TMP112_CONFIG_OS (1 << 7)
#define TMP112_CONFIG_CC(x) ((x & 0x3) << 5)
#define TMP112_CONFIG_SD (1 << 0)
#define BTEMP_SENSOR_IIC_ID DW_IIC_1_ID
#define TMP112_ADDRESS 0x48
#define BTEMP_SENSOR_ADDR TMP112_ADDRESS
#define EMSK_TMP_SENSOR_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
#define MAX30102_REG_INT_STATUS_1 0x00 /* Interrupt status 1 */
#define MAX30102_REG_INT_STATUS_2 0x01 /* Interrupt status 2 */
#define MAX30102_REG_INT_ENABLE_1 0x02 /* Interrupt enable 1 */
#define MAX30102_REG_INT_ENABLE_2 0x03 /* Interrupt enable 2 */
#define MAX30102_REG_FIFO_WR_PTR 0x04 /* FIFO write pointer */
#define MAX30102_REG_OVF_COUNTER 0x05 /* FIFO overflow counter */
#define MAX30102_REG_FIFO_RD_PTR 0x06 /* FIFO read pointer */
#define MAX30102_REG_FIFO_DATA 0x07 /* FIFO data */
#define MAX30102_REG_FIFO_CONFIG 0x08 /* FIFO configuration */
#define MAX30102_REG_MODE_CONFIG 0x09 /* Mode configuration */
#define MAX30102_REG_SPO2_CONFIG 0x0A /* SpO2 configuration */
#define MAX30102_REG_LED_PULSE_AMP_1 0x0C /* LED pulse amplitude 1 */
#define MAX30102_REG_LED_PULSE_AMP_2 0x0D /* LED pulse amplitude 2 */
#define MAX30102_REG_PM_LED_PULSE_AMP 0x10 /* Proximity mode led pulse amplitude */
#define MAX30102_REG_MULTI_LED_MODE_CRTL_1 0x11 /* Multi-LED mode control registers 1 */
#define MAX30102_REG_MULTI_LED_MODE_CRTL_2 0x12 /* Multi-LED mode control registers 2 */
#define MAX30102_REG_DIE_TEMP_INTEGER 0x1F /* Die temp integer */
#define MAX30102_REG_DIE_TEMP_FRACTION 0x20 /* Die temp fraction */
#define MAX30102_REG_DIE_TEMP_CONFIG 0x21 /* Die temp configuration */
#define MAX30102_REG_PM_INT_THRESHOLD 0x30 /* Proximity interrupt threshold */
#define MAX30102_STATUS_PWR_RDY (1)
#define MAX30102_STATUS_PROX_INT (1 << 4)
#define MAX30102_STATUS_ALC_OVF (1 << 5)
#define MAX30102_STATUS_PPG_RDY (1 << 6)
#define MAX30102_STATUS_A_FULL (1 << 7)
#define MAX30102_STATUS_DIE_TEMP_RDY (1 << 1)
#define MAX30102_CONFIG_FIFO_A_FULL(x) (x & 0xf)
#define MAX30102_CONFIG_FIFO_ROL_LOVER_EN (1 << 4)
#define MAX30102_CONFIG_SMP_AVE(x) ((x & 0x7) << 4)
#define MAX30102_CONFIG_MODE(x) (x & 0x7)
#define MAX30102_CONFIG_RESET (1 << 6)
#define MAX30102_CONFIG_SHDN (1 << 7)
#define MAX30102_CONFIG_LED_PW(x) (x & 0x3)
#define MAX30102_CONFIG_SPO2_SR(x) ((x & 0x7) << 2)
#define MAX30102_CONFIG_SPO2_ADC_REG(x) ((x & 0x3) << 5)
#define MAX30102_CONFIG_LED_PA_1(x) (x & 0xFF)
#define MAX30102_CONFIG_LED_PA_2(x) (x & 0xFF)
#define MAX30102_CONFIG_PM_LED_PA(x) (x & 0xFF)
#define MAX30102_CONFIG_FIFO_A_0_FULL 0 /* EMPTY DATA SAMPLES IN FIFO:0 / UNREAD:32 */
#define MAX30102_CONFIG_FIFO_A_1_FULL 1 /* EMPTY DATA SAMPLES IN FIFO:1 / UNREAD:31 */
#define MAX30102_CONFIG_FIFO_A_2_FULL 2 /* EMPTY DATA SAMPLES IN FIFO:2 / UNREAD:30 */
#define MAX30102_CONFIG_FIFO_A_3_FULL 3 /* EMPTY DATA SAMPLES IN FIFO:3 / UNREAD:29 */
#define MAX30102_CONFIG_FIFO_A_F_FULL 15 /* EMPTY DATA SAMPLES IN FIFO:15 / UNREAD:17 */
#define MAX30102_CONFIG_SMP_1_AVE 0 /* NO 1.of samples averaged per FIFO sample */
#define MAX30102_CONFIG_SMP_2_AVE 1 /* NO 2.of samples averaged per FIFO sample */
#define MAX30102_CONFIG_SMP_4_AVE 2 /* NO 4.of samples averaged per FIFO sample */
#define MAX30102_CONFIG_SMP_8_AVE 3 /* NO 8.of samples averaged per FIFO sample */
#define MAX30102_CONFIG_SMP_16_AVE 4 /* NO 16.of samples averaged per FIFO sample */
#define MAX30102_CONFIG_SMP_32_AVE 5 /* NO 32.of samples averaged per FIFO sample */
#define MAX30102_CONFIG_HR_MODE 2 /* Heart Rate mode LED CHANNELS:Red only */
#define MAX30102_CONFIG_SPO2_MODE 3 /* SpO2 mode LED CHANNELS:Red and IR */
#define MAX30102_CONFIG_MUTLI_LED_MODE 7 /* Multi-LED mode LED CHANNELS:Red and IR */
#define MAX30102_CONFIG_LED_69_PW 0 /* ADC resolution(bits):15 */
#define MAX30102_CONFIG_LED_118_PW 1 /* ADC resolution(bits):16 */
#define MAX30102_CONFIG_LED_215_PW 2 /* ADC resolution(bits):17 */
#define MAX30102_CONFIG_LED_411_PW 3 /* ADC resolution(bits):18 */
#define MAX30102_CONFIG_SPO2_50_SR 0 /* SAMPLE PER SECOND:50 */
#define MAX30102_CONFIG_SPO2_100_SR 1 /* SAMPLE PER SECOND:100 */
#define MAX30102_CONFIG_SPO2_200_SR 2 /* SAMPLE PER SECOND:200 */
#define MAX30102_CONFIG_SPO2_400_SR 3 /* SAMPLE PER SECOND:400 */
#define MAX30102_CONFIG_SPO2_800_SR 4 /* SAMPLE PER SECOND:800 */
#define MAX30102_CONFIG_SPO2_1000_SR 5 /* SAMPLE PER SECOND:1000 */
#define MAX30102_CONFIG_SPO2_1600_SR 6 /* SAMPLE PER SECOND:1600 */
#define MAX30102_CONFIG_SPO2_3200_SR 7 /* SAMPLE PER SECOND:3200 */
#define MAX30102_CONFIG_SPO2_ADC_0_REG 0 /* ADC LSB SIZE:7.81 FULL SCALE:2048 */
#define MAX30102_CONFIG_SPO2_ADC_1_REG 1 /* ADC LSB SIZE:15.63 FULL SCALE:4096 */
#define MAX30102_CONFIG_SPO2_ADC_2_REG 2 /* ADC LSB SIZE:31.25 FULL SCALE:8192 */
#define MAX30102_CONFIG_SPO2_ADC_3_REG 3 /* ADC LSB SIZE:62.5 FULL SCALE:16384 */
#define HRATE_SENSOR_IIC_ID DW_IIC_1_ID
#define MAX30102_ADDRESS 0x57
#define HRATE_SENSOR_ADDR MAX30102_ADDRESS
#define EMSK_HEART_RATE_SENSOR_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
#define T1_COUNT_UNIT_LMS (2000) /* counting accuracy of Timer1: 0.1ms */
#define STACK_DEPTH_LWM2M (20480) /* stack depth for lwm2mClient : word(4*bytes) */
#define STACK_DEPTH_ACC (1024) /* stack depth for heartrate detector : word(4*bytes) */
#define TIME_DELAY_ACC_MS (31) /* acceleration sampling frequency: 30Hz */
#define THOLD_CNT_AW (150) /* threshold of counter(5s) for executing awake event detecting algorithm */
#define THOLD_CNT_SL (1760) /* threshold of counter(1min1760) for executing sleep monitoring algorithm */
#define THOLD_CNT_BTEMP (1760) /* threshold of counter(1min1760) for body temperature sampling time */
#define WARN_BTEMP_L (350) /* lower value of warning body temperature */
#define WARN_BTEMP_H (380) /* upper value of warning body temperature */
#define WARN_ACCL_Z (-8) /* lower value of warning acceleration */
#define PAR_ACC_BASE (30) /* base value of low pass filter coefficient */
#define PAR_ACC_STEP (5) /* step of coefficient enlarge */
#define CNT_ACC_STEP (5) /* step of counter enlarge */
#define THOLD_ACC_DIFF (300) /* threshold of acceleration value variation range, counter enlarge */
#define THOLD_ACC_CNT (30) /* threshold of counter, coefficient enlarge */
#define PAR_SVM_BASE (80) /* base value of low pass filter coefficient */
#define PAR_SVM_STEP (20) /* step of coefficient enlarge */
#define CNT_SVM_STEP (5) /* step of counter enlarge */
#define THOLD_SVM_DIFF (30) /* threshold of acceleration value variation range, counter enlarge */
#define THOLD_SVM_CNT (50) /* threshold of counter, coefficient enlarge */
#define MAX_LIMIT_SVM (200) /* upper limit of svm */
#define MIN_LIMIT_SVM (5) /* lower limit of svm */
#define THOLD_INTEN_AW (1000) /* threshold of motion intensity */
#define LEN_STA_WAKE (5) /* length of state queue indicated baby awake */
#define LEN_STA_SLEEP (LEN_STA_QUEUE - LEN_STA_WAKE)
#define PAR_STA_AW (0.75) /* proportion of wake-state in total queue indicated baby awake */
#define P (0.0046) /* coefficient of scale */
#define K0 (0.04) /* coefficient of relationship */
#define K1 (0.22)
#define K2 (1)
#define K3 (0.24)
#define K4 (0.06)
#define AWAKE (1)
#define NOEVENT (0)
#define LEN_STA_QUEUE (20)
#define SLEEP (1)
#define WAKE (0)
#define STACK_DEPTH_HRATE (256) /* stack depth for heartrate detector : word(4*bytes) */
#define TIME_DELAY_HRATE_MS (19) /* IR sampling frequency: 50Hz */
#define HRATE_BASE_VALUE (1200079925) /* base value of calculating heartrate */
calibrate the time elapsed per clock cycle: U = 1000(ms)/20001331(cycles) beats_per_min = 60/(cost_cycles*U/1000) ==> = 1200079925/cost_cycles
#define HRATE_SIZE (8) /* increase this for more averaging, 8 is good */
#define BEATS_PER_MIN_MAX (255) /* maximum value of heartrate */
#define BEATS_PER_MIN_MIN (20) /* minimum value of heartrate */
#define AMPL_DIFF_MAX (1000) /* maximum value of finger detecting amplitude */
#define AMPL_DIFF_MIN (100) /* minimum value of finger detecting amplitude */
#define WARN_HR_MIN (50) /* lower value of warning heartrate */
#define WARN_HR_MAX (150) /* upper value of warning heartrate */
Typedefs
typedef struct __accValues acc_values
Functions
static int32_t mpu6050_reg_write (uint8_t *seq, uint8_t len)
write mpu6050 register
static int32_t mpu6050_reg_read (uint8_t seq, uint8_t *val, uint8_t len)
read mpu6050 register
int32_t acc_sensor_init (uint32_t slv_addr)
acceleration sensor initialize
int32_t acc_sensor_read (acc_values *acc_temp)
read acceleration sensor value
static int32_t tmp112_reg_write (uint8_t *seq, uint8_t len)
write tmp112 register
static int32_t tmp112_reg_read (uint8_t seq, uint8_t *val, uint8_t len)
read tmp112 register
int32_t btemp_sensor_init (uint32_t slv_addr)
body temperature sensor initialize
int32_t btemp_sensor_read (uint16_t *btemp)
val is the return temperature in degrees Celsius (1/10 C)
static int32_t max30102_reg_write (uint8_t *seq, uint8_t len)
write max30102 register
static int32_t max30102_reg_read (uint8_t seq, uint8_t *val, uint8_t len)
read max30102 register
int32_t hrate_sensor_init (uint32_t slv_addr)
heartrate sensor initialize
int32_t hrate_sensor_read (int32_t *hrate)
read heartrate sensor data
static void timer1_isr (void *ptr)
arc timer 1 interrupt routine
void timer1_start (void)
software timing used timer1 interrupt start
void timer1_stop (void)
software timing used timer1 stop
void perf_init (void)
performance timer initialization
void perf_start (void)
performance timer start
uint32_t perf_end (void)
performance timer end, and return the time passed
static void task_lwm2m_client (void *par)
int32_t lwm2m_client_start (void)
function to be LwM2M Client
void print_msg_func (void)
print message for debug major function
void print_msg_awake (void)
print message for debug awake event detecting function
void print_msg_sleep (uint8_t state)
print message for debug sleep-wake state monitoring function
static uint32_t process_acc (acc_values acc_temp)
function for processing accelerate raw data
static uint8_t func_detect_awake (uint32_t inten_temp)
function for awake event detecting
static uint8_t func_detect_state (uint32_t inten_temp)
function for sleep-wake state detecting
static bool func_detect_downward (float acc_temp)
function for sleep downward state detecting
static void task_sleep_monitor (void *par)
task for sleep monitoring
void sleep_monitor_start (void)
function for starting sleep monitor and body temperature detecting
static int filter_acc (int val_new, int val_old, bool *flag_old, char *cnt, unsigned char *par)
function for deal with acclerate by filter
static int filter_svm (int val_new, int val_old, bool *flag_old, char *cnt, unsigned char *par)
function for deal with SVM by filter
static bool check_beat (int32_t sample)
Heart Rate Monitor functions takes a sample value and the sample number returns true if a beat is detected a running average of four samples is recommended for display on the screen.
static int16_t aver_dc_estimator (int32_t *p, uint16_t x)
average DC estimator
static int16_t low_pass_fir_filter (int16_t din)
low pass FIR filter
static int32_t mul16 (int16_t x, int16_t y)
integer multiplier
static void task_process_hrate (void *par)
task for heartrate detecting
void hrate_detector_start (void)
function for starting heartrate detecting
int main (void)
main entry
Variables
union _acc_data acc_data
static uint8_t imu_init_seq0 []
static uint8_t imu_init_seq1 []
static const float acc_unit = 5.9855042e-4f
static DEV_IIC * emsk_imu_sensor
static uint32_t acc_sensor_addr
union _btemp_data btemp_data
static uint8_t tmp_oneshot_enable []
static uint8_t tmp_shutdown_enable []
static const float btemp_unit = 0.0625
static DEV_IIC * emsk_tmp_sensor
static uint32_t btemp_sensor_addr
union _hrate_data hrate_data
static uint8_t hrate_init_fifo_seq []
static uint8_t hrate_init_seq []
static uint8_t hrate_int_enable []
static DEV_IIC * emsk_max_sensor
static uint32_t hrate_sensor_addr
volatile uint32_t t1_cnt
volatile uint32_t t1_start
static lwm2m_client_info c_info
static int lwm2m_client_conn_stat = 0
static int lwm2m_client_start_flag = 0
static const char * p_port = (char *)"5683"
static const char * p_server = (char *)"192.168.43.199"
static const char * p_client_name = (char *)"wn"
static TaskHandle_t task_lwm2m_client_handle = NULL
static char cnt_x
static char cnt_y
static char cnt_z
static unsigned char par_x
static unsigned char par_y
static unsigned char par_z
static bool flag_old_x
static bool flag_old_y
static bool flag_old_z
static int16_t x_old
static int16_t y_old
static int16_t z_old
static uint32_t svm_old
static char cnt_v
static unsigned char par_v
static bool flag_old_v
static TaskHandle_t task_sleep_monitor_handle = NULL
uint8_t state_aw [LEN_STA_QUEUE]
uint32_t inten_sl [5]
uint32_t sum_svm_5s
float score_sl
static uint16_t rates [HRATE_SIZE]
static uint8_t rate_spot = 0
static uint32_t beats_per_min
static uint16_t beat_aver
static bool flag_timer_stop = true
static int16_t ir_ac_max = 20
static int16_t ir_ac_min = -20
static int16_t val_cur = 0
static int16_t val_pre
static int16_t val_min = 0
static int16_t val_max = 0
static int16_t aver_estimated
static int16_t pos_edge = 0
static int16_t neg_edge = 0
static int32_t ir_avg_reg = 0
static int16_t cbuf [32]
static uint8_t offset = 0
static const uint16_t fir_coeffs [12] = {172, 321, 579, 927, 1360, 1858, 2390, 2916, 3391, 3768, 4012, 4096}
static TaskHandle_t task_process_hrate_handle = NULL
macros for settings
#define LWM2M_CLIENT (0)
#define PRINT_DEBUG_FUNC (1)
#define PRINT_DEBUG_AWAKE (0)
#define PRINT_DEBUG_SLEEP (0)
macros for freertos task
#define TSKPRI_HIGH (configMAX_PRIORITIES-2)
#define TSKPRI_MID (configMAX_PRIORITIES-3)
#define TSKPRI_LOW (configMAX_PRIORITIES-4)
macros for reported data
data_wearable_node data_report_wn
data_wearable_node data_report_wn_old
Detailed Description
embARC IoT iBaby Smarthome Node Wearable Node
Extra Required Tools
Extra Required Peripherals
Digilent PMOD WIFI(MRF24WG0MA) MPU6050 MAX30102 MLX90614
Design Concept
All sensor modules should be connected to EMSK. This application is designed to show how to connect EMSK and iBaby Smarthome Gateway using embARC.
Usage Manual
Before compiling this example, you need to change some macro in common.h to customize your own project.
It can report the following information to the iBaby Smarthome Gateway.
the Body Temperature (uint16_t) - Wearable module connected to J4 (Based on Temperature sensor)
the Heartrate (uint16_t) - Wearable module connected to J4 (Based on Heartrate sensor)
the Motion Intensity in 1min (uint32_t) - Wearable module connected to J4 (Based on Acceleration sensor)
the Sleep-Wake state (uint8_t) - Wearable module connected to J4 (Based on Acceleration sensor)
the Awake Event (uint8_t) - Wearable module connected to J4 (Based on Acceleration sensor)
3 flags of Warning (bool) - Warning of Body Temperature abnormal, Heartrate abnormal, sleep on his stomach
EMSK can send the above data to iBaby Gateway Smarthome with LwM2M.
Extra Comments
Macro Definition Documentation
#define ACC_SENSOR_IIC_ID DW_IIC_1_ID
< using IIC 1 interface
Definition at line 47 of file acceleration.h.
Referenced by acc_sensor_init(), acc_sensor_read(), mpu6050_reg_read(), and mpu6050_reg_write().
#define AWAKE (1)
< parameters of awake event detecting wake up event
Definition at line 52 of file process_acc.h.
Referenced by func_detect_awake().
#define BTEMP_SENSOR_IIC_ID DW_IIC_1_ID
< using IIC 1 interface TMP112 address
Definition at line 47 of file body_temperature.h.
Referenced by btemp_sensor_init(), btemp_sensor_read(), tmp112_reg_read(), and tmp112_reg_write().
#define EMSK_IMU_SENSOR_CHECK_EXP_NORTN (EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
struct for acceleration data storaged
Definition at line 60 of file acceleration.h.
Referenced by acc_sensor_init(), mpu6050_reg_read(), and mpu6050_reg_write().
#define HRATE_SENSOR_IIC_ID DW_IIC_1_ID
< using IIC 1 interface max30102 address
Definition at line 47 of file heartrate.h.
Referenced by hrate_sensor_init(), hrate_sensor_read(), max30102_reg_read(), and max30102_reg_write().
#define LEN_STA_QUEUE (20)
length of state queue used to detect awake event parameters of sleep monitoring algorithm
Definition at line 55 of file process_acc.h.
Referenced by func_detect_awake().
#define LWM2M_CLIENT (0)
set 1 to be lwm2m client
Definition at line 50 of file wearable_node/function/common.h.
#define MAX30102_ADDRESS 0x57
heartrate sensor address
Definition at line 50 of file heartrate.h.
#define MPU6050_A0_PIN 0
I2C address of PmodIMU4 can be selected via AD0: 0x68, 0x69 AD0 connect to GND is 0x68.
< MPU6050 address I2C Serial Bus Address Selection Pin
Definition at line 54 of file acceleration.h.
#define MPU6050_ADDRESS (0x68 + MPU6050_A0_PIN)
acceleration sensor address
Definition at line 55 of file acceleration.h.
#define NOEVENT (0)
no event
Definition at line 53 of file process_acc.h.
Referenced by func_detect_awake().
#define PRINT_DEBUG_AWAKE (0)
set 1 to print out message for debug awake event detecting function
Definition at line 53 of file wearable_node/function/common.h.
#define PRINT_DEBUG_FUNC (1)
set 1 to print out message for debug major function
Definition at line 52 of file wearable_node/function/common.h.
#define PRINT_DEBUG_SLEEP (0)
set 1 to print out message for debug sleep-wake state monitoring function
Definition at line 54 of file wearable_node/function/common.h.
#define SLEEP (1)
sleep state
Definition at line 58 of file process_acc.h.
Referenced by func_detect_state().
#define TSKPRI_HIGH (configMAX_PRIORITIES-2)
< freertos task priority high priority
Definition at line 63 of file wearable_node/function/common.h.
#define TSKPRI_LOW (configMAX_PRIORITIES-4)
low priority
Definition at line 65 of file wearable_node/function/common.h.
#define TSKPRI_MID (configMAX_PRIORITIES-3)
middle priority
Definition at line 64 of file wearable_node/function/common.h.
#define WAKE (0)
wake state variable of detecting awake event
Definition at line 59 of file process_acc.h.
Referenced by func_detect_state().
Function Documentation
int32_t acc_sensor_init (uint32_t slv_addr)
acceleration sensor initialize
Parameters
[in] slv_addr imu sensor iic slave address
Return values
E_OK initialize success
!E_OK initialize failed
Definition at line 176 of file acceleration.c.
References ACC_SENSOR_IIC_ID, CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, EMSK_IMU_SENSOR_CHECK_EXP_NORTN, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, IIC_SPEED_STANDARD, and mpu6050_reg_write().
Referenced by main().
int32_t acc_sensor_read (acc_values * acc_temp)
read acceleration sensor value
Parameters
[out] val return acceleration data
Return values
E_OK read success
!E_OK read failed
Definition at line 205 of file acceleration.c.
References ACC_SENSOR_IIC_ID, E_OBJ, E_OK, iic_get_dev(), and mpu6050_reg_read().
Referenced by task_sleep_monitor().
int32_t btemp_sensor_init (uint32_t slv_addr)
body temperature sensor initialize
Parameters
[in] slv_addr body temperature sensor iic slave address
Return values
E_OK initialize success
!E_OK initialize failed
Definition at line 166 of file body_temperature.c.
References BTEMP_SENSOR_IIC_ID, CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, IIC_SPEED_STANDARD, and tmp112_reg_write().
Referenced by main().
int32_t btemp_sensor_read (uint16_t * btemp)
val is the return temperature in degrees Celsius (1/10 C)
read temperature sensor value in 0.1c unit
Parameters
[out] val return temperature in degrees Celsius (1/10 C)
Return values
E_OK read success
!E_OK read failed
Definition at line 195 of file body_temperature.c.
References BTEMP_SENSOR_IIC_ID, E_OBJ, E_OK, iic_get_dev(), tmp112_reg_read(), and tmp112_reg_write().
Referenced by task_sleep_monitor().
int32_t hrate_sensor_init (uint32_t slv_addr)
heartrate sensor initialize
Parameters
[in] slv_addr heartrate sensor iic slave address
Return values
E_OK initialize success
!E_OK initialize failed
Definition at line 253 of file heartrate.c.
References CONV2VOID, E_OK, E_OPNED, HRATE_SENSOR_IIC_ID, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), and max30102_reg_write().
Referenced by main().
int32_t hrate_sensor_read (int32_t * hrate)
read heartrate sensor data
Parameters
[out] val return heartrate sensor data
Return values
E_OK read success
!E_OK read failed
Definition at line 281 of file heartrate.c.
References E_OBJ, E_OK, HRATE_SENSOR_IIC_ID, iic_get_dev(), and max30102_reg_read().
Referenced by task_process_hrate().
static int32_t max30102_reg_read (uint8_t seq, uint8_t * val, uint8_t len) static
read max30102 register
Parameters
seq regaddr register address
*val returned value
len the length of returned value
Return values
>=0 read success, return bytes read
!E_OK read failed
Definition at line 224 of file heartrate.c.
References CONV2VOID, E_PAR, HRATE_SENSOR_IIC_ID, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by hrate_sensor_read().
static int32_t max30102_reg_write (uint8_t * seq, uint8_t len) static
write max30102 register
Parameters
*seq register address and value to be written
len the length of seq
Return values
>=0 write success, return bytes written
!E_OK write failed
Definition at line 198 of file heartrate.c.
References CONV2VOID, E_PAR, HRATE_SENSOR_IIC_ID, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by hrate_sensor_init().
static int32_t mpu6050_reg_read (uint8_t seq, uint8_t * val, uint8_t len) static
read mpu6050 register
Parameters
seq register address
*val returned value
len the length of returned value
Return values
>=0 read success, return bytes read
!E_OK read failed
Definition at line 146 of file acceleration.c.
References ACC_SENSOR_IIC_ID, CONV2VOID, E_PAR, EMSK_IMU_SENSOR_CHECK_EXP_NORTN, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by acc_sensor_read().
static int32_t mpu6050_reg_write (uint8_t * seq, uint8_t len) static
write mpu6050 register
Parameters
*seq register address and value to be written
len the length of seq
Return values
>=0 write success, return bytes written
!E_OK write failed
Definition at line 120 of file acceleration.c.
References ACC_SENSOR_IIC_ID, CONV2VOID, E_PAR, EMSK_IMU_SENSOR_CHECK_EXP_NORTN, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by acc_sensor_init().
static void perf_start (void)
performance timer start
performance timer start.
Definition at line 108 of file timer1.c.
References t1_start, TIMER_1, and timer_current().
Referenced by task_process_hrate().
static int32_t tmp112_reg_read (uint8_t seq, uint8_t * val, uint8_t len) static
read tmp112 register
Parameters
seq register address
*val returned value
len the length of returned value
Return values
>=0 read success, return bytes read
!E_OK read failed
Definition at line 138 of file body_temperature.c.
References BTEMP_SENSOR_IIC_ID, CONV2VOID, E_PAR, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by btemp_sensor_read().
static int32_t tmp112_reg_write (uint8_t * seq, uint8_t len) static
write tmp112 register
Parameters
*seq register address and value to be written
len the length of seq
Return values
>=0 write success, return bytes written
!E_OK write failed
Definition at line 112 of file body_temperature.c.
References BTEMP_SENSOR_IIC_ID, CONV2VOID, E_PAR, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by btemp_sensor_init(), and btemp_sensor_read().
Variable Documentation
data_wearable_node data_report_wn
current value of reporting data
Definition at line 87 of file wearable_node/function/common.h.
Referenced by task_process_hrate(), and task_sleep_monitor().
data_wearable_node data_report_wn_old
the last value of reporting data
Definition at line 88 of file wearable_node/function/common.h.
uint8_t hrate_init_fifo_seq[] static
Initial value:
= {
        MAX30102_REG_FIFO_WR_PTR,
        0x00,
        0x00,
        0x00
}
Definition at line 162 of file heartrate.c.
uint8_t hrate_init_seq[] static
Initial value:
= {
        MAX30102_REG_FIFO_CONFIG,
        MAX30102_CONFIG_FIFO_A_FULL(15) | MAX30102_CONFIG_SMP_AVE(0),
        MAX30102_CONFIG_MODE(2),
        MAX30102_CONFIG_SPO2_ADC_REG(2) | MAX30102_CONFIG_LED_PW(3) | MAX30102_CONFIG_SPO2_SR(0),
        0x00,
        0x28
}
Definition at line 170 of file heartrate.c.
uint8_t hrate_int_enable[] static
Initial value:
= {
        MAX30102_REG_INT_ENABLE_1,
        MAX30102_STATUS_PPG_RDY | MAX30102_STATUS_A_FULL,
        0x00,
}
Definition at line 181 of file heartrate.c.
uint8_t imu_init_seq0[] static
Initial value:
= {
        MPU6050_REG_SAMPLE_RATE,
        0x00,
        0x01,
        0x18,
        0x00
}
Definition at line 94 of file acceleration.c.
uint8_t imu_init_seq1[] static
Initial value:
= {
        MPU6050_REG_POWER_MANAGEMENT,
        0x00
}
Definition at line 102 of file acceleration.c.
uint32_t inten_sl[5]
motion intensity for 5 * 1min
Definition at line 66 of file process_acc.h.
Referenced by func_detect_state().
float score_sl
score of motion
Definition at line 68 of file process_acc.h.
Referenced by func_detect_state().
uint8_t state_aw[LEN_STA_QUEUE]
state for LEN_STA_QUEUE * 5s variable of sleep monitoring
Definition at line 63 of file process_acc.h.
Referenced by func_detect_awake().
uint32_t sum_svm_5s
motion intensity in 5s
Definition at line 67 of file process_acc.h.
Referenced by task_sleep_monitor().
volatile uint32_t t1_cnt
software timing counter for timer1
Definition at line 47 of file timer1.h.
Referenced by timer1_isr(), timer1_start(), and timer1_stop().
volatile uint32_t t1_start
storage count of timer1
Definition at line 48 of file timer1.h.
Referenced by perf_end(), and perf_start().
uint8_t tmp_oneshot_enable[] static
Initial value:
= {
        TMP112_REG_CONG,
        TMP112_CONFIG_OS,
        0x00
}
Definition at line 86 of file body_temperature.c.
uint8_t tmp_shutdown_enable[] static
Initial value:
= {
        TMP112_REG_CONG,
        TMP112_CONFIG_SD,
        0x00
}
Definition at line 93 of file body_temperature.c.