embARC: Compiler Builtin and Helper
Compiler Builtin and Helper
ARC HAL
Built-in and helper functions to access ARC hardware layer.
Files
file arc_builtin.h
header file of builtin and helper functions
Macros
#define _arc_nop _nop
#define _arc_brk _brk
#define _arc_clri _clri
#define _arc_seti(c) _seti(c)
#define _arc_core_write(regno, val) _core_write(val, regno)
#define _arc_core_read(regno) _core_read(regno)
#define _arc_lr_reg(aux) _lr(aux)
#define _arc_sr_reg(aux, val) _sr(val, aux)
#define _arc_sleep(a) _sleep(a)
#define _arc_flag(a) _flag(a)
#define _arc_kflag(a)
#define _arc_sync _sync
#define _arc_usually(a) _Usually((a))
#define _arc_rarely(a) _Rarely((a))
#define _arc_swi _swi
Each call to _swi() generates one software interrupt instruction (SWI) for processors to support the SWI instruction.
#define _arc_aux_read(aux) _arc_lr_reg(aux)
#define _arc_aux_write(aux, val) _arc_sr_reg(aux, val)
Functions
Inline uint32_t _arc_swap32 (uint32_t val)
Inline uint16_t _arc_swap16 (uint32_t val)
cache related helper function
Inline uint32_t _arc_read_uncached_32 (void *ptr)
read memory and bypass the cache
Inline void _arc_write_uncached_32 (void *ptr, uint32_t data)
write memory and bypass the cache
Inline uint32_t _arc_read_cached_32 (void *ptr)
read memory with cache
Inline void _arc_write_cached_32 (void *ptr, uint32_t data)
read memory with cache
Inline int32_t _arc_goto_main (int argc, char **argv)
go to main function with proper arguments
Detailed Description
Built-in and helper functions to access ARC hardware layer.
Macro Definition Documentation
#define _arc_brk _brk
generate a brk instruction
Definition at line 60 of file arc_builtin.h.
#define _arc_clri _clri
generate a clri instruction
Definition at line 62 of file arc_builtin.h.
Referenced by arc_lock_save().
#define _arc_core_read (regno) _core_read(regno)
read core register
Definition at line 68 of file arc_builtin.h.
#define _arc_core_write (regno, val) _core_write(val, regno)
write core register
Definition at line 66 of file arc_builtin.h.
#define _arc_flag (a) _flag(a)
generate a flag instruction
Definition at line 76 of file arc_builtin.h.
#define _arc_lr_reg (aux) _lr(aux)
read auxiliary register
Definition at line 70 of file arc_builtin.h.
Referenced by main().
#define _arc_nop _nop
no operation, generate a nop instruction produces a single NOP instruction in the compiled code
Definition at line 58 of file arc_builtin.h.
#define _arc_seti (c) _seti(c)
generate a seti instruction
Definition at line 64 of file arc_builtin.h.
Referenced by arc_unlock_restore().
#define _arc_sleep (a) _sleep(a)
generate a sleep instruction
Definition at line 74 of file arc_builtin.h.
#define _arc_sr_reg (aux, val) _sr(val, aux)
write auxiliary register
Definition at line 72 of file arc_builtin.h.
#define _arc_sync _sync
generate a sync instruction
Definition at line 80 of file arc_builtin.h.
Function Documentation
Inline int32_t _arc_goto_main (int argc, char ** argv)
go to main function with proper arguments
Parameters
argc argument count
argv argument content array
Return values
return value of main function
Definition at line 277 of file arc_builtin.h.
Inline uint32_t _arc_read_cached_32 (void * ptr)
read memory with cache
Parameters
[in] ptr memory address
Returns
value in the memory
Definition at line 253 of file arc_builtin.h.
Referenced by __attribute__().
Inline uint32_t _arc_read_uncached_32 (void * ptr)
read memory and bypass the cache
Parameters
[in] ptr memory address
Returns
value in the memory
Definition at line 231 of file arc_builtin.h.
Referenced by __attribute__().
Inline void _arc_write_cached_32 (void * ptr, uint32_t data)
read memory with cache
Parameters
[in] ptr memory address
[in] data vaule to be written
Returns
description
Definition at line 266 of file arc_builtin.h.
Inline void _arc_write_uncached_32 (void * ptr, uint32_t data)
write memory and bypass the cache
Parameters
[in] ptr memory address
[in] data vaule to be written
Definition at line 243 of file arc_builtin.h.
Referenced by dw_spi_0_control().