embARC: EMSK BLE-HM1X Driver
EMSK BLE-HM1X Driver
BSP Layer » EMSK BSP » EMSK Peripheral Driver Module » EMSK Bluetooth 4.0 Driver
EMSK HM1X BLE driver.
Files
file hm1x.c
HM-1X BLE driver.
file hm1x.h
HM-1X BLE driver.
Macros
#define HM_1X_UART_ID DW_UART_0_ID
uart id which HM-10 BLE uses
#define HM1X_TIMENOW() OSP_GET_CUR_MS()
#define HM1X_READ_TMOUT 500
#define MAX_CMD_LENGTH 32
#define MAX_RESP_LENGTH 32
#define AT_CMD_PREFIX "AT+"
#define BAUD_INDEX_MAX 8
#define BAUD_INDEX_MIN 0
#define HM1X_SYS_DELAY_MS 550
#define ENABLE_HM1X_DEBUG
#define HM1X_DEBUG(fmt,...) EMBARC_PRINTF(fmt, ##__VA_ARGS__)
#define MAX_READ_CNT 20
#define OK_SET_PREFIX "OK+Set:"
#define OK_GET_PREFIX "OK+Get:"
#define CMD_BAUD_SET_PREFIX "AT+BAUD"
#define BLE_HM1X_MASTER_ROLE 1
HM1X working role: master or slave.
#define BLE_HM1X_SLAVE_ROLE 0
#define BLE_HM1X_MODE_0 0
HM1X working mode: 0: transparent 1: PIO sample & remote control & transparent 2: remote control & transparent.
#define BLE_HM1X_MODE_1 1
#define BLE_HM1X_MODE_2 2
#define BLE_HM1X_TYPE_0 0
HM1X working type 0: connect without password 1: simple match 2: match with password 3: match and bind.
#define BLE_HM1X_TYPE_1 1
#define BLE_HM1X_TYPE_2 2
#define BLE_HM1X_TYPE_3 3
Functions
static void hm1x_delay (uint32_t ms)
Internal delay function used by hm1x.
void hm1x_flush (void)
Flush the hm1x input data.
int32_t hm1x_init (uint32_t baudrate)
Init HM1X BLE device.
uint32_t hm1x_write (uint8_t *buf, uint32_t cnt)
Write data to HM1X.
uint32_t hm1x_read (uint8_t *buf, uint32_t cnt)
Read data from HM1X.
int32_t hm1x_exec_command (char *cmd, char *resp, uint32_t wait_ms)
Execute command and wait for response with timeout.
int32_t hm1x_exec_cmd_chkresp (char *cmd, char *resp_prefix, char *resp_data, uint32_t max_try)
Execute command and check whether the response prefix matches.
int32_t hm1x_set_param (char *param, char *val)
HM1X set param, value and param must end with '\0', 0 for success, -1 for fail.
int32_t hm1x_get_param (char *param, char *r_val)
HM1X get param, cmd and val must contain '\0' end, >=0 for success, <0 for fail.
int32_t hm1x_set_param_u8 (char *param, uint8_t val)
set a 8bits long parameter of hm1x, 0 for success, -1 for fail
int32_t hm1x_set_role (uint32_t role)
set working role, 0 for success, -1 for fail
int32_t hm1x_set_mode (uint32_t mode)
set working mode, 0 for success, -1 for fail
int32_t hm1x_set_type (uint32_t type)
set working type, 0 for success, -1 for fail
int32_t hm1x_set_baud (uint32_t baudrate)
set baudrate of hm1x, >=0 for success, -1 for fail
int32_t hm1x_disconnect (void)
disconnect the already connected ble, >=0 for success, <0 for fail
int32_t hm1x_restart (void)
reset and restart the module, >=0 for success, <0 for fail
int32_t hm1x_renew (void)
renew the module, >=0 for success, <0 for fail
int32_t hm1x_baudrate_map (uint32_t baudrate)
get the baudrate map of hm1x, return the index of baudrate map in hm1x
Variables
DEV_UART * hm1x_ble_uart = NULL
Detailed Description
EMSK HM1X BLE driver.
Implement the hm1x ble driver using the DesignWare UART device driver.
Function Documentation
int32_t hm1x_exec_cmd_chkresp (char * cmd, char * resp_prefix, char * resp_data, uint32_t max_try)
Execute command and check whether the response prefix matches.
Parameters
cmd Command to send to the BLE device using the UART
resp_prefix Response prefix string, like OK. Must not be NULL
resp_data Response data buffer, may be NULL
max_try How many times this function can try to run
Return values
-1 Fail
>=0 Response data length
Definition at line 206 of file hm1x.c.
References hm1x_exec_command().
Referenced by hm1x_disconnect(), hm1x_get_param(), hm1x_renew(), hm1x_restart(), hm1x_set_baud(), and hm1x_set_param().
int32_t hm1x_exec_command (char * cmd, char * resp, uint32_t wait_ms)
Execute command and wait for response with timeout.
Parameters
cmd Command to send to the BLE device using the UART
resp Response buffer, must not be NULL
wait_ms Maximum MS to wait for response
Return values
-1 Fail
>=0 Response string count
Definition at line 177 of file hm1x.c.
References hm1x_read(), and hm1x_write().
Referenced by hm1x_exec_cmd_chkresp().
int32_t hm1x_get_param (char * param, char * r_val)
HM1X get param, cmd and val must contain '\0' end, >=0 for success, <0 for fail.
only for return resp with OK+Get:
Definition at line 268 of file hm1x.c.
References hm1x_exec_cmd_chkresp().
int32_t hm1x_init (uint32_t baudrate)
Init HM1X BLE device.
Parameters
baudrate ble working baudrate
Return values
0 success
-1 fail
Definition at line 121 of file hm1x.c.
References E_OPNED, HM_1X_UART_ID, UART_CMD_SET_BAUD, dev_uart::uart_control, uart_get_dev(), and dev_uart::uart_open.
uint32_t hm1x_read (uint8_t * buf, uint32_t cnt)
Read data from HM1X.
Parameters
buf Buffer to be read to
cnt Number to be read
Return values
0 Failed to read
>0 Read count
Definition at line 155 of file hm1x.c.
References UART_CMD_GET_RXAVAIL, dev_uart::uart_control, and dev_uart::uart_read.
Referenced by hm1x_exec_command().
int32_t hm1x_set_param (char * param, char * val)
HM1X set param, value and param must end with '\0', 0 for success, -1 for fail.
only for return resp with OK+Set:
Definition at line 245 of file hm1x.c.
References hm1x_exec_cmd_chkresp().
Referenced by hm1x_set_param_u8().
int32_t hm1x_set_param_u8 (char * param, uint8_t val)
set a 8bits long parameter of hm1x, 0 for success, -1 for fail
only for return resp with OK+Set:
Definition at line 287 of file hm1x.c.
References hm1x_set_param().
Referenced by hm1x_set_mode(), hm1x_set_role(), and hm1x_set_type().
uint32_t hm1x_write (uint8_t * buf, uint32_t cnt)
Write data to HM1X.
Parameters
buf Buffer to be written
cnt Number to be written
Return values
0 Failed to write
>0 Written count
Definition at line 141 of file hm1x.c.
References dev_uart::uart_write.
Referenced by hm1x_exec_command().