embARC: EMSK Common Init Module
EMSK Common Init Module
BSP Layer » EMSK BSP » EMSK Common Module
EMSK Board Common Init Module.
Files
file emsk_init.c
common emsk init module
file 11/emsk_hardware.h
emsk hardware resource definitions
file 22/emsk_hardware.h
emsk hardware resource definitions
file 23/emsk_hardware.h
emsk hardware resource definitions
file emsk.h
emsk resource definitions
Macros
#define PERIPHERAL_BASE _arc_aux_read(AUX_DMP_PERIPHERAL)
#define CLK_CPU (30000000)
CPU Clock Frequency definition.
#define CLK_BUS_APB (50000000U)
Peripheral Bus Reference Clock definition.
#define REL_REGBASE_PINMUX (0x00000000U)
#define REL_REGBASE_GPIO0 (0x00002000U)
#define REL_REGBASE_I2C0 (0x00004000U)
#define REL_REGBASE_SPI0 (0x00006000U)
#define REL_REGBASE_SPI1 (0x00007000U)
#define REL_REGBASE_UART0 (0x00008000U)
#define REL_REGBASE_UART1 (0x00009000U)
#define INTNO_TIMER0 16
#define INTNO_TIMER1 17
#define INTNO_GPIO 18
#define INTNO_I2C0 19
#define INTNO_SPI_MASTER 21
#define INTNO_SPI_SLAVE 22
#define INTNO_UART0 23
#define INTNO_UART1 24
#define EMSK_SPI_LINE_0 0
#define EMSK_SPI_LINE_1 1
#define EMSK_SPI_LINE_2 2
#define EMSK_SPI_LINE_SDCARD 3
#define EMSK_SPI_LINE_SPISLAVE 4
#define EMSK_SPI_LINE_SFLASH 5
#define CLK_CPU (30000000)
CPU Clock Frequency definition.
#define CLK_BUS_APB (50000000U)
Peripheral Bus Reference Clock definition.
#define REL_REGBASE_PINMUX (0x00000000U)
#define REL_REGBASE_SPI_MST_CS_CTRL (0x00000014U)
#define REL_REGBASE_GPIO0 (0x00002000U)
#define REL_REGBASE_TIMERS (0x00003000U)
#define REL_REGBASE_I2C0 (0x00004000U)
#define REL_REGBASE_I2C1 (0x00005000U)
#define REL_REGBASE_SPI0 (0x00006000U)
#define REL_REGBASE_SPI1 (0x00007000U)
#define REL_REGBASE_UART0 (0x00008000U)
#define REL_REGBASE_UART1 (0x00009000U)
#define REL_REGBASE_UART2 (0x0000A000U)
#define REL_REGBASE_WDT (0x0000B000U)
#define REL_REGBASE_I2S_MASTER_IN (0x0000C000U)
#define REL_REGBASE_I2S_MASTER_OUT (0x0000D000U)
#define REL_REGBASE_GMAC (0x0000E000U)
#define INTNO_TIMER0 16
#define INTNO_TIMER1 17
#define INTNO_GPIO 22
#define INTNO_I2C0 23
#define INTNO_I2C1 24
#define INTNO_SPI_MASTER 25
#define INTNO_SPI_SLAVE 26
#define INTNO_UART0 27
#define INTNO_UART1 28
#define INTNO_UART2 29
#define INTNO_DW_WDT 30
#define INTNO_DW_TMR0 31
#define INTNO_DW_TMR1 32
#define INTNO_I2S_Master_In 33
#define INTNO_I2S_Master_Out 34
#define INTNO_GMAC 35
#define EMSK_SPI_LINE_0 0
#define EMSK_SPI_LINE_1 1
#define EMSK_SPI_LINE_2 2
#define EMSK_SPI_LINE_SDCARD 3
#define EMSK_SPI_LINE_SPISLAVE 4
#define EMSK_SPI_LINE_SFLASH 5
#define CLK_CPU (20000000)
CPU Clock Frequency definition.
#define CLK_BUS_APB (50000000U)
Peripheral Bus Reference Clock definition.
#define REL_REGBASE_PINMUX (0x00000000U)
#define REL_REGBASE_SPI_MST_CS_CTRL (0x00000014U)
#define REL_REGBASE_GPIO0 (0x00002000U)
#define REL_REGBASE_TIMERS (0x00003000U)
#define REL_REGBASE_I2C0 (0x00004000U)
#define REL_REGBASE_I2C1 (0x00005000U)
#define REL_REGBASE_SPI0 (0x00006000U)
#define REL_REGBASE_SPI1 (0x00007000U)
#define REL_REGBASE_UART0 (0x00008000U)
#define REL_REGBASE_UART1 (0x00009000U)
#define REL_REGBASE_UART2 (0x0000A000U)
#define REL_REGBASE_WDT (0x0000B000U)
#define INTNO_TIMER0 16
#define INTNO_TIMER1 17
#define INTNO_SECURE_TIMER0 20
#define INTNO_DMA_START 22
#define INTNO_DMA_COMPLETE 22
#define INTNO_DMA_ERROR 23
#define INTNO_GPIO 24
#define INTNO_I2C0 25
#define INTNO_I2C1 26
#define INTNO_SPI_MASTER 27
#define INTNO_SPI_SLAVE 28
#define INTNO_UART0 29
#define INTNO_UART1 30
#define INTNO_UART2 31
#define INTNO_DW_WDT 32
#define INTNO_DW_TMR0 33
#define INTNO_DW_TMR1 34
#define EMSK_SPI_LINE_0 0
#define EMSK_SPI_LINE_1 1
#define EMSK_SPI_LINE_2 2
#define EMSK_SPI_LINE_SDCARD 3
#define EMSK_SPI_LINE_SPISLAVE 4
#define EMSK_SPI_LINE_SFLASH 5
#define EMSK_GPIO_PORT_A DW_GPIO_PORT_A
#define EMSK_GPIO_PORT_B DW_GPIO_PORT_B
#define EMSK_GPIO_PORT_C DW_GPIO_PORT_C
#define EMSK_GPIO_PORT_D DW_GPIO_PORT_D
#define BOARD_CONSOLE_UART_ID DW_UART_1_ID
#define BOARD_CONSOLE_UART_BAUD UART_BAUDRATE_115200
#define BOARD_ADC_IIC_ID DW_IIC_0_ID
#define BOARD_TEMP_SENSOR_IIC_ID DW_IIC_0_ID
#define BOARD_TEMP_IIC_SLVADDR TEMP_I2C_SLAVE_ADDRESS
#define BOARD_SDCARD_SPI_ID DW_SPI_0_ID
#define BOARD_WIFI_SPI_ID DW_SPI_0_ID
#define BOARD_SFLASH_SPI_ID DW_SPI_0_ID
#define BOARD_SDCARD_SPI_LINE EMSK_SPI_LINE_SDCARD
#define BOARD_WIFI_SPI_LINE EMSK_SPI_LINE_1
#define BOARD_SFLASH_SPI_LINE EMSK_SPI_LINE_SFLASH
#define BOARD_SPI_FREQ (1000000)
#define BOARD_SPI_CLKMODE (SPI_CLK_MODE_0)
#define BOARD_SYS_TIMER_ID TIMER_0
#define BOARD_SYS_TIMER_INTNO INTNO_TIMER0
#define BOARD_SYS_TIMER_HZ (1000)
#define BOARD_SYS_TIMER_MS_HZ (1000)
board timer count frequency (HZ)
#define BOARD_SYS_TIMER_MS_CONV (BOARD_SYS_TIMER_MS_HZ/BOARD_SYS_TIMER_HZ)
board timer count frequency convention based on the global timer counter
#define BOARD_OS_TIMER_ID TIMER_0
#define BOARD_OS_TIMER_INTNO INTNO_TIMER0
#define BOARD_CPU_CLOCK CLK_CPU
#define BOARD_DEV_CLOCK CLK_BUS_APB
#define BOARD_LED_MASK (0x1ff)
#define BOARD_LED_CNT (9)
#define BOARD_BTN_MASK (0x7)
#define BOARD_BTN_CNT (3)
#define BOARD_SWT_MASK (0xf)
#define BOARD_SWT_CNT (4)
#define BOARD_ONBOARD_NTSHELL_ID (EMSK_NTSHELL_0_ID)
#define OSP_DELAY_OS_COMPAT_ENABLE (1)
#define OSP_DELAY_OS_COMPAT_DISABLE (0)
#define WF_IPADDR_1 (192)
#define WF_IPADDR_2 (168)
#define WF_IPADDR_3 (43)
#define WF_IPADDR_4 (102)
#define WF_NETMASK_1 (255)
#define WF_NETMASK_2 (255)
#define WF_NETMASK_3 (255)
#define WF_NETMASK_4 (0)
#define WF_GATEWAY_1 (192)
#define WF_GATEWAY_2 (168)
#define WF_GATEWAY_3 (43)
#define WF_GATEWAY_4 (1)
#define WF_HOTSPOT_IS_OPEN (0)
#define WF_IPADDR_DHCP (1)
#define WF_HOTSPOT_NAME "embARC"
#define WF_HOTSPOT_PASSWD "qazwsxedc"
#define WF_ENABLE_MANUAL_SET_MAC (0)
#define WF_MAC_ADDR0 (EMSK_PMWIFI_0_MAC_ADDR0)
#define WF_MAC_ADDR1 (EMSK_PMWIFI_0_MAC_ADDR1)
#define WF_MAC_ADDR2 (EMSK_PMWIFI_0_MAC_ADDR2)
#define WF_MAC_ADDR3 (EMSK_PMWIFI_0_MAC_ADDR3)
#define WF_MAC_ADDR4 (EMSK_PMWIFI_0_MAC_ADDR4)
#define WF_MAC_ADDR5 (EMSK_PMWIFI_0_MAC_ADDR5)
#define PMWIFI_MRF24G 0
Possible Pmod WiFi choices.
#define PMWIFI_RW009 1
#define BOARD_PMWIFI_0_ID EMSK_PMWIFI_0_ID
#define BOARD_PMWIFI_ID_MAX EMSK_PMWIFI_0_ID
#define OSP_GET_CUR_SYSHZ() (gl_emsk_sys_hz_cnt)
#define OSP_GET_CUR_MS() (gl_emsk_ms_cnt)
#define OSP_GET_CUR_US() board_get_cur_us()
#define OSP_GET_CUR_HWTICKS() board_get_hwticks()
Functions
static void emsk_mux_init (void)
emsk-related mux io init
void board_init (void)
Board init routine MUST be called in each application.
void board_timer_update (uint32_t precision)
Update timer counter and other MS period operation in cycling interrupt and must be called periodically.
void board_delay_ms (uint32_t ms, uint8_t os_compat)
provide MS delay function
uint64_t board_get_hwticks (void)
get current cpu hardware ticks
uint64_t board_get_cur_us (void)
get current passed us since timer init
Detailed Description
EMSK Board Common Init Module.
EMSK timer/gpio/interrupt init process. Device-driver installation is done while getting the device object for the first time.
Macro Definition Documentation
#define CLK_BUS_APB (50000000U)
Peripheral Bus Reference Clock definition.
< Default peripheral bus reference clock defintion
Definition at line 67 of file 23/emsk_hardware.h.
#define CLK_BUS_APB (50000000U)
Peripheral Bus Reference Clock definition.
< Default peripheral bus reference clock defintion
Definition at line 67 of file 22/emsk_hardware.h.
#define CLK_BUS_APB (50000000U)
Peripheral Bus Reference Clock definition.
< Default peripheral bus reference clock defintion
Definition at line 67 of file 11/emsk_hardware.h.
#define CLK_CPU (20000000)
CPU Clock Frequency definition.
< Default cpu clock frequency
Definition at line 58 of file 23/emsk_hardware.h.
#define CLK_CPU (30000000)
CPU Clock Frequency definition.
< Default cpu clock frequency
Definition at line 58 of file 11/emsk_hardware.h.
#define CLK_CPU (30000000)
CPU Clock Frequency definition.
< Default cpu clock frequency
Definition at line 58 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_0 0
CS0 – Pmod 6 pin1
Definition at line 106 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_0 0
CS0 – Pmod 6 pin1
Definition at line 110 of file 23/emsk_hardware.h.
#define EMSK_SPI_LINE_1 1
CS1 – Pmod 5 pin1 or Pmod 6 pin 7
Definition at line 107 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_1 1
CS1 – Pmod 5 pin1 or Pmod 6 pin 7
Definition at line 111 of file 23/emsk_hardware.h.
#define EMSK_SPI_LINE_2 2
CS2 – Pmod 6 pin8
Definition at line 108 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_2 2
CS2 – Pmod 6 pin8
Definition at line 112 of file 23/emsk_hardware.h.
#define EMSK_SPI_LINE_SDCARD 3
CS3 – On-board SD card
Definition at line 109 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_SDCARD 3
CS3 – On-board SD card
Definition at line 113 of file 23/emsk_hardware.h.
#define EMSK_SPI_LINE_SFLASH 5
CS5 – On-board SPI Flash memory
Definition at line 111 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_SFLASH 5
CS5 – On-board SPI Flash memory
Definition at line 115 of file 23/emsk_hardware.h.
#define EMSK_SPI_LINE_SPISLAVE 4
CS4 – Internal SPI slave
Definition at line 110 of file 22/emsk_hardware.h.
#define EMSK_SPI_LINE_SPISLAVE 4
CS4 – Internal SPI slave
Definition at line 114 of file 23/emsk_hardware.h.
#define INTNO_DMA_COMPLETE 22
Core DMA Controller Complete
Definition at line 92 of file 23/emsk_hardware.h.
#define INTNO_DMA_ERROR 23
Core DMA Controller Error
Definition at line 93 of file 23/emsk_hardware.h.
#define INTNO_DMA_START 22
Core DMA Controller
Definition at line 91 of file 23/emsk_hardware.h.
#define INTNO_DW_TMR0 31
DW Timer 0
Definition at line 99 of file 22/emsk_hardware.h.
#define INTNO_DW_TMR0 33
DW Timer 0
Definition at line 103 of file 23/emsk_hardware.h.
#define INTNO_DW_TMR1 32
DW Timer 1
Definition at line 100 of file 22/emsk_hardware.h.
#define INTNO_DW_TMR1 34
DW Timer 1
Definition at line 104 of file 23/emsk_hardware.h.
#define INTNO_DW_WDT 30
WDT
Definition at line 98 of file 22/emsk_hardware.h.
#define INTNO_DW_WDT 32
WDT
Definition at line 102 of file 23/emsk_hardware.h.
#define INTNO_GMAC 35
GMAC
Definition at line 103 of file 22/emsk_hardware.h.
#define INTNO_GPIO 22
GPIO controller
Definition at line 90 of file 22/emsk_hardware.h.
#define INTNO_GPIO 24
GPIO controller
Definition at line 94 of file 23/emsk_hardware.h.
#define INTNO_I2C0 23
I2C_0 controller
Definition at line 91 of file 22/emsk_hardware.h.
#define INTNO_I2C0 25
I2C_0 controller
Definition at line 95 of file 23/emsk_hardware.h.
#define INTNO_I2C1 24
I2C_1 controller
Definition at line 92 of file 22/emsk_hardware.h.
#define INTNO_I2C1 26
I2C_1 controller
Definition at line 96 of file 23/emsk_hardware.h.
#define INTNO_I2S_Master_In 33
I2S Master In
Definition at line 101 of file 22/emsk_hardware.h.
#define INTNO_I2S_Master_Out 34
I2S Master Out
Definition at line 102 of file 22/emsk_hardware.h.
#define INTNO_SECURE_TIMER0 20
Core Secure Timer 0
Definition at line 90 of file 23/emsk_hardware.h.
#define INTNO_SPI_MASTER 25
SPI Master controller
Definition at line 93 of file 22/emsk_hardware.h.
#define INTNO_SPI_MASTER 27
SPI Master controller
Definition at line 97 of file 23/emsk_hardware.h.
#define INTNO_SPI_SLAVE 26
SPI Slave controller
Definition at line 94 of file 22/emsk_hardware.h.
#define INTNO_SPI_SLAVE 28
SPI Slave controller
Definition at line 98 of file 23/emsk_hardware.h.
#define INTNO_TIMER0 16
ARC Timer0
Definition at line 88 of file 23/emsk_hardware.h.
#define INTNO_TIMER0 16
ARC Timer0
Definition at line 88 of file 22/emsk_hardware.h.
#define INTNO_TIMER1 17
ARC Timer1
Definition at line 89 of file 23/emsk_hardware.h.
#define INTNO_TIMER1 17
ARC Timer1
Definition at line 89 of file 22/emsk_hardware.h.
#define INTNO_UART0 27
UART0
Definition at line 95 of file 22/emsk_hardware.h.
#define INTNO_UART0 29
UART0
Definition at line 99 of file 23/emsk_hardware.h.
#define INTNO_UART1 28
UART1
Definition at line 96 of file 22/emsk_hardware.h.
#define INTNO_UART1 30
UART1
Definition at line 100 of file 23/emsk_hardware.h.
#define INTNO_UART2 29
UART2
Definition at line 97 of file 22/emsk_hardware.h.
#define INTNO_UART2 31
UART2
Definition at line 101 of file 23/emsk_hardware.h.
#define REL_REGBASE_GMAC (0x0000E000U)
GMAC
Definition at line 85 of file 22/emsk_hardware.h.
#define REL_REGBASE_GPIO0 (0x00002000U)
GPIO 0 Onboard
Definition at line 72 of file 11/emsk_hardware.h.
#define REL_REGBASE_GPIO0 (0x00002000U)
GPIO 0 Onboard
Definition at line 73 of file 23/emsk_hardware.h.
#define REL_REGBASE_GPIO0 (0x00002000U)
GPIO 0 Onboard
Definition at line 73 of file 22/emsk_hardware.h.
#define REL_REGBASE_I2C0 (0x00004000U)
I2C 0
Definition at line 74 of file 11/emsk_hardware.h.
#define REL_REGBASE_I2C0 (0x00004000U)
I2C 0
Definition at line 75 of file 23/emsk_hardware.h.
#define REL_REGBASE_I2C0 (0x00004000U)
I2C 0
Definition at line 75 of file 22/emsk_hardware.h.
#define REL_REGBASE_I2C1 (0x00005000U)
I2C 1
Definition at line 76 of file 22/emsk_hardware.h.
#define REL_REGBASE_I2C1 (0x00005000U)
I2C 1
Definition at line 76 of file 23/emsk_hardware.h.
#define REL_REGBASE_I2S_MASTER_IN (0x0000C000U)
I2S Master In
Definition at line 83 of file 22/emsk_hardware.h.
#define REL_REGBASE_I2S_MASTER_OUT (0x0000D000U)
I2S Master Out
Definition at line 84 of file 22/emsk_hardware.h.
#define REL_REGBASE_PINMUX (0x00000000U)
PINMUX
Definition at line 71 of file 23/emsk_hardware.h.
#define REL_REGBASE_PINMUX (0x00000000U)
PINMUX
Definition at line 71 of file 11/emsk_hardware.h.
Referenced by emsk_mux_init().
#define REL_REGBASE_PINMUX (0x00000000U)
PINMUX
Definition at line 71 of file 22/emsk_hardware.h.
#define REL_REGBASE_SPI0 (0x00006000U)
SPI Master
Definition at line 76 of file 11/emsk_hardware.h.
#define REL_REGBASE_SPI0 (0x00006000U)
SPI Master
Definition at line 77 of file 23/emsk_hardware.h.
#define REL_REGBASE_SPI0 (0x00006000U)
SPI Master
Definition at line 77 of file 22/emsk_hardware.h.
#define REL_REGBASE_SPI1 (0x00007000U)
SPI Slave
Definition at line 77 of file 11/emsk_hardware.h.
#define REL_REGBASE_SPI1 (0x00007000U)
SPI Slave
Definition at line 78 of file 23/emsk_hardware.h.
#define REL_REGBASE_SPI1 (0x00007000U)
SPI Slave
Definition at line 78 of file 22/emsk_hardware.h.
#define REL_REGBASE_SPI_MST_CS_CTRL (0x00000014U)
SPI Master Select Ctrl
Definition at line 72 of file 22/emsk_hardware.h.
Referenced by dw_spi_0_install().
#define REL_REGBASE_SPI_MST_CS_CTRL (0x00000014U)
SPI Master Select Ctrl
Definition at line 72 of file 23/emsk_hardware.h.
#define REL_REGBASE_TIMERS (0x00003000U)
DW TIMER
Definition at line 74 of file 22/emsk_hardware.h.
#define REL_REGBASE_TIMERS (0x00003000U)
DW TIMER
Definition at line 74 of file 23/emsk_hardware.h.
#define REL_REGBASE_UART0 (0x00008000U)
UART0 is connected to PMOD
Definition at line 78 of file 11/emsk_hardware.h.
#define REL_REGBASE_UART0 (0x00008000U)
UART0 is connected to PMOD
Definition at line 79 of file 23/emsk_hardware.h.
#define REL_REGBASE_UART0 (0x00008000U)
UART0 is connected to PMOD
Definition at line 79 of file 22/emsk_hardware.h.
#define REL_REGBASE_UART1 (0x00009000U)
UART1 is USB-UART use UART1 as default
Definition at line 79 of file 11/emsk_hardware.h.
#define REL_REGBASE_UART1 (0x00009000U)
UART1 is USB-UART use UART1 as default
Definition at line 80 of file 23/emsk_hardware.h.
#define REL_REGBASE_UART1 (0x00009000U)
UART1 is USB-UART use UART1 as default
Definition at line 80 of file 22/emsk_hardware.h.
#define REL_REGBASE_UART2 (0x0000A000U)
UART2
Definition at line 81 of file 23/emsk_hardware.h.
#define REL_REGBASE_UART2 (0x0000A000U)
UART2
Definition at line 81 of file 22/emsk_hardware.h.
#define REL_REGBASE_WDT (0x0000B000U)
WDT
Definition at line 82 of file 22/emsk_hardware.h.
#define REL_REGBASE_WDT (0x0000B000U)
WDT
Definition at line 82 of file 23/emsk_hardware.h.
Function Documentation
void board_delay_ms (uint32_t ms, uint8_t os_compat)
provide MS delay function
this function needs a 1-MS timer interrupt to work. For bare-metal, it is implemented in this file. For OS, you must call board_timer_update in the OS 1-MS timer interrupt when the bare-metal timer interrupt is not ready
Parameters
[in] ms MS to delay
[in] os_compat Enable or disable When this delay is enabled, use the OS delay function, if one is provided. See OSP_DELAY_OS_COMPAT_ENABLE and OSP_DELAY_OS_COMPAT_DISABLE
Definition at line 184 of file axs_timer.c.
uint64_t board_get_cur_us (void)
get current passed us since timer init
Return values
us count in 64 bit format
us count in 64bit format
Definition at line 158 of file axs_timer.c.
uint64_t board_get_hwticks (void)
get current cpu hardware ticks
Return values
hardware ticks count in 64 bit format
hardware ticks count in 64bit format
Definition at line 142 of file axs_timer.c.
void board_init (void)
Board init routine MUST be called in each application.
Note
It is better to disable interrupts when calling this function remember to enable interrupt when you want to use them
Definition at line 110 of file emsk_init.c.
References emsk_gpio_init(), emsk_mux_init(), emsk_timer_init(), and timer_init().
void board_timer_update (uint32_t precision)
Update timer counter and other MS period operation in cycling interrupt and must be called periodically.
When the OS timer interrupt is in conflict with the bare-metal timer interrupt, put this function into the OS timer interrupt
Parameters
[in] precision interrupt-period precision in Hz
Definition at line 87 of file axs_timer.c.