embARC: NSIM UART Object
NSIM UART Object
BSP Layer » NSIM BSP » NSIM Peripheral Driver Module
NSIM UART Objects.
Files
file nsim_uart_obj.c
file nsim_uart_obj.h
header file of uart object instantiation in nsim
Functions
DEV_UART_PTR uart_get_dev (int32_t uart_id)
get one uart device structure
void nsim_uart_all_install (void)
install all uart objects
NSIM UART 0 Object Instantiation
DEV_UART nsim_uart_0
static int32_t nsim_uart_0_open (uint32_t baud)
nsim uart 0 open
static int32_t nsim_uart_0_close (void)
nsim uart 0 close
static int32_t nsim_uart_0_control (uint32_t ctrl_cmd, void *param)
nsim uart 0 control
static int32_t nsim_uart_0_write (const void *data, uint32_t len)
nsim uart 0 write
static int32_t nsim_uart_0_read (void *data, uint32_t len)
nsim uart 0 close
static void nsim_uart_0_install (void)
install nsim uart 0 to system
NSIM UART Object Number
#define DW_UART_NUM (1)
NSIM UART Object ID Macros
#define NSIM_UART_0_ID 0
NSIM UART Object Control Macros
#define USE_NSIM_UART_0 1
Detailed Description
NSIM UART Objects.
Macro Definition Documentation
#define DW_UART_NUM (1)
NSIM UART valid number
Definition at line 52 of file nsim_uart_obj.h.
#define NSIM_UART_0_ID 0
uart 0 id macro
Definition at line 59 of file nsim_uart_obj.h.
Referenced by uart_get_dev().
#define USE_NSIM_UART_0 1
enable use nsim uart 0 (stdio)
Definition at line 66 of file nsim_uart_obj.h.
Function Documentation
void nsim_uart_all_install (void)
install all uart objects
Note
MUST be called during system init
Definition at line 151 of file nsim_uart_obj.c.
References nsim_uart_0_install().
Referenced by uart_get_dev().
DEV_UART_PTR uart_get_dev (int32_t uart_id)
get one uart device structure
get an uart device by uart device id.
Definition at line 125 of file nsim_uart_obj.c.
References dw_uart_0, DW_UART_0_ID, dw_uart_1, DW_UART_1_ID, dw_uart_2, DW_UART_2_ID, dw_uart_all_install(), nsim_uart_0, NSIM_UART_0_ID, and nsim_uart_all_install().
Variable Documentation
DEV_UART nsim_uart_0
nsim uart object
Definition at line 65 of file nsim_uart_obj.c.
Referenced by nsim_uart_0_install(), and uart_get_dev().