embARC: hm1x.c File Reference
hm1x.c File Reference
HM-1X BLE driver.
#include "embARC_toolchain.h"
#include "embARC_error.h"
#include "hm1x.h"
#include "stdio.h"
#include "string.h"
#include "dev_uart.h"
#include "board.h"
#include "embARC_debug.h"
Macros
#define HM1X_TIMENOW() OSP_GET_CUR_MS()
#define HM1X_READ_TMOUT 500
#define HM1X_SYS_DELAY_MS 550
#define MAX_READ_CNT 20
#define MAX_CMD_LENGTH 32
#define MAX_RESP_LENGTH 32
#define AT_TEST_PREFIX "AT"
#define OK_PREFIX "OK"
#define AT_CMD_PREFIX "AT+"
#define OK_SET_PREFIX "OK+Set:"
#define OK_GET_PREFIX "OK+Get:"
#define AT_ROLE_COMMAND "ROLE"
#define AT_MODE_COMMAND "MODE"
#define AT_TYPE_COMMAND "TYPE"
#define CMD_BAUD_SET_PREFIX "AT+BAUD"
#define CMD_RESET_PREFIX "AT+RESET"
#define CMD_RENEW_PREFIX "AT+RENEW"
#define BAUD_INDEX_MAX 8
#define BAUD_INDEX_MIN 0
#define ENABLE_HM1X_DEBUG
#define HM1X_DEBUG(fmt,...) EMBARC_PRINTF(fmt, ##__VA_ARGS__)
#define EMSK_BLE_CHECK_EXP(EXPR, ERCD, ERROR_CODE) CHECK_EXP(EXPR, ERCD, ERROR_CODE, error_exit)
#define EMSK_BLE_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
Functions
static void _hm1x_delay (uint32_t ms)
Internal delay function used by hm1x.
static int32_t _hm1x_baudrate_map (uint32_t baudrate)
get the baudrate map of hm1x, return the index of baudrate map in hm1x
void hm1x_flush (HM1X_DEF_PTR obj)
Flush the hm1x input data.
int32_t hm1x_init (HM1X_DEF_PTR obj, uint32_t baudrate)
Init HM1X BLE device.
int32_t hm1x_deinit (HM1X_DEF_PTR obj)
Deinit HM1X BLE device.
uint32_t hm1x_write (HM1X_DEF_PTR obj, uint8_t *buf, uint32_t cnt)
Write data to HM1X.
uint32_t hm1x_read (HM1X_DEF_PTR obj, uint8_t *buf, uint32_t cnt)
Read data from HM1X.
int32_t hm1x_exec_command (HM1X_DEF_PTR obj, char *cmd, char *resp, uint32_t wait_ms)
Execute command and wait for response with timeout.
int32_t hm1x_exec_cmd_chkresp (HM1X_DEF_PTR obj, char *cmd, char *resp_prefix, char *resp_data, uint32_t max_try)
Execute command and check whether the response prefix matches.
int32_t hm1x_set_param (HM1X_DEF_PTR obj, char *param, char *val)
HM1X set param, value and param must end with '\0', E_OK for success, -1 for fail.
int32_t hm1x_get_param (HM1X_DEF_PTR obj, char *param, char *r_val)
HM1X get param, cmd and val must contain '\0' end, >=0 for success, <0 for fail.
int32_t hm1x_set_param_u8 (HM1X_DEF_PTR obj, char *param, uint8_t val)
set a 8bits long parameter of hm1x, E_OK for success, -1 for fail
int32_t hm1x_set_role (HM1X_DEF_PTR obj, uint32_t role)
set working role, 0 for success, -1 for fail
int32_t hm1x_set_mode (HM1X_DEF_PTR obj, uint32_t mode)
set working mode, 0 for success, -1 for fail
int32_t hm1x_set_type (HM1X_DEF_PTR obj, uint32_t type)
set working type, 0 for success, -1 for fail
int32_t hm1x_set_baud (HM1X_DEF_PTR obj, uint32_t baudrate)
set baudrate of hm1x, >=0 for success, <0 for fail
int32_t hm1x_test_command (HM1X_DEF_PTR obj)
the test command for hm1x ble module, >=0 for success, <0 for fail
int32_t hm1x_restart (HM1X_DEF_PTR obj)
reset and restart the module, >=0 for success, <0 for fail
int32_t hm1x_renew (HM1X_DEF_PTR obj)
renew the module, >=0 for success, <0 for fail
Detailed Description
HM-1X BLE driver.
Implement hm-1x ble driver.
Definition in file hm1x.c.
Function Documentation
int32_t hm1x_deinit (HM1X_DEF_PTR obj)
Deinit HM1X BLE device.
Parameters
obj HM1X type object
Return values
E_OK success
!E_OK fail
Definition at line 178 of file hm1x.c.
References E_OK, dev_uart::uart_close, and uart_get_dev().
int32_t hm1x_exec_cmd_chkresp (HM1X_DEF_PTR obj, char * cmd, char * resp_prefix, char * resp_data, uint32_t max_try)
Execute command and check whether the response prefix matches.
Parameters
cmd Command to send to the BLE device using the UART
resp_prefix Response prefix string, like OK. Must not be NULL
resp_data Response data buffer, may be NULL
max_try How many times this function can try to run
Return values
<0 Fail
>=0 Response data length
Definition at line 263 of file hm1x.c.
References E_PAR, and hm1x_exec_command().
Referenced by hm1x_get_param(), hm1x_renew(), hm1x_restart(), hm1x_set_baud(), hm1x_set_param(), and hm1x_test_command().
int32_t hm1x_exec_command (HM1X_DEF_PTR obj, char * cmd, char * resp, uint32_t wait_ms)
Execute command and wait for response with timeout.
Parameters
cmd Command to send to the BLE device using the UART
resp Response buffer, must not be NULL
wait_ms Maximum MS to wait for response
Return values
<0 Fail
>=0 Response string count
Definition at line 233 of file hm1x.c.
References E_PAR, hm1x_read(), and hm1x_write().
Referenced by hm1x_exec_cmd_chkresp().
int32_t hm1x_get_param (HM1X_DEF_PTR obj, char * param, char * r_val)
HM1X get param, cmd and val must contain '\0' end, >=0 for success, <0 for fail.
only for return resp with OK+Get:
Definition at line 329 of file hm1x.c.
References E_BOVR, E_PAR, and hm1x_exec_cmd_chkresp().
int32_t hm1x_init (HM1X_DEF_PTR obj, uint32_t baudrate)
Init HM1X BLE device.
Parameters
obj HM1X type object
baudrate ble working baudrate
Return values
E_OK success
!E_OK fail
Definition at line 156 of file hm1x.c.
References E_OBJ, E_OK, E_OPNED, UART_CMD_SET_BAUD, dev_uart::uart_control, uart_get_dev(), and dev_uart::uart_open.
uint32_t hm1x_read (HM1X_DEF_PTR obj, uint8_t * buf, uint32_t cnt)
Read data from HM1X.
Parameters
buf Buffer to be read to
cnt Number to be read
Return values
<0 Failed to read
>=0 Read count
Definition at line 209 of file hm1x.c.
References E_OBJ, UART_CMD_GET_RXAVAIL, dev_uart::uart_control, uart_get_dev(), and dev_uart::uart_read.
Referenced by hm1x_exec_command().
int32_t hm1x_set_param (HM1X_DEF_PTR obj, char * param, char * val)
HM1X set param, value and param must end with '\0', E_OK for success, -1 for fail.
only for return resp with OK+Set:
Definition at line 304 of file hm1x.c.
References E_BOVR, E_OK, E_PAR, and hm1x_exec_cmd_chkresp().
Referenced by hm1x_set_param_u8().
int32_t hm1x_set_param_u8 (HM1X_DEF_PTR obj, char * param, uint8_t val)
set a 8bits long parameter of hm1x, E_OK for success, -1 for fail
only for return resp with OK+Set:
Definition at line 350 of file hm1x.c.
References hm1x_set_param().
Referenced by hm1x_set_mode(), hm1x_set_role(), and hm1x_set_type().
uint32_t hm1x_write (HM1X_DEF_PTR obj, uint8_t * buf, uint32_t cnt)
Write data to HM1X.
Parameters
buf Buffer to be written
cnt Number to be written
Return values
<0 Failed to write
>=0 Written count
Definition at line 193 of file hm1x.c.
References E_OBJ, uart_get_dev(), and dev_uart::uart_write.
Referenced by hm1x_exec_command().