embARC: rw009.c File Reference
rw009.c File Reference
rw009 wifi module driver
#include <string.h>
#include "embARC.h"
#include "rw009.h"
#include "embARC_debug.h"
Data Structures
struct rw009_spi_request
struct rw009_spi_response
struct rw009_spi_data_packet
struct _rw009_ap_info
struct _rw009_cmd_init
struct _rw009_resp_init
struct _rw009_cmd_easy_join
struct _rw009_cmd_join
struct _rw009_cmd_rssi
struct _rw009_cmd_softap
struct _rw009_resp_join
struct rw009_cmd
struct rw009_resp
Macros
#define DEBUG
#define RW009_SPI_ID DW_SPI_0_ID
#define RW009_SPI_LINE EMSK_SPI_LINE_1
by default, use J5
#define RW009_GPIO_ID EMSK_GPIO_PORT_A
#define RW009_INT_BUSY_PIN (24)
#define RW009_RST_PIN (25)
#define RW009_CS_PIN (26)
#define RW009_RST_PIN_MASK (1 << RW009_RST_PIN)
#define RW009_INT_BUSY_PIN_MASK (1 << RW009_INT_BUSY_PIN)
#define RW009_CS_PIN_MASK (1 << RW009_CS_PIN)
#define RW009_SPIFREQ BOARD_SPI_FREQ
RW009 WIFI SPI FREQ & CLK MODE SETTINGS.
#define RW009_SPICLKMODE BOARD_SPI_CLKMODE
#define RW009_CHECK_EXP(EXPR, ERROR_CODE) CHECK_EXP(EXPR, ercd, ERROR_CODE, error_exit)
#define RW009_REQ_MAGIC1 (0x67452301)
#define RW009_REQ_MAGIC2 (0xEFCDAB89)
#define RW009_REQ_FLAG_MRDY (0x01) /* master ready to transfer */
#define RW009_RESP_FLAG_SRDY (0x01) /* rw009 ready to transfer */
#define RW009_RESP_MAGIC1 (0x98BADCFE)
#define RW009_RESP_MAGIC2 (0x10325476)
#define RW009_SPI_MAX_DATA_LEN (1520)
#define RW009_CMD_PACKET_HRD_LEN (8)
#define RW009_SSID_NAME_LENGTH_MAX (32)
#define RW009_PASSWORD_LENGTH_MAX (64)
#define RW009_CMD_INIT (128)
#define RW009_CMD_SCAN (129)
#define RW009_CMD_JOIN (130)
#define RW009_CMD_EASY_JOIN (131)
#define RW009_CMD_RSSI (132)
#define RW009_CMD_SOFTAP (133)
#define RW009_CMD_NULL (0xff)
#define RW009_SCAN_TIME_MS (3000) /* 3000 ms for scan */
#define RW009_SCAN_AP_NUM (5)
#define RW009_INIT_TIME_MS (3000) /* 3000 ms for init time out */
#define RW009_INIT_RETRY (3) /* retry times for init */
#define RW009_CON_TIME_MS (10000) /* 10000 ms for connection time out */
#define RW009_DATA_PACKET_HDR_LEN (8)
#define RW009_CMD_PACKET_HDR_LEN (8)
#define RW009_RESET_ASSERT (~RW009_RST_PIN_MASK)
#define RW009_RESET_UNASSERT (RW009_RST_PIN_MASK)
#define RW009_RESET_ASSERT_MS 10
#define RW009_RESET_DELAY_MS 200
Typedefs
typedef struct _rw009_ap_info rw009_ap_info
typedef struct _rw009_cmd_init rw009_cmd_init
typedef struct _rw009_resp_init rw009_resp_init
typedef struct _rw009_cmd_easy_join rw009_cmd_easy_join
typedef struct _rw009_cmd_join rw009_cmd_join
typedef struct _rw009_cmd_rssi rw009_cmd_rssi
typedef struct _rw009_cmd_softap rw009_cmd_softap
typedef struct _rw009_resp_join rw009_resp_join
Enumerations
enum spi_data_type { data_type_eth_data = 0, data_type_cmd, data_type_resp, data_type_status }
enum wifi_mode_t { MODE_STATION = 0, MODE_SOFTAP = 1 }
Functions
static void rw009_isr (void *ptr)
interrupt service routine for rw009
static uint32_t rw009_timer_read_ms (void)
get current system time in millisecond
static void rw009_timer_delay (uint32_t ms)
static int32_t rw009_spi_open (uint32_t freq, uint32_t clk_mode)
static int32_t rw009_gpio_open (void)
static void rw009_int_enable (void)
enable rw009 interrupt
static void rw009_int_disable (void)
disable rw009 interrupt
static int rw009_is_busy (void)
poll rw009 whether is busy
static void rw009_reset (void)
reset rw009
static void rw009_select (void)
chip select rw009
static void rw009_deselect (void)
chip de-select rw009
static int cmd_resp_handler (DEV_WNIC *rw009_wnic, struct rw009_resp *resp)
cmd response handler
static int rw009_xfer (DEV_WNIC *rw009_wnic, struct rw009_spi_data_packet *out, struct rw009_spi_data_packet *in)
transfer function between rw009 and host
static int32_t rw009_cmd (DEV_WNIC *rw009_wnic, uint32_t cmd, void *args)
send cmd to rw009
int32_t rw009_wnic_get_info (DEV_WNIC *rw009_wnic, uint32_t cmd, void *rinfo)
int32_t rw009_wnic_control (DEV_WNIC *rw009_wnic, uint32_t ctrl_cmd, void *param)
int32_t rw009_wnic_init (DEV_WNIC *rw009_wnic, uint32_t network_type)
int32_t rw009_poll_init_status (DEV_WNIC *rw009_wnic)
int32_t rw009_poll_busy_status (DEV_WNIC *rw009_wnic)
int32_t rw009_set_network_type (DEV_WNIC *rw009_wnic, uint32_t type)
int32_t rw009_set_macaddr (DEV_WNIC *rw009_wnic, uint8_t *mac)
int32_t rw009_get_macaddr (DEV_WNIC *rw009_wnic, uint8_t *mac)
int32_t rw009_start_scan (DEV_WNIC *rw009_wnic)
int32_t rw009_stop_scan (DEV_WNIC *rw009_wnic)
int32_t rw009_poll_scan_status (DEV_WNIC *rw009_wnic)
int32_t rw009_get_scan_result_cnt (DEV_WNIC *rw009_wnic)
int32_t rw009_get_scan_result (DEV_WNIC *rw009_wnic, uint32_t index, WNIC_SCAN_RESULT *result)
int32_t rw009_wnic_connect (DEV_WNIC *rw009_wnic, uint32_t security, const uint8_t *ssid, WNIC_AUTH_KEY *key)
int32_t rw009_poll_conn_status (DEV_WNIC *rw009_wnic)
int32_t rw009_wnic_disconnect (DEV_WNIC *rw009_wnic)
int32_t rw009_prepare_tx (DEV_WNIC *rw009_wnic, uint32_t tx_len)
int32_t rw009_add_tx_data (DEV_WNIC *rw009_wnic, uint8_t *p_buf, uint32_t len)
int32_t rw009_commit_tx (DEV_WNIC *rw009_wnic, uint32_t len)
int32_t rw009_prepare_rx (DEV_WNIC *rw009_wnic)
int32_t rw009_get_rx_data (DEV_WNIC *rw009_wnic, uint8_t *p_buf, uint32_t len)
int32_t rw009_accept_rx (DEV_WNIC *rw009_wnic)
int32_t rw009_config_power_mode (DEV_WNIC *rw009_wnic, int32_t power_mode)
int32_t rw009_poll_power_mode (DEV_WNIC *rw009_wnic)
int32_t rw009_wnic_reset (DEV_WNIC *rw009_wnic)
void rw009_period_process (DEV_WNIC *rw009_wnic, void *ptr)
Variables
static DEV_SPI * rw009_spi_ptr
static DEV_GPIO * rw009_gpio_ptr
static struct rw009_spi_data_packet snd_packet
static uint32_t snd_cnt
static struct rw009_spi_data_packet rcv_packet
static uint32_t rcv_cnt
static uint32_t last_cmd = RW009_CMD_NULL
static uint32_t rw009_to_send = 0
static uint32_t scan_timer = 0
static uint32_t scan_cnt = 0
static rw009_ap_info scanned_ap [RW009_SCAN_AP_NUM]
static uint32_t init_timer = 0
static uint32_t init_try = 0
static uint32_t conn_timer = 0
static uint32_t cs_line = RW009_SPI_LINE
Detailed Description
rw009 wifi module driver
Definition in file rw009.c.
Function Documentation
static int cmd_resp_handler (DEV_WNIC * rw009_wnic, struct rw009_resp * resp) static
cmd response handler
Parameters
rw009_wnic rw009 object
rw009_resp response from rw009
Returns
error code
Definition at line 422 of file rw009.c.
References dev_wnic_info::busy_status, dev_wnic_info::conn_status, E_CLS, E_OBJ, E_OK, E_PAR, dev_wnic_info::init_status, dev_wnic_info::mac_addr, rw009_resp::resp, dev_wnic_info::scan_status, WNIC_DURING_SCAN, WNIC_HDR_LEN, dev_wnic::wnic_info, and dev_wnic::wnic_on_ops.
Referenced by rw009_xfer().
static int32_t rw009_cmd (DEV_WNIC * rw009_wnic, uint32_t cmd, void * args) static
send cmd to rw009
Parameters
rw009_wnic rw009 object
cmd command for rw009
args arguments of command
Returns
< 0 failed
Definition at line 622 of file rw009.c.
References cpu_lock_save(), cpu_unlock_restore(), rw009_cmd::params, rw009_timer_read_ms(), and rw009_xfer().
static int rw009_is_busy (void) static
poll rw009 whether is busy
Returns
1 busy, 0 idle
Definition at line 350 of file rw009.c.
References dev_gpio::gpio_read.
Referenced by rw009_xfer().
static void rw009_isr (void * ptr) static
interrupt service routine for rw009
Parameters
ptr parameter to isr
Definition at line 402 of file rw009.c.
References rw009_int_disable().
static uint32_t rw009_timer_read_ms (void) static
get current system time in millisecond
Returns
millisecond
Definition at line 258 of file rw009.c.
Referenced by rw009_cmd().
static int rw009_xfer (DEV_WNIC * rw009_wnic, struct rw009_spi_data_packet * out, struct rw009_spi_data_packet * in) static
transfer function between rw009 and host
Parameters
rw009_wnic rw009 object
out output packet
rw009_spi_data_packet input packet
Returns
< 0 error
Definition at line 522 of file rw009.c.
References cmd_resp_handler(), DEV_SPI_XFER_SET_NEXT, DEV_SPI_XFER_SET_RXBUF, DEV_SPI_XFER_SET_TXBUF, E_OBJ, E_OK, E_SYS, dev_wnic_info::init_status, rw009_deselect(), rw009_int_disable(), rw009_int_enable(), rw009_is_busy(), rw009_select(), SPI_CMD_TRANSFER_POLLING, dev_spi::spi_control, dev_spi::spi_read, dev_spi::spi_write, dev_wnic::wnic_info, and dev_wnic::wnic_on_ops.
Referenced by rw009_cmd().