embARC: task.c File Reference
task.c File Reference
embARC Applications » All embARC ApplicationsembARC Applications » embARC Applications for Different Operating Systems » | embARC FreeRTOS ApplicationsembARC Applications » embARC Applications for Different Middlewares » | embARC FatFS Applications » embARC IOT iLight synthesize
task in FreeRTOS
#include "task.h"
#include "light_mode.h"
#include "light_driver.h"
#include "imu.h"
#include "scope.h"
#include "mic.h"
#include "mpu6050.h"
#include "rtc.h"
Macros
#define led_display_task_prioroties ((configMAX_PRIORITIES - 1) | portPRIVILEGE_BIT)
#define pattern_change_task_prioroties ((configMAX_PRIORITIES - 2) | portPRIVILEGE_BIT)
#define light_mode_task_prioroties ((configMAX_PRIORITIES - 3) | portPRIVILEGE_BIT)
#define light_mode_music_task_prioroties ((configMAX_PRIORITIES - 3) | portPRIVILEGE_BIT)
#define mpu_task_prioroties ((configMAX_PRIORITIES - 4) | portPRIVILEGE_BIT)
#define light_mode_alarm_task_prioroties ((configMAX_PRIORITIES - 3) | portPRIVILEGE_BIT)
Functions
static void led_display_task (void *par)
task for led displaying.
static void pattern_change_task (void *par)
pattern change task in FreeRTOS.
static void light_mode_task (void *par)
light mode task in FreeRTOS.
static void light_mode_music_task (void *par)
light mode music task in FreeRTOS.
static void mpu_task (void *par)
mpu task in FreeRTOS.
static void light_mode_alarm_task (void *par)
light mode alarm task in FreeRTOS.
static void perf_init (unsigned int id)
performance timer initialization.
static void perf_start (void)
performance timer start.
static unsigned int perf_end (void)
performance timer end, and return the time passed.
static void led_turn (uint8_t led)
turn around one bit of led.
uint8_t task_init (void)
create all the task at appropriate order.
Variables
static TaskHandle_t led_display_task_handle = NULL
static TaskHandle_t light_mode_task_handle = NULL
static TaskHandle_t light_mode_music_task_handle = NULL
static TaskHandle_t mpu_task_handle = NULL
static TaskHandle_t light_mode_alarm_task_handle = NULL
TaskHandle_t pattern_change_task_handle = NULL
SemaphoreHandle_t recognition_semaphore = NULL
QueueHandle_t led_queue = NULL
QueueHandle_t mode_info_queue = NULL
static uint32_t mpu_cycle
static uint32_t time_clock
static volatile uint32_t start = 0
static uint32_t perf_id = 0xFF
Detailed Description
task in FreeRTOS
Definition in file task.c.
Function Documentation
static void light_mode_music_task (void * par) static
light mode music task in FreeRTOS.
This task should execute exactly every MIC_PERIOD_TICK.
Definition at line 209 of file task.c.
References adc_get(), fft_Convert(), fft_Data(), fft_powerMag(), led_turn(), and light_mode_music().
Referenced by task_init().