embARC: tcn75.h File Reference
tcn75.h File Reference
header file of tcn75 temperature sensor driver
#include "dev_iic.h"
Data Structures
struct TCN75_DEF
Macros
#define TCN75_A0_PIN 1
#define TCN75_A1_PIN 1
#define TCN75_A2_PIN 0
#define TCN75_IIC_ADDRESS (0x48 + (TCN75_A2_PIN << 2) +(TCN75_A1_PIN << 1) + TCN75_A0_PIN)
#define TEMP_I2C_SLAVE_ADDRESS TCN75_IIC_ADDRESS
#define TCN75_DEFINE(NAME, I2C_ID, SLAVE_ADDRESS)
Typedefs
typedef struct TCN75_DEF * TCN75_DEF_PTR
Enumerations
enum TCN75_OP_MODE { TCN75_OP_MODE_NORMAL = 0, TCN75_OP_MODE_SHUTDOWN = 1 }
Functions
int32_t tcn75_sensor_init (TCN75_DEF_PTR obj)
temperature sensor init
int32_t tcn75_sensor_deinit (TCN75_DEF_PTR obj)
temperature sensor deinit
int32_t tcn75_sensor_mode (TCN75_DEF_PTR obj, int32_t mode)
temperature sensor deinit
int32_t tcn75_sensor_read (TCN75_DEF_PTR obj, float *val)
read temperature sensor value in 0.1c unit
Detailed Description
header file of tcn75 temperature sensor driver
Definition in file tcn75.h.
Macro Definition Documentation
#define TCN75_A0_PIN 1
I2C Serial Bus Address Selection Pin
Definition at line 41 of file tcn75.h.
#define TCN75_A1_PIN 1
I2C Serial Bus Address Selection Pin
Definition at line 42 of file tcn75.h.
#define TCN75_A2_PIN 0
I2C Serial Bus Address Selection Pin
Definition at line 43 of file tcn75.h.
#define TCN75_DEFINE (NAME, I2C_ID, SLAVE_ADDRESS)
Value:
TCN75_DEF __ ## NAME = { \
                        .i2c_id = I2C_ID, \
                        .slvaddr = SLAVE_ADDRESS, \
        }; \
        TCN75_DEF_PTR NAME = &__ ## NAME
Definition at line 66 of file tcn75.h.
Function Documentation
int32_t tcn75_sensor_deinit (TCN75_DEF_PTR obj)
temperature sensor deinit
Parameters
[in] obj temperature sensor object
Return values
E_OK init success
!E_OK init failed
Definition at line 167 of file tcn75.c.
References E_OK, dev_iic::iic_close, and iic_get_dev().
int32_t tcn75_sensor_init (TCN75_DEF_PTR obj)
temperature sensor init
Parameters
[in] obj temperature sensor object
Return values
E_OK init success
!E_OK init failed
Definition at line 141 of file tcn75.c.
References CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, IIC_SPEED_HIGH, and tcn75_sensor_mode().
int32_t tcn75_sensor_mode (TCN75_DEF_PTR obj, int32_t mode)
temperature sensor deinit
Parameters
[in] obj temperature sensor object
[in] mode sensor working mode, choose from enum sensor_op_mode
Return values
E_OK always return E_OK
Definition at line 186 of file tcn75.c.
References _tcn75_reg_read(), _tcn75_reg_write(), E_OK, and TCN75_REG_CONFIG.
Referenced by tcn75_sensor_init().
int32_t tcn75_sensor_read (TCN75_DEF_PTR obj, float * val)
read temperature sensor value in 0.1c unit
Parameters
[in] obj temperature sensor object
[out] val return temperature in degrees Celsius (°C)
Return values
E_OK read success
!E_OK read failed
Definition at line 205 of file tcn75.c.
References _tcn75_reg_read(), E_OBJ, E_OK, and TCN75_REG_TEMP.