/*
 ****************************************************************************
 *
 * avrtest - A simple simulator for the Atmel AVR family of microcontrollers
 *           designed to test the compiler
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ****************************************************************************
 */

#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

#include "sreg.h"

#define FUT_ADD8_RES    0x01FF
#define FUT_ADD8_V2_80  0x0200
#define FUT_ADD8_V1_80  0x0400
#define FUT_ADD8_V2_08  0x0800
#define FUT_ADD8_V1_08  0x1000

#define FUT_SUB8_RES    0x01FF
#define FUT_SUB8_V2_80  0x0200
#define FUT_SUB8_V1_80  0x0400
#define FUT_SUB8_V2_08  0x0800
#define FUT_SUB8_V1_08  0x1000

static int theSize;
static int theNum;


static void
table_start (const char *name, int size)
{
  theSize = size;
  theNum = 0;
  printf ("\nstatic const byte %s[%d] =\n  {", name, size);
}


static void
table_end (void)
{
  printf ("\n  };\n");
}


static void
table_add (int x)
{
  if (theNum % 16 == 0)
    printf ("\n    ");
  
  theNum++;

  printf ("%d%s", x, theNum == theSize ? "" : ", ");
}


static uint8_t
update_zns_flags (int result, uint8_t sreg)
{
  if ((result & 0xFF) == 0x00)
    sreg |= FLAG_Z;
  if (result & 0x80)
    sreg |= FLAG_N;
  if (((sreg & FLAG_N) != 0) != ((sreg & FLAG_V) != 0))
    sreg |= FLAG_S;
  return sreg;
}


static void
gen_flag_update_tables (void)
{
  int i, result, sreg;

  printf ("// Auto-generated file. Do not edit.\n"
          "// Generated by : gen-flag-tables\n"
          "// Included by  : avrtest.c\n");

  // build flag update table for 8 bit addition
  table_start ("flag_update_table_add8", 8192);
  for (i = 0; i < 8192; i++)
    {
      result = i & FUT_ADD8_RES;
      sreg = 0;
      if ((!(i & FUT_ADD8_V1_80) == !(i & FUT_ADD8_V2_80))
          && (!(result & 0x80) != !(i & FUT_ADD8_V1_80)))
        sreg |= FLAG_V;
      if (result & 0x100)
        sreg |= FLAG_C;
      if (((i & 0x1800) == 0x1800)
          || ((result & 0x08) == 0
              && ((i & 0x1800) != 0x0000)))
        sreg |= FLAG_H;
      sreg = update_zns_flags (result, sreg);
      table_add (sreg);
    }
  table_end ();

  // build flag update table for 8 bit subtraction
  table_start ("flag_update_table_sub8", 8192);
  for (i = 0; i < 8192; i++)
    {
      result = i & FUT_SUB8_RES;
      sreg = 0;
      if ((!(result & 0x80) == !(i & FUT_SUB8_V2_80))
          && (!(i & FUT_SUB8_V1_80) != !(i & FUT_SUB8_V2_80)))
        sreg |= FLAG_V;
      if (result & 0x100)
        sreg |= FLAG_C;
      if (((i & 0x1800) == 0x1800)
          || ((result & 0x08) == 0
              && ((i & 0x1800) != 0x0000)))
        sreg |= FLAG_H;
      sreg = update_zns_flags (result, sreg);
      table_add (sreg);
    }
  table_end ();

  // build flag update table for 8 bit rotation
  table_start ("flag_update_table_ror8", 512);
  for (i = 0; i < 512; i++)
    {
      result = i >> 1;
      sreg = 0;
      if (i & 0x01)
        sreg |= FLAG_C;
      if (((result & 0x80) != 0) != ((sreg & FLAG_C) != 0))
        sreg |= FLAG_V;
      sreg = update_zns_flags (result, sreg);
      table_add (sreg);
    }
  table_end ();

  // build flag update table for increment
  table_start ("flag_update_table_inc", 256);
  for (i = 0; i < 256; i++)
    {
      sreg = (i == 0x80) ? FLAG_V : 0;
      sreg = update_zns_flags (i, sreg);
      table_add (sreg);
    }
  table_end ();

  // build flag update table for decrement
  table_start ("flag_update_table_dec", 256);
  for (i = 0; i < 256; i++)
    {
      sreg = (i == 0x7F) ? FLAG_V : 0;
      sreg = update_zns_flags (i, sreg);
      table_add (sreg);
    }
  table_end ();

  // build flag update table for logical operations
  table_start ("flag_update_table_logical", 256);
  for (i = 0; i < 256; i++)
    {
      sreg = update_zns_flags (i, 0);
      table_add (sreg);
    }
  table_end ();
}

int main (void)
{
  gen_flag_update_tables ();
  return EXIT_SUCCESS;
}
