embARC: Interrupt
Interrupt
ARC HAL » Exception and Interrupt
Interrupt related definitions.
Files
file arc_exception.c
C Implementation of exception and interrupt management.
file arc_exception.h
header file of exception and interrupt management module
Macros
#define INT_PRI_MIN (-2)
#define INT_PRI_MAX (-1)
Typedefs
typedef void(* INT_HANDLER)(void *ptr)
the data type for interrupt handler
Functions
static void int_handler_default (void *p_excinf)
default interrupt handler
void exc_int_init (void)
intialize the exception and interrupt handling
int32_t int_handler_install (const uint32_t intno, INT_HANDLER handler)
install an interrupt handler
INT_HANDLER int_handler_get (const uint32_t intno)
get the installed an interrupt handler
Inline void arc_int_disable (const uint32_t intno)
disable the specific interrupt
Inline void arc_int_enable (const uint32_t intno)
enable the specific int
Inline uint32_t arc_int_enabled (const uint32_t intno)
check whether the specific int is enabled
Inline uint32_t arc_int_ipm_get (void)
get the interrupt priority mask
Inline void arc_int_ipm_set (uint32_t intpri)
set the interrupt priority mask
Inline uint32_t arc_int_pri_get (const uint32_t intno)
get current interrupt priority mask
Inline void arc_int_pri_set (const uint32_t intno, uint32_t intpri)
set interrupt priority
Inline void arc_int_secure_set (const uint32_t intno, uint32_t secure)
set interrupt secure or not secure
Inline uint32_t arc_int_probe (const uint32_t intno)
probe the pending status of interrupt
Inline void arc_int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Inline void arc_int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Inline void arc_lock (void)
lock cpu, disable interrupts
Inline void arc_unlock (void)
unlock cpu, enable interrupts to happen
Inline uint32_t arc_lock_save (void)
lock cpu and staus
Inline void arc_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Detailed Description
Interrupt related definitions.
Macro Definition Documentation
#define INT_PRI_MAX (-1)
the maximum interrupt priority
Definition at line 201 of file arc_exception.h.
Referenced by exc_int_init(), and int_ipm_set().
#define INT_PRI_MIN (-2)
the minimum interrupt priority
Definition at line 198 of file arc_exception.h.
Referenced by exc_int_init(), int_ipm_get(), int_ipm_set(), int_pri_get(), int_pri_set(), and main().
Function Documentation
Inline void arc_int_disable (const uint32_t intno)
disable the specific interrupt
Parameters
[in] intno interrupt number
Definition at line 207 of file arc_exception.h.
References AUX_IRQ_ENABLE, and AUX_IRQ_SELECT.
Referenced by int_disable().
Inline void arc_int_enable (const uint32_t intno)
enable the specific int
Parameters
[in] intno interrupt number
Definition at line 218 of file arc_exception.h.
References AUX_IRQ_ENABLE, and AUX_IRQ_SELECT.
Referenced by int_enable().
Inline uint32_t arc_int_enabled (const uint32_t intno)
check whether the specific int is enabled
Parameters
[in] intno interrupt number
Returns
0 disabled, 1 enabled
Definition at line 230 of file arc_exception.h.
References AUX_IRQ_ENABLE, and AUX_IRQ_SELECT.
Referenced by int_enabled().
Inline uint32_t arc_int_ipm_get (void)
get the interrupt priority mask
Returns
interrupt priority mask, negative num
Definition at line 241 of file arc_exception.h.
Referenced by int_ipm_get().
Inline void arc_int_ipm_set (uint32_t intpri)
set the interrupt priority mask
Parameters
[in] intpri interrupt priority
Definition at line 251 of file arc_exception.h.
Referenced by exc_int_init(), and int_ipm_set().
Inline void arc_int_level_config (const uint32_t intno, const uint32_t level)
config the interrupt level triggered or pulse triggered
Parameters
[in] intno interrupt number
[in] level,0-level trigger, 1-pluse triggered
Definition at line 333 of file arc_exception.h.
References AUX_IRQ_SELECT, and AUX_IRQ_TRIGGER.
Referenced by int_level_config().
Inline uint32_t arc_int_pri_get (const uint32_t intno)
get current interrupt priority mask
Parameters
[in] intno interrupt number
Definition at line 266 of file arc_exception.h.
References AUX_IRQ_PRIORITY, and AUX_IRQ_SELECT.
Referenced by int_pri_get().
Inline void arc_int_pri_set (const uint32_t intno, uint32_t intpri)
set interrupt priority
Parameters
[in] intno interrupt number
[in] intpri interrupt priority
Definition at line 278 of file arc_exception.h.
References AUX_IRQ_PRIORITY, and AUX_IRQ_SELECT.
Referenced by int_pri_set().
Inline uint32_t arc_int_probe (const uint32_t intno)
probe the pending status of interrupt
Parameters
[in] intno interrupt number
Returns
1 pending, 0 no pending
Definition at line 311 of file arc_exception.h.
References AUX_IRQ_PENDING, and AUX_IRQ_SELECT.
Referenced by int_probe().
Inline void arc_int_secure_set (const uint32_t intno, uint32_t secure)
set interrupt secure or not secure
Parameters
[in] intno interrupt number
[in] secure,0 for normal, >0 for secure
Definition at line 290 of file arc_exception.h.
References AUX_IRQ_PRIORITY, AUX_IRQ_PRIORITY_BIT_S, and AUX_IRQ_SELECT.
Referenced by int_secure_set().
Inline void arc_int_sw_trigger (const uint32_t intno)
trigger the interrupt in software
Parameters
[in] intno interrupt number
Definition at line 322 of file arc_exception.h.
References AUX_IRQ_HINT.
Referenced by int_sw_trigger().
Inline uint32_t arc_lock_save (void)
lock cpu and staus
Returns
cpu status
Definition at line 362 of file arc_exception.h.
References _arc_clri.
Referenced by cpu_lock_save(), and exc_int_init().
Inline void arc_unlock_restore (const uint32_t status)
unlock cpu with the specific status
Parameters
[in] status cpu status saved by cpu_lock_save
Definition at line 372 of file arc_exception.h.
References _arc_seti.
Referenced by cpu_unlock_restore(), and exc_int_init().
static void int_handler_default (void * p_excinf) static
default interrupt handler
Parameters
[in] p_excinf information for interrupt handler
Definition at line 94 of file arc_exception.c.
References AUX_IRQ_CAUSE.
INT_HANDLER int_handler_get (const uint32_t intno)
get the installed an interrupt handler
Parameters
[in] intno interrupt number
Returns
the installed interrupt handler or NULL
Definition at line 512 of file arc_exception.c.
int32_t int_handler_install (const uint32_t intno, INT_HANDLER handler)
install an interrupt handler
Parameters
[in] intno interrupt number
[in] handler interrupt handler to install
Definition at line 496 of file arc_exception.c.
Referenced by axs_timer_init(), dw_gpio_open(), dw_iic_enable_interrupt(), dw_iic_open(), dw_spi_enable_interrupt(), dw_spi_open(), dw_uart_enable_interrupt(), dw_uart_open(), emsk_timer_init(), main(), and nsim_timer_init().