embARC: EMSK PMOD-TMP Sensor Driver
EMSK PMOD-TMP Sensor Driver
BSP Layer » EMSK BSP » EMSK Peripheral Driver Module
EMSK PMOD Temperature Sensor Driver.
Files
file emsk_temperature.c
emsk pmod temperature sensor driver
file emsk_temperature.h
header file of emsk pmod temperature sensor driver
Macros
#define ADT7420_REG_TEMP_MSB 0x00
#define ADT7420_REG_TEMP_LSB 0x01
#define ADT7420_REG_STATUS 0x02
#define ADT7420_REG_CONFIG 0x03
#define ADT7420_REG_T_HIGH_MSB 0x04
#define ADT7420_REG_T_HIGH_LSB 0x05
#define ADT7420_REG_T_LOW_MSB 0x06
#define ADT7420_REG_T_LOW_LSB 0x07
#define ADT7420_REG_T_CRIT_MSB 0x08
#define ADT7420_REG_T_CRIT_LSB 0x09
#define ADT7420_REG_HIST 0x0A
#define ADT7420_REG_ID 0x0B
#define ADT7420_REG_RESET 0x2F
#define ADT7420_STATUS_T_LOW (1 << 4)
#define ADT7420_STATUS_T_HIGH (1 << 5)
#define ADT7420_STATUS_T_CRIT (1 << 6)
#define ADT7420_STATUS_RDY (1 << 7)
#define ADT7420_CONFIG_FAULT_QUEUE(x) (x & 0x3)
#define ADT7420_CONFIG_CT_POL (1 << 2)
#define ADT7420_CONFIG_INT_POL (1 << 3)
#define ADT7420_CONFIG_INT_CT_MODE (1 << 4)
#define ADT7420_CONFIG_OP_MODE(x) ((x & 0x3) << 5)
#define ADT7420_CONFIG_RESOLUTION (1 << 7)
#define ADT7420_FAULT_QUEUE_1_FAULT 0
#define ADT7420_FAULT_QUEUE_2_FAULTS 1
#define ADT7420_FAULT_QUEUE_3_FAULTS 2
#define ADT7420_FAULT_QUEUE_4_FAULTS 3
#define ADT7420_OP_MODE_CONT_CONV 0
#define ADT7420_OP_MODE_ONE_SHOT 1
#define ADT7420_OP_MODE_1_SPS 2
#define ADT7420_OP_MODE_SHUTDOWN 3
#define ADT7420_RESOLUTION_13BIT (13)
#define ADT7420_RESOLUTION_16BIT (16)
#define ADT7420_DEFAULT_ID 0xCB
#define EMSK_TEMP_SENSOR_CHECK_EXP_NORTN(EXPR) CHECK_EXP_NOERCD(EXPR, error_exit)
#define ADT7420_A0_PIN 1
I2C address of PmodTmp2 can be selected via jumpers: 0x48, 0x49, 0x4A, 0x4B Default (all jumpers removed) is 0x4B.
#define ADT7420_A1_PIN 1
#define ADT7420_ADDRESS (0x48 + (ADT7420_A1_PIN << 1) + ADT7420_A0_PIN)
#define TEMP_I2C_SLAVE_ADDRESS ADT7420_ADDRESS
Functions
int32_t adt7420_reg_write (uint8_t regaddr, uint8_t val)
write adt7420 register
int32_t adt7420_reg_read (uint8_t regaddr, uint8_t *val)
read adt7420 register
int32_t temp_sensor_init (uint32_t slv_addr)
temperature sensor init
int32_t temp_sensor_read (int32_t *val)
val is the return temperature in degrees Celsius (1/10 C)
Variables
static int32_t temp_resolution = ADT7420_RESOLUTION_13BIT
static DEV_IIC * emsk_temp_sensor
static uint32_t temp_sensor_slvaddr
Detailed Description
EMSK PMOD Temperature Sensor Driver.
Realize driver for PMOD temperature sensor using Designware iic driver.
Macro Definition Documentation
#define ADT7420_A0_PIN 1
I2C address of PmodTmp2 can be selected via jumpers: 0x48, 0x49, 0x4A, 0x4B Default (all jumpers removed) is 0x4B.
I2C Serial Bus Address Selection Pin
Definition at line 53 of file emsk_temperature.h.
#define ADT7420_A1_PIN 1
I2C Serial Bus Address Selection Pin
Definition at line 54 of file emsk_temperature.h.
#define ADT7420_REG_CONFIG 0x03
Configuration
Definition at line 65 of file emsk_temperature.c.
Referenced by temp_sensor_init().
#define ADT7420_REG_HIST 0x0A
Temperature HYST set point
Definition at line 72 of file emsk_temperature.c.
#define ADT7420_REG_ID 0x0B
ID
Definition at line 73 of file emsk_temperature.c.
#define ADT7420_REG_RESET 0x2F
Software reset
Definition at line 74 of file emsk_temperature.c.
#define ADT7420_REG_STATUS 0x02
Status
Definition at line 64 of file emsk_temperature.c.
#define ADT7420_REG_T_CRIT_LSB 0x09
Temperature CRIT set point LSB
Definition at line 71 of file emsk_temperature.c.
#define ADT7420_REG_T_CRIT_MSB 0x08
Temperature CRIT set point MSB
Definition at line 70 of file emsk_temperature.c.
#define ADT7420_REG_T_HIGH_LSB 0x05
Temperature HIGH set point LSB
Definition at line 67 of file emsk_temperature.c.
#define ADT7420_REG_T_HIGH_MSB 0x04
Temperature HIGH set point MSB
Definition at line 66 of file emsk_temperature.c.
#define ADT7420_REG_T_LOW_LSB 0x07
Temperature LOW set point LSB
Definition at line 69 of file emsk_temperature.c.
#define ADT7420_REG_T_LOW_MSB 0x06
Temperature LOW set point MSB
Definition at line 68 of file emsk_temperature.c.
#define ADT7420_REG_TEMP_LSB 0x01
Temperature value LSB
Definition at line 63 of file emsk_temperature.c.
Referenced by temp_sensor_read().
#define ADT7420_REG_TEMP_MSB 0x00
ADT7420 registers Temperature value MSB
Definition at line 62 of file emsk_temperature.c.
Referenced by temp_sensor_read().
Function Documentation
int32_t adt7420_reg_read (uint8_t regaddr, uint8_t * val)
read adt7420 register
Parameters
regaddr register address
val returned value
Return values
>=0 read success, return bytes read
!E_OK read failed
Definition at line 151 of file emsk_temperature.c.
References CONV2VOID, E_PAR, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_RESTART, IIC_MODE_STOP, dev_iic::iic_read, and dev_iic::iic_write.
Referenced by temp_sensor_init(), and temp_sensor_read().
int32_t adt7420_reg_write (uint8_t regaddr, uint8_t val)
write adt7420 register
Parameters
regaddr register address
val value to be written
Return values
>=0 write success, return bytes written
!E_OK write failed
Definition at line 122 of file emsk_temperature.c.
References CONV2VOID, E_PAR, IIC_CMD_MST_SET_NEXT_COND, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), IIC_MODE_STOP, and dev_iic::iic_write.
Referenced by temp_sensor_init().
int32_t temp_sensor_init (uint32_t slv_addr)
temperature sensor init
Parameters
[in] slv_addr temperature sensor iic slave address
Return values
E_OK init success
!E_OK init failed
Definition at line 183 of file emsk_temperature.c.
References ADT7420_REG_CONFIG, adt7420_reg_read(), adt7420_reg_write(), CONV2VOID, DEV_MASTER_MODE, E_OK, E_OPNED, IIC_CMD_MST_SET_TAR_ADDR, dev_iic::iic_control, iic_get_dev(), dev_iic::iic_open, and IIC_SPEED_HIGH.
int32_t temp_sensor_read (int32_t * val)
val is the return temperature in degrees Celsius (1/10 C)
read temperature sensor value in 0.1c unit
Parameters
[out] val return temperature in degrees Celsius (1/10 C)
Return values
E_OK read success
!E_OK read failed
Definition at line 216 of file emsk_temperature.c.
References adt7420_reg_read(), ADT7420_REG_TEMP_LSB, ADT7420_REG_TEMP_MSB, E_OBJ, E_OK, and iic_get_dev().