XI_TEST_ELF := $(XI_BINDIR)/libxively_cortex-m3-qemu_unit_test.elf
XI_TEST_SIM := qemu-system-arm -cpu cortex-m3 -nographic -monitor null -serial null -semihosting -kernel
XI_TEST_LOG := /tmp/libxively_cortex-m3-qemu_unit_test.log

$(XI_BINDIR)/libxively_cortex-m3-qemu_unit_test: $(XI_TEST_ELF) $(XI_TEST_DEPENDS)
	@-mkdir -p $(dir $@)
	$(XI_TEST_SIM) $(XI_TEST_ELF) | tee $(XI_TEST_LOG)
	grep -q 'status: 0' $(XI_TEST_LOG)

$(XI_TEST_ELF): $(XI_TEST_SOURCES) $(XI_TEST_DEPENDS)
	@-mkdir -p $(dir $@)
	$(CC) $(XI_CFLAGS) $(XI_TEST_SOURCES) -o $@
