XI_UNIT_TEST_TARGET ?= native
XI_IO_LAYER ?= dummy

export XI_IO_LAYER

ifndef XI_UNIT_TEST_DEFAULTS
export XI_UNIT_TEST_DEFAULTS = ""

ifeq ($(XI_UNIT_TEST_TARGET),cortex-m3-qemu)
  CC = arm-none-eabi-gcc
  AR = arm-none-eabi-ar
  XI_DEBUG_ASSERT = 0
  XI_DEBUG_OUTPUT = 1
  XI_CFLAGS += -mcpu=cortex-m3 -mthumb -T generic-hosted.ld

  export CC AR
  export XI_DEBUG_ASSERT XI_DEBUG_OUTPUT
endif

ifeq ($(XI_UNIT_TEST_TARGET),avr)
  CC = avr-gcc
  AR = avr-ar
  XI_DEBUG_ASSERT = 0
  XI_DEBUG_OUTPUT = 0
  XI_CFLAGS += -mmcu=atmega2560

  export CC AR
  export XI_DEBUG_ASSERT XI_DEBUG_OUTPUT
endif

ifeq ($(XI_UNIT_TEST_TARGET),native)
  XI_CFLAGS += -DXI_UNIT_TEST_NATIVE=1
else
  XI_CFLAGS += -DXI_UNIT_TEST_NATIVE=0
endif

export XI_CFLAGS
endif
