AVRTEST_SRCDIR ?= ../import/avrtest/
AVRTEST_CFLAGS += -I$(AVRTEST_SRCDIR)
AVRTEST_CFLAGS += -W -Wall -Wno-unused-parameter -Wno-attributes

XI_CFLAGS += -I$(AVRTEST_SRCDIR)

XI_TEST_ELF := $(XI_BINDIR)/libxively_avr_unit_test.elf
XI_TEST_SIM := $(XI_BINDIR)/avrtest

XI_TEST_SOURCES += $(XI_OBJDIR)/avrtest/exit.o
XI_TEST_DEPENDS += $(XI_TEST_SIM)

$(XI_BINDIR)/libxively_avr_unit_test: $(XI_TEST_ELF) $(XI_TEST_DEPENDS)
	@-mkdir -p $(dir $@)
	$(XI_TEST_SIM) -mmcu=avr6 $(XI_TEST_ELF)

$(XI_TEST_ELF): $(XI_TEST_SOURCES) $(XI_TEST_DEPENDS)
	@-mkdir -p $(dir $@)
	$(CC) $(XI_CFLAGS) $(XI_TEST_SOURCES) -o $@

$(AVRTEST_SRCDIR)/gen-flag-tables: $(AVRTEST_SRCDIR)/gen-flag-tables.c
	gcc $(AVRTEST_CFLAGS) $^ -o $@

$(AVRTEST_SRCDIR)/flag-tables.c: $(AVRTEST_SRCDIR)/gen-flag-tables
	$^ > $@

$(XI_TEST_SIM): $(AVRTEST_SRCDIR)/flag-tables.c $(AVRTEST_SRCDIR)/avrtest.c
	@-mkdir -p $(dir $@)
	gcc $(AVRTEST_CFLAGS) $(AVRTEST_SRCDIR)/avrtest.c -o $@

$(XI_OBJDIR)/avrtest/exit.o: $(AVRTEST_SRCDIR)/dejagnuboards/exit.c
	@-mkdir -p $(dir $@)
	avr-gcc $(XI_CFLAGS) -mmcu=atmega2560 -c $^ -o $@
